ANNarchy iCub Interface: iCubInterfaceMessages::TestRequest Class Reference
iCubInterfaceMessages::TestRequest Class Reference
#include <icub.pb.h>
Public Member Functions
TestRequest ()
virtual ~TestRequest ()
TestRequest (const TestRequest &from)
TestRequest & operator= (const TestRequest &from)
void Swap (TestRequest *other)
TestRequest * New () const final
TestRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const TestRequest &from)
void MergeFrom (const TestRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
TestRequest ()
virtual ~TestRequest ()
TestRequest (const TestRequest &from)
TestRequest & operator= (const TestRequest &from)
void Swap (TestRequest *other)
TestRequest * New () const final
TestRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const TestRequest &from)
void MergeFrom (const TestRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const TestRequest & default_instance ()
static void InitAsDefaultInstance ()
static const TestRequest * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const TestRequest & default_instance ()
static void InitAsDefaultInstance ()
static const TestRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (TestRequest &a, TestRequest &b)
void swap (TestRequest &a, TestRequest &b)
Detailed Description
Definition at line 303 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
TestRequest() [1/4]
iCubInterfaceMessages::TestRequest::TestRequest ()
Definition at line 1218 of file icub.pb.cc.
~TestRequest() [1/2]
iCubInterfaceMessages::TestRequest::~TestRequest () virtual
Definition at line 1235 of file icub.pb.cc.
TestRequest() [2/4]
iCubInterfaceMessages::TestRequest::TestRequest (const TestRequest & from)
Definition at line 1225 of file icub.pb.cc.
TestRequest() [3/4]
iCubInterfaceMessages::TestRequest::TestRequest ()
~TestRequest() [2/2]
virtual iCubInterfaceMessages::TestRequest::~TestRequest () virtual
TestRequest() [4/4]
iCubInterfaceMessages::TestRequest::TestRequest (const TestRequest & from)
Member Function Documentation
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::TestRequest::ByteSizeLong () const final
Definition at line 1319 of file icub.pb.cc.
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::TestRequest::ByteSizeLong () const final
Clear() [1/2]
void iCubInterfaceMessages::TestRequest::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::TestRequest::Clear () final
Definition at line 1257 of file icub.pb.cc.
Referenced by CopyFrom().
CopyFrom() [1/4]
void iCubInterfaceMessages::TestRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 1357 of file icub.pb.cc.
CopyFrom() [2/4]
void iCubInterfaceMessages::TestRequest::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [3/4]
void iCubInterfaceMessages::TestRequest::CopyFrom (const TestRequest & from)
Definition at line 1364 of file icub.pb.cc.
CopyFrom() [4/4]
void iCubInterfaceMessages::TestRequest::CopyFrom (const TestRequest & from)
default_instance() [1/2]
const TestRequest & iCubInterfaceMessages::TestRequest::default_instance () static
Definition at line 1251 of file icub.pb.cc.
default_instance() [2/2]
static const TestRequest& iCubInterfaceMessages::TestRequest::default_instance () static
descriptor() [1/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::TestRequest::descriptor () static
descriptor() [2/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::TestRequest::descriptor () static
Definition at line 1246 of file icub.pb.cc.
GetCachedSize() [1/2]
int iCubInterfaceMessages::TestRequest::GetCachedSize () const inline final
Definition at line 368 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::TestRequest::GetCachedSize () const inline final
Definition at line 368 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
google::protobuf::Metadata iCubInterfaceMessages::TestRequest::GetMetadata () const final
Definition at line 1384 of file icub.pb.cc.
GetMetadata() [2/2]
::google::protobuf::Metadata iCubInterfaceMessages::TestRequest::GetMetadata () const final
InitAsDefaultInstance() [1/2]
void iCubInterfaceMessages::TestRequest::InitAsDefaultInstance () static
Definition at line 1213 of file icub.pb.cc.
InitAsDefaultInstance() [2/2]
static void iCubInterfaceMessages::TestRequest::InitAsDefaultInstance () static
internal_default_instance() [1/2]
static const TestRequest* iCubInterfaceMessages::TestRequest::internal_default_instance () inline static
Definition at line 333 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
internal_default_instance() [2/2]
static const TestRequest* iCubInterfaceMessages::TestRequest::internal_default_instance () inline static
Definition at line 333 of file iCub_ANN_Interface/grpc/icub.pb.h.
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::TestRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 1304 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::TestRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::TestRequest::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::TestRequest::IsInitialized () const final
Definition at line 1371 of file icub.pb.cc.
MergeFrom() [1/4]
void iCubInterfaceMessages::TestRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 1333 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/4]
void iCubInterfaceMessages::TestRequest::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [3/4]
void iCubInterfaceMessages::TestRequest::MergeFrom (const TestRequest & from)
MergeFrom() [4/4]
void iCubInterfaceMessages::TestRequest::MergeFrom (const TestRequest & from)
Definition at line 1348 of file icub.pb.cc.
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::TestRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::TestRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 1266 of file icub.pb.cc.
New() [1/4]
TestRequest* iCubInterfaceMessages::TestRequest::New () const inline final
Definition at line 347 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
TestRequest* iCubInterfaceMessages::TestRequest::New () const inline final
Definition at line 347 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
TestRequest* iCubInterfaceMessages::TestRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 351 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
TestRequest* iCubInterfaceMessages::TestRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 351 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
TestRequest& iCubInterfaceMessages::TestRequest::operator= (const TestRequest & from) inline
Definition at line 310 of file iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
TestRequest& iCubInterfaceMessages::TestRequest::operator= (const TestRequest & from) inline
Definition at line 310 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::TestRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 1291 of file icub.pb.cc.
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::TestRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Swap() [1/2]
void iCubInterfaceMessages::TestRequest::Swap (TestRequest * other)
Definition at line 1375 of file icub.pb.cc.
Swap() [2/2]
void iCubInterfaceMessages::TestRequest::Swap (TestRequest * other)
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 395 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (TestRequest & a, TestRequest & b) friend
Definition at line 341 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (TestRequest & a, TestRequest & b) friend
Definition at line 341 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::TestRequest::kIndexInFileMessages static constexpr
Initial value:
=
    1
Definition at line 337 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc