ANNarchy iCub Interface: iCubInterfaceMessages::AllTargetEncodedRequest Class Reference
iCubInterfaceMessages::AllTargetEncodedRequest Class Reference
#include <icub.pb.h>
Public Member Functions
AllTargetEncodedRequest ()
virtual ~AllTargetEncodedRequest ()
AllTargetEncodedRequest (const AllTargetEncodedRequest &from)
AllTargetEncodedRequest & operator= (const AllTargetEncodedRequest &from)
void Swap (AllTargetEncodedRequest *other)
AllTargetEncodedRequest * New () const final
AllTargetEncodedRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const AllTargetEncodedRequest &from)
void MergeFrom (const AllTargetEncodedRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
AllTargetEncodedRequest ()
virtual ~AllTargetEncodedRequest ()
AllTargetEncodedRequest (const AllTargetEncodedRequest &from)
AllTargetEncodedRequest & operator= (const AllTargetEncodedRequest &from)
void Swap (AllTargetEncodedRequest *other)
AllTargetEncodedRequest * New () const final
AllTargetEncodedRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const AllTargetEncodedRequest &from)
void MergeFrom (const AllTargetEncodedRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const AllTargetEncodedRequest & default_instance ()
static void InitAsDefaultInstance ()
static const AllTargetEncodedRequest * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const AllTargetEncodedRequest & default_instance ()
static void InitAsDefaultInstance ()
static const AllTargetEncodedRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (AllTargetEncodedRequest &a, AllTargetEncodedRequest &b)
void swap (AllTargetEncodedRequest &a, AllTargetEncodedRequest &b)
Detailed Description
Definition at line 2482 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
AllTargetEncodedRequest() [1/4]
iCubInterfaceMessages::AllTargetEncodedRequest::AllTargetEncodedRequest ()
Definition at line 6176 of file icub.pb.cc.
~AllTargetEncodedRequest() [1/2]
iCubInterfaceMessages::AllTargetEncodedRequest::~AllTargetEncodedRequest () virtual
Definition at line 6193 of file icub.pb.cc.
AllTargetEncodedRequest() [2/4]
iCubInterfaceMessages::AllTargetEncodedRequest::AllTargetEncodedRequest (const AllTargetEncodedRequest & from)
Definition at line 6183 of file icub.pb.cc.
AllTargetEncodedRequest() [3/4]
iCubInterfaceMessages::AllTargetEncodedRequest::AllTargetEncodedRequest ()
~AllTargetEncodedRequest() [2/2]
virtual iCubInterfaceMessages::AllTargetEncodedRequest::~AllTargetEncodedRequest () virtual
AllTargetEncodedRequest() [4/4]
iCubInterfaceMessages::AllTargetEncodedRequest::AllTargetEncodedRequest (const AllTargetEncodedRequest & from)
Member Function Documentation
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::AllTargetEncodedRequest::ByteSizeLong () const final
Definition at line 6277 of file icub.pb.cc.
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::AllTargetEncodedRequest::ByteSizeLong () const final
Clear() [1/2]
void iCubInterfaceMessages::AllTargetEncodedRequest::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::AllTargetEncodedRequest::Clear () final
Definition at line 6215 of file icub.pb.cc.
Referenced by CopyFrom().
CopyFrom() [1/4]
void iCubInterfaceMessages::AllTargetEncodedRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 6315 of file icub.pb.cc.
CopyFrom() [2/4]
void iCubInterfaceMessages::AllTargetEncodedRequest::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [3/4]
void iCubInterfaceMessages::AllTargetEncodedRequest::CopyFrom (const AllTargetEncodedRequest & from)
Definition at line 6322 of file icub.pb.cc.
CopyFrom() [4/4]
void iCubInterfaceMessages::AllTargetEncodedRequest::CopyFrom (const AllTargetEncodedRequest & from)
default_instance() [1/2]
const AllTargetEncodedRequest & iCubInterfaceMessages::AllTargetEncodedRequest::default_instance () static
Definition at line 6209 of file icub.pb.cc.
default_instance() [2/2]
static const AllTargetEncodedRequest& iCubInterfaceMessages::AllTargetEncodedRequest::default_instance () static
descriptor() [1/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::AllTargetEncodedRequest::descriptor () static
descriptor() [2/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::AllTargetEncodedRequest::descriptor () static
Definition at line 6204 of file icub.pb.cc.
GetCachedSize() [1/2]
int iCubInterfaceMessages::AllTargetEncodedRequest::GetCachedSize () const inline final
Definition at line 2547 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::AllTargetEncodedRequest::GetCachedSize () const inline final
Definition at line 2547 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
google::protobuf::Metadata iCubInterfaceMessages::AllTargetEncodedRequest::GetMetadata () const final
Definition at line 6342 of file icub.pb.cc.
GetMetadata() [2/2]
::google::protobuf::Metadata iCubInterfaceMessages::AllTargetEncodedRequest::GetMetadata () const final
InitAsDefaultInstance() [1/2]
void iCubInterfaceMessages::AllTargetEncodedRequest::InitAsDefaultInstance () static
Definition at line 6171 of file icub.pb.cc.
InitAsDefaultInstance() [2/2]
static void iCubInterfaceMessages::AllTargetEncodedRequest::InitAsDefaultInstance () static
internal_default_instance() [1/2]
static const AllTargetEncodedRequest* iCubInterfaceMessages::AllTargetEncodedRequest::internal_default_instance () inline static
Definition at line 2512 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
internal_default_instance() [2/2]
static const AllTargetEncodedRequest* iCubInterfaceMessages::AllTargetEncodedRequest::internal_default_instance () inline static
Definition at line 2512 of file iCub_ANN_Interface/grpc/icub.pb.h.
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::AllTargetEncodedRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 6262 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::AllTargetEncodedRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::AllTargetEncodedRequest::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::AllTargetEncodedRequest::IsInitialized () const final
Definition at line 6329 of file icub.pb.cc.
MergeFrom() [1/4]
void iCubInterfaceMessages::AllTargetEncodedRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 6291 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/4]
void iCubInterfaceMessages::AllTargetEncodedRequest::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [3/4]
void iCubInterfaceMessages::AllTargetEncodedRequest::MergeFrom (const AllTargetEncodedRequest & from)
MergeFrom() [4/4]
void iCubInterfaceMessages::AllTargetEncodedRequest::MergeFrom (const AllTargetEncodedRequest & from)
Definition at line 6306 of file icub.pb.cc.
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::AllTargetEncodedRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::AllTargetEncodedRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 6224 of file icub.pb.cc.
New() [1/4]
AllTargetEncodedRequest* iCubInterfaceMessages::AllTargetEncodedRequest::New () const inline final
Definition at line 2526 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
AllTargetEncodedRequest* iCubInterfaceMessages::AllTargetEncodedRequest::New () const inline final
Definition at line 2526 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
AllTargetEncodedRequest* iCubInterfaceMessages::AllTargetEncodedRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 2530 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
AllTargetEncodedRequest* iCubInterfaceMessages::AllTargetEncodedRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 2530 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
AllTargetEncodedRequest& iCubInterfaceMessages::AllTargetEncodedRequest::operator= (const AllTargetEncodedRequest & from) inline
Definition at line 2489 of file iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
AllTargetEncodedRequest& iCubInterfaceMessages::AllTargetEncodedRequest::operator= (const AllTargetEncodedRequest & from) inline
Definition at line 2489 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::AllTargetEncodedRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 6249 of file icub.pb.cc.
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::AllTargetEncodedRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Swap() [1/2]
void iCubInterfaceMessages::AllTargetEncodedRequest::Swap (AllTargetEncodedRequest * other)
Definition at line 6333 of file icub.pb.cc.
Swap() [2/2]
void iCubInterfaceMessages::AllTargetEncodedRequest::Swap (AllTargetEncodedRequest * other)
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 2574 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (AllTargetEncodedRequest & a, AllTargetEncodedRequest & b) friend
Definition at line 2520 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (AllTargetEncodedRequest & a, AllTargetEncodedRequest & b) friend
Definition at line 2520 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::AllTargetEncodedRequest::kIndexInFileMessages static constexpr
Initial value:
=
    21
Definition at line 2516 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc