ANNarchy iCub Interface: iCubInterfaceMessages::MultiTargetResponse Class Reference
iCubInterfaceMessages::MultiTargetResponse Class Reference
#include <icub.pb.h>
Public Member Functions
MultiTargetResponse ()
virtual ~MultiTargetResponse ()
MultiTargetResponse (const MultiTargetResponse &from)
MultiTargetResponse & operator= (const MultiTargetResponse &from)
void Swap (MultiTargetResponse *other)
MultiTargetResponse * New () const final
MultiTargetResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const MultiTargetResponse &from)
void MergeFrom (const MultiTargetResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
MultiTargetResponse ()
virtual ~MultiTargetResponse ()
MultiTargetResponse (const MultiTargetResponse &from)
MultiTargetResponse & operator= (const MultiTargetResponse &from)
void Swap (MultiTargetResponse *other)
MultiTargetResponse * New () const final
MultiTargetResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const MultiTargetResponse &from)
void MergeFrom (const MultiTargetResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const MultiTargetResponse & default_instance ()
static void InitAsDefaultInstance ()
static const MultiTargetResponse * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const MultiTargetResponse & default_instance ()
static void InitAsDefaultInstance ()
static const MultiTargetResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kAngleFieldNumber = 2
static const int kStatusFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (MultiTargetResponse &a, MultiTargetResponse &b)
void swap (MultiTargetResponse &a, MultiTargetResponse &b)
Detailed Description
Definition at line 1719 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
MultiTargetResponse() [1/4]
iCubInterfaceMessages::MultiTargetResponse::MultiTargetResponse ()
Definition at line 4449 of file icub.pb.cc.
~MultiTargetResponse() [1/2]
iCubInterfaceMessages::MultiTargetResponse::~MultiTargetResponse () virtual
Definition at line 4469 of file icub.pb.cc.
MultiTargetResponse() [2/4]
iCubInterfaceMessages::MultiTargetResponse::MultiTargetResponse (const MultiTargetResponse & from)
Definition at line 4456 of file icub.pb.cc.
MultiTargetResponse() [3/4]
iCubInterfaceMessages::MultiTargetResponse::MultiTargetResponse ()
~MultiTargetResponse() [2/2]
virtual iCubInterfaceMessages::MultiTargetResponse::~MultiTargetResponse () virtual
MultiTargetResponse() [4/4]
iCubInterfaceMessages::MultiTargetResponse::MultiTargetResponse (const MultiTargetResponse & from)
Member Function Documentation
add_angle() [1/2]
void iCubInterfaceMessages::MultiTargetResponse::add_angle (double value) inline
Definition at line 3683 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
add_angle() [2/2]
void iCubInterfaceMessages::MultiTargetResponse::add_angle (double value)
angle() [1/4]
const ::google::protobuf::RepeatedField< double > & iCubInterfaceMessages::MultiTargetResponse::angle () const inline
Definition at line 3688 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by SerializeWithCachedSizes().
angle() [2/4]
const ::google::protobuf::RepeatedField< double >& iCubInterfaceMessages::MultiTargetResponse::angle () const
angle() [3/4]
double iCubInterfaceMessages::MultiTargetResponse::angle (int index) const inline
Definition at line 3675 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by WriteClientInstance::retrieve_multitarget().
angle() [4/4]
double iCubInterfaceMessages::MultiTargetResponse::angle (int index) const
angle_size() [1/2]
int iCubInterfaceMessages::MultiTargetResponse::angle_size () const inline
Definition at line 3669 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
angle_size() [2/2]
int iCubInterfaceMessages::MultiTargetResponse::angle_size () const
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::MultiTargetResponse::ByteSizeLong () const final
Definition at line 4628 of file icub.pb.cc.
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::MultiTargetResponse::ByteSizeLong () const final
Clear() [1/2]
void iCubInterfaceMessages::MultiTargetResponse::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::MultiTargetResponse::Clear () final
Definition at line 4491 of file icub.pb.cc.
Referenced by CopyFrom().
clear_angle() [1/2]
void iCubInterfaceMessages::MultiTargetResponse::clear_angle () inline
Definition at line 3672 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_angle() [2/2]
void iCubInterfaceMessages::MultiTargetResponse::clear_angle ()
clear_status() [1/2]
void iCubInterfaceMessages::MultiTargetResponse::clear_status () inline
Definition at line 3655 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_status() [2/2]
void iCubInterfaceMessages::MultiTargetResponse::clear_status ()
CopyFrom() [1/4]
void iCubInterfaceMessages::MultiTargetResponse::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/4]
void iCubInterfaceMessages::MultiTargetResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 4692 of file icub.pb.cc.
CopyFrom() [3/4]
void iCubInterfaceMessages::MultiTargetResponse::CopyFrom (const MultiTargetResponse & from)
CopyFrom() [4/4]
void iCubInterfaceMessages::MultiTargetResponse::CopyFrom (const MultiTargetResponse & from)
Definition at line 4699 of file icub.pb.cc.
default_instance() [1/2]
static const MultiTargetResponse& iCubInterfaceMessages::MultiTargetResponse::default_instance () static
default_instance() [2/2]
const MultiTargetResponse & iCubInterfaceMessages::MultiTargetResponse::default_instance () static
Definition at line 4485 of file icub.pb.cc.
descriptor() [1/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::MultiTargetResponse::descriptor () static
descriptor() [2/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::MultiTargetResponse::descriptor () static
Definition at line 4480 of file icub.pb.cc.
GetCachedSize() [1/2]
int iCubInterfaceMessages::MultiTargetResponse::GetCachedSize () const inline final
Definition at line 1784 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::MultiTargetResponse::GetCachedSize () const inline final
Definition at line 1784 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
google::protobuf::Metadata iCubInterfaceMessages::MultiTargetResponse::GetMetadata () const final
Definition at line 4721 of file icub.pb.cc.
GetMetadata() [2/2]
::google::protobuf::Metadata iCubInterfaceMessages::MultiTargetResponse::GetMetadata () const final
InitAsDefaultInstance() [1/2]
static void iCubInterfaceMessages::MultiTargetResponse::InitAsDefaultInstance () static
InitAsDefaultInstance() [2/2]
void iCubInterfaceMessages::MultiTargetResponse::InitAsDefaultInstance () static
Definition at line 4442 of file icub.pb.cc.
internal_default_instance() [1/2]
static const MultiTargetResponse* iCubInterfaceMessages::MultiTargetResponse::internal_default_instance () inline static
Definition at line 1749 of file iCub_ANN_Interface/grpc/icub.pb.h.
internal_default_instance() [2/2]
static const MultiTargetResponse* iCubInterfaceMessages::MultiTargetResponse::internal_default_instance () inline static
Definition at line 1749 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::MultiTargetResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 4594 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::MultiTargetResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::MultiTargetResponse::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::MultiTargetResponse::IsInitialized () const final
Definition at line 4706 of file icub.pb.cc.
MergeFrom() [1/4]
void iCubInterfaceMessages::MultiTargetResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 4664 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/4]
void iCubInterfaceMessages::MultiTargetResponse::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [3/4]
void iCubInterfaceMessages::MultiTargetResponse::MergeFrom (const MultiTargetResponse & from)
MergeFrom() [4/4]
void iCubInterfaceMessages::MultiTargetResponse::MergeFrom (const MultiTargetResponse & from)
Definition at line 4679 of file icub.pb.cc.
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::MultiTargetResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 4502 of file icub.pb.cc.
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::MultiTargetResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_angle() [1/2]
::google::protobuf::RepeatedField< double >* iCubInterfaceMessages::MultiTargetResponse::mutable_angle ()
mutable_angle() [2/2]
google::protobuf::RepeatedField< double > * iCubInterfaceMessages::MultiTargetResponse::mutable_angle () inline
Definition at line 3693 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/4]
MultiTargetResponse* iCubInterfaceMessages::MultiTargetResponse::New () const inline final
Definition at line 1763 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
MultiTargetResponse* iCubInterfaceMessages::MultiTargetResponse::New () const inline final
Definition at line 1763 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
MultiTargetResponse* iCubInterfaceMessages::MultiTargetResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1767 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
MultiTargetResponse* iCubInterfaceMessages::MultiTargetResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1767 of file iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
MultiTargetResponse& iCubInterfaceMessages::MultiTargetResponse::operator= (const MultiTargetResponse & from) inline
Definition at line 1726 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
MultiTargetResponse& iCubInterfaceMessages::MultiTargetResponse::operator= (const MultiTargetResponse & from) inline
Definition at line 1726 of file iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::MultiTargetResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 4566 of file icub.pb.cc.
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::MultiTargetResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_angle() [1/2]
void iCubInterfaceMessages::MultiTargetResponse::set_angle (int index, double value)
set_angle() [2/2]
void iCubInterfaceMessages::MultiTargetResponse::set_angle (int index, double value) inline
Definition at line 3679 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
set_status() [1/2]
void iCubInterfaceMessages::MultiTargetResponse::set_status (::iCubInterfaceMessages::Status value)
set_status() [2/2]
void iCubInterfaceMessages::MultiTargetResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 3662 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status() [1/2]
iCubInterfaceMessages::Status iCubInterfaceMessages::MultiTargetResponse::status () const inline
Definition at line 3658 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
status() [2/2]
::iCubInterfaceMessages::Status iCubInterfaceMessages::MultiTargetResponse::status () const
Swap() [1/2]
void iCubInterfaceMessages::MultiTargetResponse::Swap (MultiTargetResponse * other)
Definition at line 4710 of file icub.pb.cc.
Swap() [2/2]
void iCubInterfaceMessages::MultiTargetResponse::Swap (MultiTargetResponse * other)
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 1832 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (MultiTargetResponse & a, MultiTargetResponse & b) friend
Definition at line 1757 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (MultiTargetResponse & a, MultiTargetResponse & b) friend
Definition at line 1757 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kAngleFieldNumber
static const int iCubInterfaceMessages::MultiTargetResponse::kAngleFieldNumber = 2 static
Definition at line 1809 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::MultiTargetResponse::kIndexInFileMessages static constexpr
Initial value:
=
    14
Definition at line 1753 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kStatusFieldNumber
static const int iCubInterfaceMessages::MultiTargetResponse::kStatusFieldNumber = 1 static
Definition at line 1820 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc