ANNarchy iCub Interface: iCubInterfaceMessages::AllJointEncodedRequest Class Reference
iCubInterfaceMessages::AllJointEncodedRequest Class Reference
#include <icub.pb.h>
Public Member Functions
AllJointEncodedRequest ()
virtual ~AllJointEncodedRequest ()
AllJointEncodedRequest (const AllJointEncodedRequest &from)
AllJointEncodedRequest & operator= (const AllJointEncodedRequest &from)
void Swap (AllJointEncodedRequest *other)
AllJointEncodedRequest * New () const final
AllJointEncodedRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const AllJointEncodedRequest &from)
void MergeFrom (const AllJointEncodedRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_part ()
const ::std::string & part () const
void set_part (const ::std::string &value)
void set_part (const char *value)
void set_part (const char *value, size_t size)
::std::string * mutable_part ()
::std::string * release_part ()
void set_allocated_part (::std::string *part)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const AllJointEncodedRequest & default_instance ()
static void InitAsDefaultInstance ()
static const AllJointEncodedRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kPartFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (AllJointEncodedRequest &a, AllJointEncodedRequest &b)
Detailed Description
Definition at line 1208 of file icub.pb.h.
Constructor & Destructor Documentation
AllJointEncodedRequest() [1/2]
iCubInterfaceMessages::AllJointEncodedRequest::AllJointEncodedRequest ()
Definition at line 3257 of file icub.pb.cc.
~AllJointEncodedRequest()
iCubInterfaceMessages::AllJointEncodedRequest::~AllJointEncodedRequest () virtual
Definition at line 3279 of file icub.pb.cc.
AllJointEncodedRequest() [2/2]
iCubInterfaceMessages::AllJointEncodedRequest::AllJointEncodedRequest (const AllJointEncodedRequest & from)
Definition at line 3264 of file icub.pb.cc.
Member Function Documentation
ByteSizeLong()
size_t iCubInterfaceMessages::AllJointEncodedRequest::ByteSizeLong () const final
Definition at line 3407 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::AllJointEncodedRequest::Clear () final
Definition at line 3302 of file icub.pb.cc.
Referenced by CopyFrom().
clear_part()
void iCubInterfaceMessages::AllJointEncodedRequest::clear_part () inline
Definition at line 3072 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::AllJointEncodedRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 3456 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::AllJointEncodedRequest::CopyFrom (const AllJointEncodedRequest & from)
Definition at line 3463 of file icub.pb.cc.
default_instance()
const AllJointEncodedRequest & iCubInterfaceMessages::AllJointEncodedRequest::default_instance () static
Definition at line 3296 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::AllJointEncodedRequest::descriptor () static
Definition at line 3291 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::AllJointEncodedRequest::GetCachedSize () const inline final
Definition at line 1273 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::AllJointEncodedRequest::GetMetadata () const final
Definition at line 3485 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::AllJointEncodedRequest::InitAsDefaultInstance () static
Definition at line 3251 of file icub.pb.cc.
internal_default_instance()
static const AllJointEncodedRequest* iCubInterfaceMessages::AllJointEncodedRequest::internal_default_instance () inline static
Definition at line 1238 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::AllJointEncodedRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 3381 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::AllJointEncodedRequest::IsInitialized () const final
Definition at line 3470 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::AllJointEncodedRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 3428 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::AllJointEncodedRequest::MergeFrom (const AllJointEncodedRequest & from)
Definition at line 3443 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::AllJointEncodedRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 3312 of file icub.pb.cc.
mutable_part()
std::string * iCubInterfaceMessages::AllJointEncodedRequest::mutable_part () inline
Definition at line 3104 of file icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/2]
AllJointEncodedRequest* iCubInterfaceMessages::AllJointEncodedRequest::New () const inline final
Definition at line 1252 of file icub.pb.h.
New() [2/2]
AllJointEncodedRequest* iCubInterfaceMessages::AllJointEncodedRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1256 of file icub.pb.h.
operator=()
AllJointEncodedRequest& iCubInterfaceMessages::AllJointEncodedRequest::operator= (const AllJointEncodedRequest & from) inline
Definition at line 1215 of file icub.pb.h.
part()
const ::std::string & iCubInterfaceMessages::AllJointEncodedRequest::part () const inline
Definition at line 3075 of file icub.pb.h.
Referenced by AllJointEncodedRequest(), ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), and SerializeWithCachedSizes().
release_part()
std::string * iCubInterfaceMessages::AllJointEncodedRequest::release_part () inline
Definition at line 3109 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::AllJointEncodedRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 3358 of file icub.pb.cc.
set_allocated_part()
void iCubInterfaceMessages::AllJointEncodedRequest::set_allocated_part (::std::string * part) inline
Definition at line 3114 of file icub.pb.h.
set_part() [1/3]
void iCubInterfaceMessages::AllJointEncodedRequest::set_part (const ::std::string & value) inline
Definition at line 3079 of file icub.pb.h.
set_part() [2/3]
void iCubInterfaceMessages::AllJointEncodedRequest::set_part (const char * value) inline
Definition at line 3092 of file icub.pb.h.
set_part() [3/3]
void iCubInterfaceMessages::AllJointEncodedRequest::set_part (const char * value, size_t size) inline
Definition at line 3098 of file icub.pb.h.
Swap()
void iCubInterfaceMessages::AllJointEncodedRequest::Swap (AllJointEncodedRequest * other)
Definition at line 3474 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 1315 of file icub.pb.h.
swap
void swap (AllJointEncodedRequest & a, AllJointEncodedRequest & b) friend
Definition at line 1246 of file icub.pb.h.
Member Data Documentation
kIndexInFileMessages
constexpr int iCubInterfaceMessages::AllJointEncodedRequest::kIndexInFileMessages static constexpr
Initial value:
=
    9
Definition at line 1242 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kPartFieldNumber
const int iCubInterfaceMessages::AllJointEncodedRequest::kPartFieldNumber = 1 static
Definition at line 1297 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc