ANNarchy iCub Interface: iCubInterfaceMessages::SingleTargetEncodedRequest Class Reference
iCubInterfaceMessages::SingleTargetEncodedRequest Class Reference
#include <icub.pb.h>
Public Member Functions
SingleTargetEncodedRequest ()
virtual ~SingleTargetEncodedRequest ()
SingleTargetEncodedRequest (const SingleTargetEncodedRequest &from)
SingleTargetEncodedRequest & operator= (const SingleTargetEncodedRequest &from)
void Swap (SingleTargetEncodedRequest *other)
SingleTargetEncodedRequest * New () const final
SingleTargetEncodedRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SingleTargetEncodedRequest &from)
void MergeFrom (const SingleTargetEncodedRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_part ()
const ::std::string & part () const
void set_part (const ::std::string &value)
void set_part (const char *value)
void set_part (const char *value, size_t size)
::std::string * mutable_part ()
::std::string * release_part ()
void set_allocated_part (::std::string *part)
void clear_joint ()
::google::protobuf::int32 joint () const
void set_joint (::google::protobuf::int32 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SingleTargetEncodedRequest & default_instance ()
static void InitAsDefaultInstance ()
static const SingleTargetEncodedRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kPartFieldNumber = 1
static const int kJointFieldNumber = 2
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (SingleTargetEncodedRequest &a, SingleTargetEncodedRequest &b)
Detailed Description
Definition at line 1861 of file icub.pb.h.
Constructor & Destructor Documentation
SingleTargetEncodedRequest() [1/2]
iCubInterfaceMessages::SingleTargetEncodedRequest::SingleTargetEncodedRequest ()
Definition at line 4724 of file icub.pb.cc.
~SingleTargetEncodedRequest()
iCubInterfaceMessages::SingleTargetEncodedRequest::~SingleTargetEncodedRequest () virtual
Definition at line 4748 of file icub.pb.cc.
SingleTargetEncodedRequest() [2/2]
iCubInterfaceMessages::SingleTargetEncodedRequest::SingleTargetEncodedRequest (const SingleTargetEncodedRequest & from)
Definition at line 4731 of file icub.pb.cc.
Member Function Documentation
ByteSizeLong()
size_t iCubInterfaceMessages::SingleTargetEncodedRequest::ByteSizeLong () const final
Definition at line 4901 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::SingleTargetEncodedRequest::Clear () final
Definition at line 4771 of file icub.pb.cc.
Referenced by CopyFrom().
clear_joint()
void iCubInterfaceMessages::SingleTargetEncodedRequest::clear_joint () inline
Definition at line 3332 of file icub.pb.h.
clear_part()
void iCubInterfaceMessages::SingleTargetEncodedRequest::clear_part () inline
Definition at line 3279 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::SingleTargetEncodedRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 4960 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::SingleTargetEncodedRequest::CopyFrom (const SingleTargetEncodedRequest & from)
Definition at line 4967 of file icub.pb.cc.
default_instance()
const SingleTargetEncodedRequest & iCubInterfaceMessages::SingleTargetEncodedRequest::default_instance () static
Definition at line 4765 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::SingleTargetEncodedRequest::descriptor () static
Definition at line 4760 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::SingleTargetEncodedRequest::GetCachedSize () const inline final
Definition at line 1926 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::SingleTargetEncodedRequest::GetMetadata () const final
Definition at line 4990 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::SingleTargetEncodedRequest::InitAsDefaultInstance () static
Definition at line 4717 of file icub.pb.cc.
internal_default_instance()
static const SingleTargetEncodedRequest* iCubInterfaceMessages::SingleTargetEncodedRequest::internal_default_instance () inline static
Definition at line 1891 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::SingleTargetEncodedRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 4870 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::SingleTargetEncodedRequest::IsInitialized () const final
Definition at line 4974 of file icub.pb.cc.
joint()
google::protobuf::int32 iCubInterfaceMessages::SingleTargetEncodedRequest::joint () const inline
Definition at line 3335 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
MergeFrom() [1/2]
void iCubInterfaceMessages::SingleTargetEncodedRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 4929 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::SingleTargetEncodedRequest::MergeFrom (const SingleTargetEncodedRequest & from)
Definition at line 4944 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::SingleTargetEncodedRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 4782 of file icub.pb.cc.
mutable_part()
std::string * iCubInterfaceMessages::SingleTargetEncodedRequest::mutable_part () inline
Definition at line 3311 of file icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/2]
SingleTargetEncodedRequest* iCubInterfaceMessages::SingleTargetEncodedRequest::New () const inline final
Definition at line 1905 of file icub.pb.h.
New() [2/2]
SingleTargetEncodedRequest* iCubInterfaceMessages::SingleTargetEncodedRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1909 of file icub.pb.h.
operator=()
SingleTargetEncodedRequest& iCubInterfaceMessages::SingleTargetEncodedRequest::operator= (const SingleTargetEncodedRequest & from) inline
Definition at line 1868 of file icub.pb.h.
part()
const ::std::string & iCubInterfaceMessages::SingleTargetEncodedRequest::part () const inline
Definition at line 3282 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), and SingleTargetEncodedRequest().
release_part()
std::string * iCubInterfaceMessages::SingleTargetEncodedRequest::release_part () inline
Definition at line 3316 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::SingleTargetEncodedRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 4842 of file icub.pb.cc.
set_allocated_part()
void iCubInterfaceMessages::SingleTargetEncodedRequest::set_allocated_part (::std::string * part) inline
Definition at line 3321 of file icub.pb.h.
set_joint()
void iCubInterfaceMessages::SingleTargetEncodedRequest::set_joint (::google::protobuf::int32 value) inline
Definition at line 3339 of file icub.pb.h.
Referenced by MergeFrom().
set_part() [1/3]
void iCubInterfaceMessages::SingleTargetEncodedRequest::set_part (const ::std::string & value) inline
Definition at line 3286 of file icub.pb.h.
set_part() [2/3]
void iCubInterfaceMessages::SingleTargetEncodedRequest::set_part (const char * value) inline
Definition at line 3299 of file icub.pb.h.
set_part() [3/3]
void iCubInterfaceMessages::SingleTargetEncodedRequest::set_part (const char * value, size_t size) inline
Definition at line 3305 of file icub.pb.h.
Swap()
void iCubInterfaceMessages::SingleTargetEncodedRequest::Swap (SingleTargetEncodedRequest * other)
Definition at line 4978 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 1975 of file icub.pb.h.
swap
void swap (SingleTargetEncodedRequest & a, SingleTargetEncodedRequest & b) friend
Definition at line 1899 of file icub.pb.h.
Member Data Documentation
kIndexInFileMessages
constexpr int iCubInterfaceMessages::SingleTargetEncodedRequest::kIndexInFileMessages static constexpr
Initial value:
=
    15
Definition at line 1895 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kJointFieldNumber
const int iCubInterfaceMessages::SingleTargetEncodedRequest::kJointFieldNumber = 2 static
Definition at line 1964 of file icub.pb.h.
kPartFieldNumber
const int iCubInterfaceMessages::SingleTargetEncodedRequest::kPartFieldNumber = 1 static
Definition at line 1950 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc