ANNarchy iCub Interface: iCubInterfaceMessages::AllTargetRequest Class Reference
iCubInterfaceMessages::AllTargetRequest Class Reference
#include <icub.pb.h>
Public Member Functions
AllTargetRequest ()
virtual ~AllTargetRequest ()
AllTargetRequest (const AllTargetRequest &from)
AllTargetRequest & operator= (const AllTargetRequest &from)
void Swap (AllTargetRequest *other)
AllTargetRequest * New () const final
AllTargetRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const AllTargetRequest &from)
void MergeFrom (const AllTargetRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const AllTargetRequest & default_instance ()
static void InitAsDefaultInstance ()
static const AllTargetRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (AllTargetRequest &a, AllTargetRequest &b)
Detailed Description
Definition at line 1648 of file icub.pb.h.
Constructor & Destructor Documentation
AllTargetRequest() [1/2]
iCubInterfaceMessages::AllTargetRequest::AllTargetRequest ()
Definition at line 4256 of file icub.pb.cc.
~AllTargetRequest()
iCubInterfaceMessages::AllTargetRequest::~AllTargetRequest () virtual
Definition at line 4273 of file icub.pb.cc.
AllTargetRequest() [2/2]
iCubInterfaceMessages::AllTargetRequest::AllTargetRequest (const AllTargetRequest & from)
Definition at line 4263 of file icub.pb.cc.
Member Function Documentation
ByteSizeLong()
size_t iCubInterfaceMessages::AllTargetRequest::ByteSizeLong () const final
Definition at line 4357 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::AllTargetRequest::Clear () final
Definition at line 4295 of file icub.pb.cc.
Referenced by CopyFrom().
CopyFrom() [1/2]
void iCubInterfaceMessages::AllTargetRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 4395 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::AllTargetRequest::CopyFrom (const AllTargetRequest & from)
Definition at line 4402 of file icub.pb.cc.
default_instance()
const AllTargetRequest & iCubInterfaceMessages::AllTargetRequest::default_instance () static
Definition at line 4289 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::AllTargetRequest::descriptor () static
Definition at line 4284 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::AllTargetRequest::GetCachedSize () const inline final
Definition at line 1713 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::AllTargetRequest::GetMetadata () const final
Definition at line 4422 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::AllTargetRequest::InitAsDefaultInstance () static
Definition at line 4251 of file icub.pb.cc.
internal_default_instance()
static const AllTargetRequest* iCubInterfaceMessages::AllTargetRequest::internal_default_instance () inline static
Definition at line 1678 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::AllTargetRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 4342 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::AllTargetRequest::IsInitialized () const final
Definition at line 4409 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::AllTargetRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 4371 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::AllTargetRequest::MergeFrom (const AllTargetRequest & from)
Definition at line 4386 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::AllTargetRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 4304 of file icub.pb.cc.
New() [1/2]
AllTargetRequest* iCubInterfaceMessages::AllTargetRequest::New () const inline final
Definition at line 1692 of file icub.pb.h.
New() [2/2]
AllTargetRequest* iCubInterfaceMessages::AllTargetRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1696 of file icub.pb.h.
operator=()
AllTargetRequest& iCubInterfaceMessages::AllTargetRequest::operator= (const AllTargetRequest & from) inline
Definition at line 1655 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::AllTargetRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 4329 of file icub.pb.cc.
Swap()
void iCubInterfaceMessages::AllTargetRequest::Swap (AllTargetRequest * other)
Definition at line 4413 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 1740 of file icub.pb.h.
swap
void swap (AllTargetRequest & a, AllTargetRequest & b) friend
Definition at line 1686 of file icub.pb.h.
Member Data Documentation
kIndexInFileMessages
constexpr int iCubInterfaceMessages::AllTargetRequest::kIndexInFileMessages static constexpr
Initial value:
=
    13
Definition at line 1682 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc