ANNarchy iCub Interface: iCubInterfaceMessages::MultiTargetRequest Class Reference
iCubInterfaceMessages::MultiTargetRequest Class Reference
#include <icub.pb.h>
Public Member Functions
MultiTargetRequest ()
virtual ~MultiTargetRequest ()
MultiTargetRequest (const MultiTargetRequest &from)
MultiTargetRequest & operator= (const MultiTargetRequest &from)
void Swap (MultiTargetRequest *other)
MultiTargetRequest * New () const final
MultiTargetRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const MultiTargetRequest &from)
void MergeFrom (const MultiTargetRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
MultiTargetRequest ()
virtual ~MultiTargetRequest ()
MultiTargetRequest (const MultiTargetRequest &from)
MultiTargetRequest & operator= (const MultiTargetRequest &from)
void Swap (MultiTargetRequest *other)
MultiTargetRequest * New () const final
MultiTargetRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const MultiTargetRequest &from)
void MergeFrom (const MultiTargetRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const MultiTargetRequest & default_instance ()
static void InitAsDefaultInstance ()
static const MultiTargetRequest * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const MultiTargetRequest & default_instance ()
static void InitAsDefaultInstance ()
static const MultiTargetRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (MultiTargetRequest &a, MultiTargetRequest &b)
void swap (MultiTargetRequest &a, MultiTargetRequest &b)
Detailed Description
Definition at line 1623 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
MultiTargetRequest() [1/4]
iCubInterfaceMessages::MultiTargetRequest::MultiTargetRequest ()
Definition at line 4268 of file icub.pb.cc.
~MultiTargetRequest() [1/2]
iCubInterfaceMessages::MultiTargetRequest::~MultiTargetRequest () virtual
Definition at line 4285 of file icub.pb.cc.
MultiTargetRequest() [2/4]
iCubInterfaceMessages::MultiTargetRequest::MultiTargetRequest (const MultiTargetRequest & from)
Definition at line 4275 of file icub.pb.cc.
MultiTargetRequest() [3/4]
iCubInterfaceMessages::MultiTargetRequest::MultiTargetRequest ()
~MultiTargetRequest() [2/2]
virtual iCubInterfaceMessages::MultiTargetRequest::~MultiTargetRequest () virtual
MultiTargetRequest() [4/4]
iCubInterfaceMessages::MultiTargetRequest::MultiTargetRequest (const MultiTargetRequest & from)
Member Function Documentation
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::MultiTargetRequest::ByteSizeLong () const final
Definition at line 4369 of file icub.pb.cc.
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::MultiTargetRequest::ByteSizeLong () const final
Clear() [1/2]
void iCubInterfaceMessages::MultiTargetRequest::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::MultiTargetRequest::Clear () final
Definition at line 4307 of file icub.pb.cc.
Referenced by CopyFrom().
CopyFrom() [1/4]
void iCubInterfaceMessages::MultiTargetRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 4407 of file icub.pb.cc.
CopyFrom() [2/4]
void iCubInterfaceMessages::MultiTargetRequest::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [3/4]
void iCubInterfaceMessages::MultiTargetRequest::CopyFrom (const MultiTargetRequest & from)
Definition at line 4414 of file icub.pb.cc.
CopyFrom() [4/4]
void iCubInterfaceMessages::MultiTargetRequest::CopyFrom (const MultiTargetRequest & from)
default_instance() [1/2]
const MultiTargetRequest & iCubInterfaceMessages::MultiTargetRequest::default_instance () static
Definition at line 4301 of file icub.pb.cc.
default_instance() [2/2]
static const MultiTargetRequest& iCubInterfaceMessages::MultiTargetRequest::default_instance () static
descriptor() [1/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::MultiTargetRequest::descriptor () static
descriptor() [2/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::MultiTargetRequest::descriptor () static
Definition at line 4296 of file icub.pb.cc.
GetCachedSize() [1/2]
int iCubInterfaceMessages::MultiTargetRequest::GetCachedSize () const inline final
Definition at line 1688 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::MultiTargetRequest::GetCachedSize () const inline final
Definition at line 1688 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
google::protobuf::Metadata iCubInterfaceMessages::MultiTargetRequest::GetMetadata () const final
Definition at line 4434 of file icub.pb.cc.
GetMetadata() [2/2]
::google::protobuf::Metadata iCubInterfaceMessages::MultiTargetRequest::GetMetadata () const final
InitAsDefaultInstance() [1/2]
void iCubInterfaceMessages::MultiTargetRequest::InitAsDefaultInstance () static
Definition at line 4263 of file icub.pb.cc.
InitAsDefaultInstance() [2/2]
static void iCubInterfaceMessages::MultiTargetRequest::InitAsDefaultInstance () static
internal_default_instance() [1/2]
static const MultiTargetRequest* iCubInterfaceMessages::MultiTargetRequest::internal_default_instance () inline static
Definition at line 1653 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
internal_default_instance() [2/2]
static const MultiTargetRequest* iCubInterfaceMessages::MultiTargetRequest::internal_default_instance () inline static
Definition at line 1653 of file iCub_ANN_Interface/grpc/icub.pb.h.
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::MultiTargetRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 4354 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::MultiTargetRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::MultiTargetRequest::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::MultiTargetRequest::IsInitialized () const final
Definition at line 4421 of file icub.pb.cc.
MergeFrom() [1/4]
void iCubInterfaceMessages::MultiTargetRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 4383 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/4]
void iCubInterfaceMessages::MultiTargetRequest::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [3/4]
void iCubInterfaceMessages::MultiTargetRequest::MergeFrom (const MultiTargetRequest & from)
MergeFrom() [4/4]
void iCubInterfaceMessages::MultiTargetRequest::MergeFrom (const MultiTargetRequest & from)
Definition at line 4398 of file icub.pb.cc.
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::MultiTargetRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::MultiTargetRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 4316 of file icub.pb.cc.
New() [1/4]
MultiTargetRequest* iCubInterfaceMessages::MultiTargetRequest::New () const inline final
Definition at line 1667 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
MultiTargetRequest* iCubInterfaceMessages::MultiTargetRequest::New () const inline final
Definition at line 1667 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
MultiTargetRequest* iCubInterfaceMessages::MultiTargetRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1671 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
MultiTargetRequest* iCubInterfaceMessages::MultiTargetRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1671 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
MultiTargetRequest& iCubInterfaceMessages::MultiTargetRequest::operator= (const MultiTargetRequest & from) inline
Definition at line 1630 of file iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
MultiTargetRequest& iCubInterfaceMessages::MultiTargetRequest::operator= (const MultiTargetRequest & from) inline
Definition at line 1630 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::MultiTargetRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 4341 of file icub.pb.cc.
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::MultiTargetRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Swap() [1/2]
void iCubInterfaceMessages::MultiTargetRequest::Swap (MultiTargetRequest * other)
Definition at line 4425 of file icub.pb.cc.
Swap() [2/2]
void iCubInterfaceMessages::MultiTargetRequest::Swap (MultiTargetRequest * other)
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 1715 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (MultiTargetRequest & a, MultiTargetRequest & b) friend
Definition at line 1661 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (MultiTargetRequest & a, MultiTargetRequest & b) friend
Definition at line 1661 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::MultiTargetRequest::kIndexInFileMessages static constexpr
Initial value:
=
    13
Definition at line 1657 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc