ANNarchy iCub Interface: iCubInterfaceMessages::ImageResponse Class Reference
iCubInterfaceMessages::ImageResponse Class Reference
#include <icub.pb.h>
Public Member Functions
ImageResponse ()
virtual ~ImageResponse ()
ImageResponse (const ImageResponse &from)
ImageResponse & operator= (const ImageResponse &from)
void Swap (ImageResponse *other)
ImageResponse * New () const final
ImageResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const ImageResponse &from)
void MergeFrom (const ImageResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int imagel_size () const
void clear_imagel ()
double imagel (int index) const
void set_imagel (int index, double value)
void add_imagel (double value)
const ::google::protobuf::RepeatedField< double > & imagel () const
::google::protobuf::RepeatedField< double > * mutable_imagel ()
int imager_size () const
void clear_imager ()
double imager (int index) const
void set_imager (int index, double value)
void add_imager (double value)
const ::google::protobuf::RepeatedField< double > & imager () const
::google::protobuf::RepeatedField< double > * mutable_imager ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const ImageResponse & default_instance ()
static void InitAsDefaultInstance ()
static const ImageResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kImageLFieldNumber = 2
static const int kImageRFieldNumber = 3
static const int kStatusFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (ImageResponse &a, ImageResponse &b)
Detailed Description
Definition at line 598 of file icub.pb.h.
Constructor & Destructor Documentation
ImageResponse() [1/2]
iCubInterfaceMessages::ImageResponse::ImageResponse ()
Definition at line 1804 of file icub.pb.cc.
~ImageResponse()
iCubInterfaceMessages::ImageResponse::~ImageResponse () virtual
Definition at line 1825 of file icub.pb.cc.
ImageResponse() [2/2]
iCubInterfaceMessages::ImageResponse::ImageResponse (const ImageResponse & from)
Definition at line 1811 of file icub.pb.cc.
Member Function Documentation
add_imagel()
void iCubInterfaceMessages::ImageResponse::add_imagel (double value) inline
Definition at line 3309 of file icub.pb.h.
add_imager()
void iCubInterfaceMessages::ImageResponse::add_imager (double value) inline
Definition at line 3339 of file icub.pb.h.
ByteSizeLong()
size_t iCubInterfaceMessages::ImageResponse::ByteSizeLong () const final
Definition at line 2026 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::ImageResponse::Clear () final
Definition at line 1847 of file icub.pb.cc.
Referenced by CopyFrom().
clear_imagel()
void iCubInterfaceMessages::ImageResponse::clear_imagel () inline
Definition at line 3298 of file icub.pb.h.
clear_imager()
void iCubInterfaceMessages::ImageResponse::clear_imager () inline
Definition at line 3328 of file icub.pb.h.
clear_status()
void iCubInterfaceMessages::ImageResponse::clear_status () inline
Definition at line 3281 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::ImageResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 2107 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::ImageResponse::CopyFrom (const ImageResponse & from)
Definition at line 2114 of file icub.pb.cc.
default_instance()
const ImageResponse & iCubInterfaceMessages::ImageResponse::default_instance () static
Definition at line 1841 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::ImageResponse::descriptor () static
Definition at line 1836 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::ImageResponse::GetCachedSize () const inline final
Definition at line 663 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::ImageResponse::GetMetadata () const final
Definition at line 2137 of file icub.pb.cc.
imagel() [1/2]
const ::google::protobuf::RepeatedField< double > & iCubInterfaceMessages::ImageResponse::imagel () const inline
Definition at line 3314 of file icub.pb.h.
Referenced by SerializeWithCachedSizes().
imagel() [2/2]
double iCubInterfaceMessages::ImageResponse::imagel (int index) const inline
Definition at line 3301 of file icub.pb.h.
Referenced by ClientInstance::retrieve_image().
imagel_size()
int iCubInterfaceMessages::ImageResponse::imagel_size () const inline
Definition at line 3295 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
imager() [1/2]
const ::google::protobuf::RepeatedField< double > & iCubInterfaceMessages::ImageResponse::imager () const inline
Definition at line 3344 of file icub.pb.h.
Referenced by SerializeWithCachedSizes().
imager() [2/2]
double iCubInterfaceMessages::ImageResponse::imager (int index) const inline
Definition at line 3331 of file icub.pb.h.
imager_size()
int iCubInterfaceMessages::ImageResponse::imager_size () const inline
Definition at line 3325 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
InitAsDefaultInstance()
void iCubInterfaceMessages::ImageResponse::InitAsDefaultInstance () static
Definition at line 1796 of file icub.pb.cc.
internal_default_instance()
static const ImageResponse* iCubInterfaceMessages::ImageResponse::internal_default_instance () inline static
Definition at line 628 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::ImageResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 1979 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::ImageResponse::IsInitialized () const final
Definition at line 2121 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::ImageResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 2078 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::ImageResponse::MergeFrom (const ImageResponse & from)
Definition at line 2093 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::ImageResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 1859 of file icub.pb.cc.
mutable_imagel()
google::protobuf::RepeatedField< double > * iCubInterfaceMessages::ImageResponse::mutable_imagel () inline
Definition at line 3319 of file icub.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_imager()
google::protobuf::RepeatedField< double > * iCubInterfaceMessages::ImageResponse::mutable_imager () inline
Definition at line 3349 of file icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/2]
ImageResponse* iCubInterfaceMessages::ImageResponse::New () const inline final
Definition at line 642 of file icub.pb.h.
New() [2/2]
ImageResponse* iCubInterfaceMessages::ImageResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 646 of file icub.pb.h.
operator=()
ImageResponse& iCubInterfaceMessages::ImageResponse::operator= (const ImageResponse & from) inline
Definition at line 605 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::ImageResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 1942 of file icub.pb.cc.
set_imagel()
void iCubInterfaceMessages::ImageResponse::set_imagel (int index, double value) inline
Definition at line 3305 of file icub.pb.h.
set_imager()
void iCubInterfaceMessages::ImageResponse::set_imager (int index, double value) inline
Definition at line 3335 of file icub.pb.h.
set_status()
void iCubInterfaceMessages::ImageResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 3288 of file icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status()
iCubInterfaceMessages::Status iCubInterfaceMessages::ImageResponse::status () const inline
Definition at line 3284 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
Swap()
void iCubInterfaceMessages::ImageResponse::Swap (ImageResponse * other)
Definition at line 2125 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 725 of file icub.pb.h.
swap
void swap (ImageResponse & a, ImageResponse & b) friend
Definition at line 636 of file icub.pb.h.
Member Data Documentation
kImageLFieldNumber
const int iCubInterfaceMessages::ImageResponse::kImageLFieldNumber = 2 static
Definition at line 688 of file icub.pb.h.
kImageRFieldNumber
const int iCubInterfaceMessages::ImageResponse::kImageRFieldNumber = 3 static
Definition at line 700 of file icub.pb.h.
kIndexInFileMessages
constexpr int iCubInterfaceMessages::ImageResponse::kIndexInFileMessages static constexpr
Initial value:
=
    4
Definition at line 632 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kStatusFieldNumber
const int iCubInterfaceMessages::ImageResponse::kStatusFieldNumber = 1 static
Definition at line 711 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc