ANNarchy iCub Interface: iCubInterfaceMessages::SingleJointResponse Class Reference
iCubInterfaceMessages::SingleJointResponse Class Reference
#include <icub.pb.h>
Public Member Functions
SingleJointResponse ()
virtual ~SingleJointResponse ()
SingleJointResponse (const SingleJointResponse &from)
SingleJointResponse & operator= (const SingleJointResponse &from)
void Swap (SingleJointResponse *other)
SingleJointResponse * New () const final
SingleJointResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SingleJointResponse &from)
void MergeFrom (const SingleJointResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_angle ()
double angle () const
void set_angle (double value)
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SingleJointResponse & default_instance ()
static void InitAsDefaultInstance ()
static const SingleJointResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kAngleFieldNumber = 2
static const int kStatusFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (SingleJointResponse &a, SingleJointResponse &b)
Detailed Description
Definition at line 635 of file icub.pb.h.
Constructor & Destructor Documentation
SingleJointResponse() [1/2]
iCubInterfaceMessages::SingleJointResponse::SingleJointResponse ()
Definition at line 1896 of file icub.pb.cc.
~SingleJointResponse()
iCubInterfaceMessages::SingleJointResponse::~SingleJointResponse () virtual
Definition at line 1919 of file icub.pb.cc.
SingleJointResponse() [2/2]
iCubInterfaceMessages::SingleJointResponse::SingleJointResponse (const SingleJointResponse & from)
Definition at line 1903 of file icub.pb.cc.
Member Function Documentation
angle()
double iCubInterfaceMessages::SingleJointResponse::angle () const inline
Definition at line 2833 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
ByteSizeLong()
size_t iCubInterfaceMessages::SingleJointResponse::ByteSizeLong () const final
Definition at line 2062 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::SingleJointResponse::Clear () final
Definition at line 1941 of file icub.pb.cc.
Referenced by CopyFrom().
clear_angle()
void iCubInterfaceMessages::SingleJointResponse::clear_angle () inline
Definition at line 2830 of file icub.pb.h.
clear_status()
void iCubInterfaceMessages::SingleJointResponse::clear_status () inline
Definition at line 2816 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::SingleJointResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 2117 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::SingleJointResponse::CopyFrom (const SingleJointResponse & from)
Definition at line 2124 of file icub.pb.cc.
default_instance()
const SingleJointResponse & iCubInterfaceMessages::SingleJointResponse::default_instance () static
Definition at line 1935 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::SingleJointResponse::descriptor () static
Definition at line 1930 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::SingleJointResponse::GetCachedSize () const inline final
Definition at line 700 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::SingleJointResponse::GetMetadata () const final
Definition at line 2146 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::SingleJointResponse::InitAsDefaultInstance () static
Definition at line 1889 of file icub.pb.cc.
internal_default_instance()
static const SingleJointResponse* iCubInterfaceMessages::SingleJointResponse::internal_default_instance () inline static
Definition at line 665 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::SingleJointResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 2036 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::SingleJointResponse::IsInitialized () const final
Definition at line 2131 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::SingleJointResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 2087 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::SingleJointResponse::MergeFrom (const SingleJointResponse & from)
Definition at line 2102 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::SingleJointResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 1953 of file icub.pb.cc.
New() [1/2]
SingleJointResponse* iCubInterfaceMessages::SingleJointResponse::New () const inline final
Definition at line 679 of file icub.pb.h.
New() [2/2]
SingleJointResponse* iCubInterfaceMessages::SingleJointResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 683 of file icub.pb.h.
operator=()
SingleJointResponse& iCubInterfaceMessages::SingleJointResponse::operator= (const SingleJointResponse & from) inline
Definition at line 642 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::SingleJointResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 2012 of file icub.pb.cc.
set_angle()
void iCubInterfaceMessages::SingleJointResponse::set_angle (double value) inline
Definition at line 2837 of file icub.pb.h.
Referenced by MergeFrom().
set_status()
void iCubInterfaceMessages::SingleJointResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 2823 of file icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status()
iCubInterfaceMessages::Status iCubInterfaceMessages::SingleJointResponse::status () const inline
Definition at line 2819 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
Swap()
void iCubInterfaceMessages::SingleJointResponse::Swap (SingleJointResponse * other)
Definition at line 2135 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 741 of file icub.pb.h.
swap
void swap (SingleJointResponse & a, SingleJointResponse & b) friend
Definition at line 673 of file icub.pb.h.
Member Data Documentation
kAngleFieldNumber
const int iCubInterfaceMessages::SingleJointResponse::kAngleFieldNumber = 2 static
Definition at line 724 of file icub.pb.h.
kIndexInFileMessages
constexpr int iCubInterfaceMessages::SingleJointResponse::kIndexInFileMessages static constexpr
Initial value:
=
    4
Definition at line 669 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kStatusFieldNumber
const int iCubInterfaceMessages::SingleJointResponse::kStatusFieldNumber = 1 static
Definition at line 730 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc