ANNarchy iCub Interface: iCubInterfaceMessages::SingleTargetEncodedResponse Class Reference
iCubInterfaceMessages::SingleTargetEncodedResponse Class Reference
#include <icub.pb.h>
Public Member Functions
SingleTargetEncodedResponse ()
virtual ~SingleTargetEncodedResponse ()
SingleTargetEncodedResponse (const SingleTargetEncodedResponse &from)
SingleTargetEncodedResponse & operator= (const SingleTargetEncodedResponse &from)
void Swap (SingleTargetEncodedResponse *other)
SingleTargetEncodedResponse * New () const final
SingleTargetEncodedResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SingleTargetEncodedResponse &from)
void MergeFrom (const SingleTargetEncodedResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
SingleTargetEncodedResponse ()
virtual ~SingleTargetEncodedResponse ()
SingleTargetEncodedResponse (const SingleTargetEncodedResponse &from)
SingleTargetEncodedResponse & operator= (const SingleTargetEncodedResponse &from)
void Swap (SingleTargetEncodedResponse *other)
SingleTargetEncodedResponse * New () const final
SingleTargetEncodedResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SingleTargetEncodedResponse &from)
void MergeFrom (const SingleTargetEncodedResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SingleTargetEncodedResponse & default_instance ()
static void InitAsDefaultInstance ()
static const SingleTargetEncodedResponse * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const SingleTargetEncodedResponse & default_instance ()
static void InitAsDefaultInstance ()
static const SingleTargetEncodedResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kAngleFieldNumber = 2
static const int kStatusFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (SingleTargetEncodedResponse &a, SingleTargetEncodedResponse &b)
void swap (SingleTargetEncodedResponse &a, SingleTargetEncodedResponse &b)
Detailed Description
Definition at line 2152 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
SingleTargetEncodedResponse() [1/4]
iCubInterfaceMessages::SingleTargetEncodedResponse::SingleTargetEncodedResponse ()
Definition at line 5425 of file icub.pb.cc.
~SingleTargetEncodedResponse() [1/2]
iCubInterfaceMessages::SingleTargetEncodedResponse::~SingleTargetEncodedResponse () virtual
Definition at line 5445 of file icub.pb.cc.
SingleTargetEncodedResponse() [2/4]
iCubInterfaceMessages::SingleTargetEncodedResponse::SingleTargetEncodedResponse (const SingleTargetEncodedResponse & from)
Definition at line 5432 of file icub.pb.cc.
SingleTargetEncodedResponse() [3/4]
iCubInterfaceMessages::SingleTargetEncodedResponse::SingleTargetEncodedResponse ()
~SingleTargetEncodedResponse() [2/2]
virtual iCubInterfaceMessages::SingleTargetEncodedResponse::~SingleTargetEncodedResponse () virtual
SingleTargetEncodedResponse() [4/4]
iCubInterfaceMessages::SingleTargetEncodedResponse::SingleTargetEncodedResponse (const SingleTargetEncodedResponse & from)
Member Function Documentation
add_angle() [1/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::add_angle (double value) inline
Definition at line 3801 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
add_angle() [2/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::add_angle (double value)
angle() [1/4]
const ::google::protobuf::RepeatedField< double > & iCubInterfaceMessages::SingleTargetEncodedResponse::angle () const inline
Definition at line 3806 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by SerializeWithCachedSizes().
angle() [2/4]
const ::google::protobuf::RepeatedField< double >& iCubInterfaceMessages::SingleTargetEncodedResponse::angle () const
angle() [3/4]
double iCubInterfaceMessages::SingleTargetEncodedResponse::angle (int index) const inline
Definition at line 3793 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by WriteClientInstance::retrieve_singletarget_enc().
angle() [4/4]
double iCubInterfaceMessages::SingleTargetEncodedResponse::angle (int index) const
angle_size() [1/2]
int iCubInterfaceMessages::SingleTargetEncodedResponse::angle_size () const inline
Definition at line 3787 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
angle_size() [2/2]
int iCubInterfaceMessages::SingleTargetEncodedResponse::angle_size () const
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::SingleTargetEncodedResponse::ByteSizeLong () const final
Definition at line 5604 of file icub.pb.cc.
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::SingleTargetEncodedResponse::ByteSizeLong () const final
Clear() [1/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::Clear () final
Definition at line 5467 of file icub.pb.cc.
Referenced by CopyFrom().
clear_angle() [1/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::clear_angle () inline
Definition at line 3790 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_angle() [2/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::clear_angle ()
clear_status() [1/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::clear_status () inline
Definition at line 3773 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_status() [2/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::clear_status ()
CopyFrom() [1/4]
void iCubInterfaceMessages::SingleTargetEncodedResponse::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/4]
void iCubInterfaceMessages::SingleTargetEncodedResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 5668 of file icub.pb.cc.
CopyFrom() [3/4]
void iCubInterfaceMessages::SingleTargetEncodedResponse::CopyFrom (const SingleTargetEncodedResponse & from)
CopyFrom() [4/4]
void iCubInterfaceMessages::SingleTargetEncodedResponse::CopyFrom (const SingleTargetEncodedResponse & from)
Definition at line 5675 of file icub.pb.cc.
default_instance() [1/2]
static const SingleTargetEncodedResponse& iCubInterfaceMessages::SingleTargetEncodedResponse::default_instance () static
default_instance() [2/2]
const SingleTargetEncodedResponse & iCubInterfaceMessages::SingleTargetEncodedResponse::default_instance () static
Definition at line 5461 of file icub.pb.cc.
descriptor() [1/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::SingleTargetEncodedResponse::descriptor () static
descriptor() [2/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::SingleTargetEncodedResponse::descriptor () static
Definition at line 5456 of file icub.pb.cc.
GetCachedSize() [1/2]
int iCubInterfaceMessages::SingleTargetEncodedResponse::GetCachedSize () const inline final
Definition at line 2217 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::SingleTargetEncodedResponse::GetCachedSize () const inline final
Definition at line 2217 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
google::protobuf::Metadata iCubInterfaceMessages::SingleTargetEncodedResponse::GetMetadata () const final
Definition at line 5697 of file icub.pb.cc.
GetMetadata() [2/2]
::google::protobuf::Metadata iCubInterfaceMessages::SingleTargetEncodedResponse::GetMetadata () const final
InitAsDefaultInstance() [1/2]
static void iCubInterfaceMessages::SingleTargetEncodedResponse::InitAsDefaultInstance () static
InitAsDefaultInstance() [2/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::InitAsDefaultInstance () static
Definition at line 5418 of file icub.pb.cc.
internal_default_instance() [1/2]
static const SingleTargetEncodedResponse* iCubInterfaceMessages::SingleTargetEncodedResponse::internal_default_instance () inline static
Definition at line 2182 of file iCub_ANN_Interface/grpc/icub.pb.h.
internal_default_instance() [2/2]
static const SingleTargetEncodedResponse* iCubInterfaceMessages::SingleTargetEncodedResponse::internal_default_instance () inline static
Definition at line 2182 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::SingleTargetEncodedResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 5570 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::SingleTargetEncodedResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::SingleTargetEncodedResponse::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::SingleTargetEncodedResponse::IsInitialized () const final
Definition at line 5682 of file icub.pb.cc.
MergeFrom() [1/4]
void iCubInterfaceMessages::SingleTargetEncodedResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 5640 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/4]
void iCubInterfaceMessages::SingleTargetEncodedResponse::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [3/4]
void iCubInterfaceMessages::SingleTargetEncodedResponse::MergeFrom (const SingleTargetEncodedResponse & from)
MergeFrom() [4/4]
void iCubInterfaceMessages::SingleTargetEncodedResponse::MergeFrom (const SingleTargetEncodedResponse & from)
Definition at line 5655 of file icub.pb.cc.
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::SingleTargetEncodedResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 5478 of file icub.pb.cc.
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::SingleTargetEncodedResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_angle() [1/2]
::google::protobuf::RepeatedField< double >* iCubInterfaceMessages::SingleTargetEncodedResponse::mutable_angle ()
mutable_angle() [2/2]
google::protobuf::RepeatedField< double > * iCubInterfaceMessages::SingleTargetEncodedResponse::mutable_angle () inline
Definition at line 3811 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/4]
SingleTargetEncodedResponse* iCubInterfaceMessages::SingleTargetEncodedResponse::New () const inline final
Definition at line 2196 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
SingleTargetEncodedResponse* iCubInterfaceMessages::SingleTargetEncodedResponse::New () const inline final
Definition at line 2196 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
SingleTargetEncodedResponse* iCubInterfaceMessages::SingleTargetEncodedResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 2200 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
SingleTargetEncodedResponse* iCubInterfaceMessages::SingleTargetEncodedResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 2200 of file iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
SingleTargetEncodedResponse& iCubInterfaceMessages::SingleTargetEncodedResponse::operator= (const SingleTargetEncodedResponse & from) inline
Definition at line 2159 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
SingleTargetEncodedResponse& iCubInterfaceMessages::SingleTargetEncodedResponse::operator= (const SingleTargetEncodedResponse & from) inline
Definition at line 2159 of file iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 5542 of file icub.pb.cc.
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_angle() [1/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::set_angle (int index, double value)
set_angle() [2/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::set_angle (int index, double value) inline
Definition at line 3797 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
set_status() [1/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::set_status (::iCubInterfaceMessages::Status value)
set_status() [2/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 3780 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status() [1/2]
iCubInterfaceMessages::Status iCubInterfaceMessages::SingleTargetEncodedResponse::status () const inline
Definition at line 3776 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
status() [2/2]
::iCubInterfaceMessages::Status iCubInterfaceMessages::SingleTargetEncodedResponse::status () const
Swap() [1/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::Swap (SingleTargetEncodedResponse * other)
Definition at line 5686 of file icub.pb.cc.
Swap() [2/2]
void iCubInterfaceMessages::SingleTargetEncodedResponse::Swap (SingleTargetEncodedResponse * other)
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 2265 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (SingleTargetEncodedResponse & a, SingleTargetEncodedResponse & b) friend
Definition at line 2190 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (SingleTargetEncodedResponse & a, SingleTargetEncodedResponse & b) friend
Definition at line 2190 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kAngleFieldNumber
static const int iCubInterfaceMessages::SingleTargetEncodedResponse::kAngleFieldNumber = 2 static
Definition at line 2242 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::SingleTargetEncodedResponse::kIndexInFileMessages static constexpr
Initial value:
=
    18
Definition at line 2186 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kStatusFieldNumber
static const int iCubInterfaceMessages::SingleTargetEncodedResponse::kStatusFieldNumber = 1 static
Definition at line 2253 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc