ANNarchy iCub Interface: iCubInterfaceMessages::MultiJointRequest Class Reference
iCubInterfaceMessages::MultiJointRequest Class Reference
#include <icub.pb.h>
Public Member Functions
MultiJointRequest ()
virtual ~MultiJointRequest ()
MultiJointRequest (const MultiJointRequest &from)
MultiJointRequest & operator= (const MultiJointRequest &from)
void Swap (MultiJointRequest *other)
MultiJointRequest * New () const final
MultiJointRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const MultiJointRequest &from)
void MergeFrom (const MultiJointRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int joint_size () const
void clear_joint ()
::google::protobuf::int32 joint (int index) const
void set_joint (int index, ::google::protobuf::int32 value)
void add_joint (::google::protobuf::int32 value)
const ::google::protobuf::RepeatedField< ::google::protobuf::int32 > & joint () const
::google::protobuf::RepeatedField< ::google::protobuf::int32 > * mutable_joint ()
void clear_encode ()
bool encode () const
void set_encode (bool value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const MultiJointRequest & default_instance ()
static void InitAsDefaultInstance ()
static const MultiJointRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kJointFieldNumber = 1
static const int kEncodeFieldNumber = 2
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (MultiJointRequest &a, MultiJointRequest &b)
Detailed Description
Definition at line 956 of file icub.pb.h.
Constructor & Destructor Documentation
MultiJointRequest() [1/2]
iCubInterfaceMessages::MultiJointRequest::MultiJointRequest ()
Definition at line 2702 of file icub.pb.cc.
~MultiJointRequest()
iCubInterfaceMessages::MultiJointRequest::~MultiJointRequest () virtual
Definition at line 2722 of file icub.pb.cc.
MultiJointRequest() [2/2]
iCubInterfaceMessages::MultiJointRequest::MultiJointRequest (const MultiJointRequest & from)
Definition at line 2709 of file icub.pb.cc.
Member Function Documentation
add_joint()
void iCubInterfaceMessages::MultiJointRequest::add_joint (::google::protobuf::int32 value) inline
Definition at line 3453 of file icub.pb.h.
ByteSizeLong()
size_t iCubInterfaceMessages::MultiJointRequest::ByteSizeLong () const final
Definition at line 2880 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::MultiJointRequest::Clear () final
Definition at line 2744 of file icub.pb.cc.
Referenced by CopyFrom().
clear_encode()
void iCubInterfaceMessages::MultiJointRequest::clear_encode () inline
Definition at line 3469 of file icub.pb.h.
clear_joint()
void iCubInterfaceMessages::MultiJointRequest::clear_joint () inline
Definition at line 3442 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::MultiJointRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 2943 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::MultiJointRequest::CopyFrom (const MultiJointRequest & from)
Definition at line 2950 of file icub.pb.cc.
default_instance()
const MultiJointRequest & iCubInterfaceMessages::MultiJointRequest::default_instance () static
Definition at line 2738 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::MultiJointRequest::descriptor () static
Definition at line 2733 of file icub.pb.cc.
encode()
bool iCubInterfaceMessages::MultiJointRequest::encode () const inline
Definition at line 3472 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
GetCachedSize()
int iCubInterfaceMessages::MultiJointRequest::GetCachedSize () const inline final
Definition at line 1021 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::MultiJointRequest::GetMetadata () const final
Definition at line 2972 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::MultiJointRequest::InitAsDefaultInstance () static
Definition at line 2695 of file icub.pb.cc.
internal_default_instance()
static const MultiJointRequest* iCubInterfaceMessages::MultiJointRequest::internal_default_instance () inline static
Definition at line 986 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::MultiJointRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 2847 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::MultiJointRequest::IsInitialized () const final
Definition at line 2957 of file icub.pb.cc.
joint() [1/2]
const ::google::protobuf::RepeatedField<::google::protobuf::int32 > & iCubInterfaceMessages::MultiJointRequest::joint () const inline
Definition at line 3458 of file icub.pb.h.
Referenced by SerializeWithCachedSizes().
joint() [2/2]
google::protobuf::int32 iCubInterfaceMessages::MultiJointRequest::joint (int index) const inline
Definition at line 3445 of file icub.pb.h.
joint_size()
int iCubInterfaceMessages::MultiJointRequest::joint_size () const inline
Definition at line 3439 of file icub.pb.h.
Referenced by InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
MergeFrom() [1/2]
void iCubInterfaceMessages::MultiJointRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 2915 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::MultiJointRequest::MergeFrom (const MultiJointRequest & from)
Definition at line 2930 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::MultiJointRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 2755 of file icub.pb.cc.
mutable_joint()
google::protobuf::RepeatedField<::google::protobuf::int32 > * iCubInterfaceMessages::MultiJointRequest::mutable_joint () inline
Definition at line 3463 of file icub.pb.h.
Referenced by MergePartialFromCodedStream(), and ClientInstance::retrieve_multijoints().
New() [1/2]
MultiJointRequest* iCubInterfaceMessages::MultiJointRequest::New () const inline final
Definition at line 1000 of file icub.pb.h.
New() [2/2]
MultiJointRequest* iCubInterfaceMessages::MultiJointRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1004 of file icub.pb.h.
operator=()
MultiJointRequest& iCubInterfaceMessages::MultiJointRequest::operator= (const MultiJointRequest & from) inline
Definition at line 963 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::MultiJointRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 2818 of file icub.pb.cc.
set_encode()
void iCubInterfaceMessages::MultiJointRequest::set_encode (bool value) inline
Definition at line 3476 of file icub.pb.h.
Referenced by MergeFrom(), and ClientInstance::retrieve_multijoints().
set_joint()
void iCubInterfaceMessages::MultiJointRequest::set_joint (int index, ::google::protobuf::int32 value) inline
Definition at line 3449 of file icub.pb.h.
Swap()
void iCubInterfaceMessages::MultiJointRequest::Swap (MultiJointRequest * other)
Definition at line 2961 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 1069 of file icub.pb.h.
swap
void swap (MultiJointRequest & a, MultiJointRequest & b) friend
Definition at line 994 of file icub.pb.h.
Member Data Documentation
kEncodeFieldNumber
const int iCubInterfaceMessages::MultiJointRequest::kEncodeFieldNumber = 2 static
Definition at line 1057 of file icub.pb.h.
kIndexInFileMessages
constexpr int iCubInterfaceMessages::MultiJointRequest::kIndexInFileMessages static constexpr
Initial value:
=
    7
Definition at line 990 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kJointFieldNumber
const int iCubInterfaceMessages::MultiJointRequest::kJointFieldNumber = 1 static
Definition at line 1046 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc