ANNarchy iCub Interface: iCubInterfaceMessages::AllJointRequest Class Reference
iCubInterfaceMessages::AllJointRequest Class Reference
#include <icub.pb.h>
Public Member Functions
AllJointRequest ()
virtual ~AllJointRequest ()
AllJointRequest (const AllJointRequest &from)
AllJointRequest & operator= (const AllJointRequest &from)
void Swap (AllJointRequest *other)
AllJointRequest * New () const final
AllJointRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const AllJointRequest &from)
void MergeFrom (const AllJointRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_part ()
const ::std::string & part () const
void set_part (const ::std::string &value)
void set_part (const char *value)
void set_part (const char *value, size_t size)
::std::string * mutable_part ()
::std::string * release_part ()
void set_allocated_part (::std::string *part)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const AllJointRequest & default_instance ()
static void InitAsDefaultInstance ()
static const AllJointRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kPartFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (AllJointRequest &a, AllJointRequest &b)
Detailed Description
Definition at line 745 of file icub.pb.h.
Constructor & Destructor Documentation
AllJointRequest() [1/2]
iCubInterfaceMessages::AllJointRequest::AllJointRequest ()
Definition at line 2160 of file icub.pb.cc.
~AllJointRequest()
iCubInterfaceMessages::AllJointRequest::~AllJointRequest () virtual
Definition at line 2182 of file icub.pb.cc.
AllJointRequest() [2/2]
iCubInterfaceMessages::AllJointRequest::AllJointRequest (const AllJointRequest & from)
Definition at line 2167 of file icub.pb.cc.
Member Function Documentation
ByteSizeLong()
size_t iCubInterfaceMessages::AllJointRequest::ByteSizeLong () const final
Definition at line 2310 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::AllJointRequest::Clear () final
Definition at line 2205 of file icub.pb.cc.
Referenced by CopyFrom().
clear_part()
void iCubInterfaceMessages::AllJointRequest::clear_part () inline
Definition at line 2848 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::AllJointRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 2359 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::AllJointRequest::CopyFrom (const AllJointRequest & from)
Definition at line 2366 of file icub.pb.cc.
default_instance()
const AllJointRequest & iCubInterfaceMessages::AllJointRequest::default_instance () static
Definition at line 2199 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::AllJointRequest::descriptor () static
Definition at line 2194 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::AllJointRequest::GetCachedSize () const inline final
Definition at line 810 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::AllJointRequest::GetMetadata () const final
Definition at line 2388 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::AllJointRequest::InitAsDefaultInstance () static
Definition at line 2154 of file icub.pb.cc.
internal_default_instance()
static const AllJointRequest* iCubInterfaceMessages::AllJointRequest::internal_default_instance () inline static
Definition at line 775 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::AllJointRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 2284 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::AllJointRequest::IsInitialized () const final
Definition at line 2373 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::AllJointRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 2331 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::AllJointRequest::MergeFrom (const AllJointRequest & from)
Definition at line 2346 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::AllJointRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 2215 of file icub.pb.cc.
mutable_part()
std::string * iCubInterfaceMessages::AllJointRequest::mutable_part () inline
Definition at line 2880 of file icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/2]
AllJointRequest* iCubInterfaceMessages::AllJointRequest::New () const inline final
Definition at line 789 of file icub.pb.h.
New() [2/2]
AllJointRequest* iCubInterfaceMessages::AllJointRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 793 of file icub.pb.h.
operator=()
AllJointRequest& iCubInterfaceMessages::AllJointRequest::operator= (const AllJointRequest & from) inline
Definition at line 752 of file icub.pb.h.
part()
const ::std::string & iCubInterfaceMessages::AllJointRequest::part () const inline
Definition at line 2851 of file icub.pb.h.
Referenced by AllJointRequest(), ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), and SerializeWithCachedSizes().
release_part()
std::string * iCubInterfaceMessages::AllJointRequest::release_part () inline
Definition at line 2885 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::AllJointRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 2261 of file icub.pb.cc.
set_allocated_part()
void iCubInterfaceMessages::AllJointRequest::set_allocated_part (::std::string * part) inline
Definition at line 2890 of file icub.pb.h.
set_part() [1/3]
void iCubInterfaceMessages::AllJointRequest::set_part (const ::std::string & value) inline
Definition at line 2855 of file icub.pb.h.
set_part() [2/3]
void iCubInterfaceMessages::AllJointRequest::set_part (const char * value) inline
Definition at line 2868 of file icub.pb.h.
set_part() [3/3]
void iCubInterfaceMessages::AllJointRequest::set_part (const char * value, size_t size) inline
Definition at line 2874 of file icub.pb.h.
Swap()
void iCubInterfaceMessages::AllJointRequest::Swap (AllJointRequest * other)
Definition at line 2377 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 852 of file icub.pb.h.
swap
void swap (AllJointRequest & a, AllJointRequest & b) friend
Definition at line 783 of file icub.pb.h.
Member Data Documentation
kIndexInFileMessages
constexpr int iCubInterfaceMessages::AllJointRequest::kIndexInFileMessages static constexpr
Initial value:
=
    5
Definition at line 779 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kPartFieldNumber
const int iCubInterfaceMessages::AllJointRequest::kPartFieldNumber = 1 static
Definition at line 834 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc