ANNarchy iCub Interface: iCubInterfaceMessages::SkinForearmRequest Class Reference
iCubInterfaceMessages::SkinForearmRequest Class Reference
#include <icub.pb.h>
Public Member Functions
SkinForearmRequest ()
virtual ~SkinForearmRequest ()
SkinForearmRequest (const SkinForearmRequest &from)
SkinForearmRequest & operator= (const SkinForearmRequest &from)
void Swap (SkinForearmRequest *other)
SkinForearmRequest * New () const final
SkinForearmRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SkinForearmRequest &from)
void MergeFrom (const SkinForearmRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
SkinForearmRequest ()
virtual ~SkinForearmRequest ()
SkinForearmRequest (const SkinForearmRequest &from)
SkinForearmRequest & operator= (const SkinForearmRequest &from)
void Swap (SkinForearmRequest *other)
SkinForearmRequest * New () const final
SkinForearmRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SkinForearmRequest &from)
void MergeFrom (const SkinForearmRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SkinForearmRequest & default_instance ()
static void InitAsDefaultInstance ()
static const SkinForearmRequest * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const SkinForearmRequest & default_instance ()
static void InitAsDefaultInstance ()
static const SkinForearmRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (SkinForearmRequest &a, SkinForearmRequest &b)
void swap (SkinForearmRequest &a, SkinForearmRequest &b)
Detailed Description
Definition at line 3019 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
SkinForearmRequest() [1/4]
iCubInterfaceMessages::SkinForearmRequest::SkinForearmRequest ()
Definition at line 7350 of file icub.pb.cc.
~SkinForearmRequest() [1/2]
iCubInterfaceMessages::SkinForearmRequest::~SkinForearmRequest () virtual
Definition at line 7367 of file icub.pb.cc.
SkinForearmRequest() [2/4]
iCubInterfaceMessages::SkinForearmRequest::SkinForearmRequest (const SkinForearmRequest & from)
Definition at line 7357 of file icub.pb.cc.
SkinForearmRequest() [3/4]
iCubInterfaceMessages::SkinForearmRequest::SkinForearmRequest ()
~SkinForearmRequest() [2/2]
virtual iCubInterfaceMessages::SkinForearmRequest::~SkinForearmRequest () virtual
SkinForearmRequest() [4/4]
iCubInterfaceMessages::SkinForearmRequest::SkinForearmRequest (const SkinForearmRequest & from)
Member Function Documentation
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::SkinForearmRequest::ByteSizeLong () const final
Definition at line 7451 of file icub.pb.cc.
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::SkinForearmRequest::ByteSizeLong () const final
Clear() [1/2]
void iCubInterfaceMessages::SkinForearmRequest::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::SkinForearmRequest::Clear () final
Definition at line 7389 of file icub.pb.cc.
Referenced by CopyFrom().
CopyFrom() [1/4]
void iCubInterfaceMessages::SkinForearmRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 7489 of file icub.pb.cc.
CopyFrom() [2/4]
void iCubInterfaceMessages::SkinForearmRequest::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [3/4]
void iCubInterfaceMessages::SkinForearmRequest::CopyFrom (const SkinForearmRequest & from)
Definition at line 7496 of file icub.pb.cc.
CopyFrom() [4/4]
void iCubInterfaceMessages::SkinForearmRequest::CopyFrom (const SkinForearmRequest & from)
default_instance() [1/2]
const SkinForearmRequest & iCubInterfaceMessages::SkinForearmRequest::default_instance () static
Definition at line 7383 of file icub.pb.cc.
default_instance() [2/2]
static const SkinForearmRequest& iCubInterfaceMessages::SkinForearmRequest::default_instance () static
descriptor() [1/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::SkinForearmRequest::descriptor () static
descriptor() [2/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::SkinForearmRequest::descriptor () static
Definition at line 7378 of file icub.pb.cc.
GetCachedSize() [1/2]
int iCubInterfaceMessages::SkinForearmRequest::GetCachedSize () const inline final
Definition at line 3084 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::SkinForearmRequest::GetCachedSize () const inline final
Definition at line 3084 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
google::protobuf::Metadata iCubInterfaceMessages::SkinForearmRequest::GetMetadata () const final
Definition at line 7516 of file icub.pb.cc.
GetMetadata() [2/2]
::google::protobuf::Metadata iCubInterfaceMessages::SkinForearmRequest::GetMetadata () const final
InitAsDefaultInstance() [1/2]
void iCubInterfaceMessages::SkinForearmRequest::InitAsDefaultInstance () static
Definition at line 7345 of file icub.pb.cc.
InitAsDefaultInstance() [2/2]
static void iCubInterfaceMessages::SkinForearmRequest::InitAsDefaultInstance () static
internal_default_instance() [1/2]
static const SkinForearmRequest* iCubInterfaceMessages::SkinForearmRequest::internal_default_instance () inline static
Definition at line 3049 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
internal_default_instance() [2/2]
static const SkinForearmRequest* iCubInterfaceMessages::SkinForearmRequest::internal_default_instance () inline static
Definition at line 3049 of file iCub_ANN_Interface/grpc/icub.pb.h.
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::SkinForearmRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 7436 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::SkinForearmRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::SkinForearmRequest::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::SkinForearmRequest::IsInitialized () const final
Definition at line 7503 of file icub.pb.cc.
MergeFrom() [1/4]
void iCubInterfaceMessages::SkinForearmRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 7465 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/4]
void iCubInterfaceMessages::SkinForearmRequest::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [3/4]
void iCubInterfaceMessages::SkinForearmRequest::MergeFrom (const SkinForearmRequest & from)
MergeFrom() [4/4]
void iCubInterfaceMessages::SkinForearmRequest::MergeFrom (const SkinForearmRequest & from)
Definition at line 7480 of file icub.pb.cc.
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::SkinForearmRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::SkinForearmRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 7398 of file icub.pb.cc.
New() [1/4]
SkinForearmRequest* iCubInterfaceMessages::SkinForearmRequest::New () const inline final
Definition at line 3063 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
SkinForearmRequest* iCubInterfaceMessages::SkinForearmRequest::New () const inline final
Definition at line 3063 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
SkinForearmRequest* iCubInterfaceMessages::SkinForearmRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 3067 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
SkinForearmRequest* iCubInterfaceMessages::SkinForearmRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 3067 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
SkinForearmRequest& iCubInterfaceMessages::SkinForearmRequest::operator= (const SkinForearmRequest & from) inline
Definition at line 3026 of file iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
SkinForearmRequest& iCubInterfaceMessages::SkinForearmRequest::operator= (const SkinForearmRequest & from) inline
Definition at line 3026 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::SkinForearmRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 7423 of file icub.pb.cc.
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::SkinForearmRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Swap() [1/2]
void iCubInterfaceMessages::SkinForearmRequest::Swap (SkinForearmRequest * other)
Definition at line 7507 of file icub.pb.cc.
Swap() [2/2]
void iCubInterfaceMessages::SkinForearmRequest::Swap (SkinForearmRequest * other)
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 3111 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (SkinForearmRequest & a, SkinForearmRequest & b) friend
Definition at line 3057 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (SkinForearmRequest & a, SkinForearmRequest & b) friend
Definition at line 3057 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::SkinForearmRequest::kIndexInFileMessages static constexpr
Initial value:
=
    26
Definition at line 3053 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc