ANNarchy iCub Interface: iCubInterfaceMessages::AllJointsRequest Class Reference
iCubInterfaceMessages::AllJointsRequest Class Reference
#include <icub.pb.h>
Public Member Functions
AllJointsRequest ()
virtual ~AllJointsRequest ()
AllJointsRequest (const AllJointsRequest &from)
AllJointsRequest & operator= (const AllJointsRequest &from)
void Swap (AllJointsRequest *other)
AllJointsRequest * New () const final
AllJointsRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const AllJointsRequest &from)
void MergeFrom (const AllJointsRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_encode ()
bool encode () const
void set_encode (bool value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const AllJointsRequest & default_instance ()
static void InitAsDefaultInstance ()
static const AllJointsRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kEncodeFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (AllJointsRequest &a, AllJointsRequest &b)
Detailed Description
Definition at line 1190 of file icub.pb.h.
Constructor & Destructor Documentation
AllJointsRequest() [1/2]
iCubInterfaceMessages::AllJointsRequest::AllJointsRequest ()
Definition at line 3273 of file icub.pb.cc.
~AllJointsRequest()
iCubInterfaceMessages::AllJointsRequest::~AllJointsRequest () virtual
Definition at line 3292 of file icub.pb.cc.
AllJointsRequest() [2/2]
iCubInterfaceMessages::AllJointsRequest::AllJointsRequest (const AllJointsRequest & from)
Definition at line 3280 of file icub.pb.cc.
Member Function Documentation
ByteSizeLong()
size_t iCubInterfaceMessages::AllJointsRequest::ByteSizeLong () const final
Definition at line 3406 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::AllJointsRequest::Clear () final
Definition at line 3314 of file icub.pb.cc.
Referenced by CopyFrom().
clear_encode()
void iCubInterfaceMessages::AllJointsRequest::clear_encode () inline
Definition at line 3535 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::AllJointsRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 3452 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::AllJointsRequest::CopyFrom (const AllJointsRequest & from)
Definition at line 3459 of file icub.pb.cc.
default_instance()
const AllJointsRequest & iCubInterfaceMessages::AllJointsRequest::default_instance () static
Definition at line 3308 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::AllJointsRequest::descriptor () static
Definition at line 3303 of file icub.pb.cc.
encode()
bool iCubInterfaceMessages::AllJointsRequest::encode () const inline
Definition at line 3538 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
GetCachedSize()
int iCubInterfaceMessages::AllJointsRequest::GetCachedSize () const inline final
Definition at line 1255 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::AllJointsRequest::GetMetadata () const final
Definition at line 3480 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::AllJointsRequest::InitAsDefaultInstance () static
Definition at line 3267 of file icub.pb.cc.
internal_default_instance()
static const AllJointsRequest* iCubInterfaceMessages::AllJointsRequest::internal_default_instance () inline static
Definition at line 1220 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::AllJointsRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 3386 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::AllJointsRequest::IsInitialized () const final
Definition at line 3466 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::AllJointsRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 3425 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::AllJointsRequest::MergeFrom (const AllJointsRequest & from)
Definition at line 3440 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::AllJointsRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 3324 of file icub.pb.cc.
New() [1/2]
AllJointsRequest* iCubInterfaceMessages::AllJointsRequest::New () const inline final
Definition at line 1234 of file icub.pb.h.
New() [2/2]
AllJointsRequest* iCubInterfaceMessages::AllJointsRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1238 of file icub.pb.h.
operator=()
AllJointsRequest& iCubInterfaceMessages::AllJointsRequest::operator= (const AllJointsRequest & from) inline
Definition at line 1197 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::AllJointsRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 3368 of file icub.pb.cc.
set_encode()
void iCubInterfaceMessages::AllJointsRequest::set_encode (bool value) inline
Definition at line 3542 of file icub.pb.h.
Referenced by MergeFrom(), and ClientInstance::retrieve_alljoints().
Swap()
void iCubInterfaceMessages::AllJointsRequest::Swap (AllJointsRequest * other)
Definition at line 3470 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 1289 of file icub.pb.h.
swap
void swap (AllJointsRequest & a, AllJointsRequest & b) friend
Definition at line 1228 of file icub.pb.h.
Member Data Documentation
kEncodeFieldNumber
const int iCubInterfaceMessages::AllJointsRequest::kEncodeFieldNumber = 1 static
Definition at line 1279 of file icub.pb.h.
kIndexInFileMessages
constexpr int iCubInterfaceMessages::AllJointsRequest::kIndexInFileMessages static constexpr
Initial value:
=
    9
Definition at line 1224 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc