ANNarchy iCub Interface: auto_test Namespace Reference
auto_test Namespace Reference
Functions
def check_position_double_mult (name, start, jnt_count, read_method, position)
def check_position_double_all (name, read_method, position)
def check_position_pop_mult (name, start, jnt_count, read_method, position)
def check_position_pop_all (name, read_method, position)
def rel_pos_double (ann_wrapper, name, key, target_positions)
def rel_pos_pop (ann_wrapper, name, key, target_positions)
def write_joint_each (ann_wrapper, pos_type, positioning, block, name, target_positions, write_method, read_method, check_method, res_path, jnts, rel_method=None, positions_double=None)
def write_joint_mult (ann_wrapper, pos_type, positioning, block, name, target_positions, write_method, read_method, check_method, res_path, jnt_sel, rel_method=None, positions_double=None)
def write_joint_all (ann_wrapper, pos_type, positioning, block, name, target_positions, write_method, read_method, check_method, res_path, rel_method=None, positions_double=None)
def test_joint_positioning (ann_wrapper)
def test_tactile_reading (ann_wrapper)
def test_visual_perception (ann_wrapper)
Variables
wrapper = iCub_Interface.iCubANN_wrapper()
Detailed Description
 *  Copyright (C) 2019-2020 Torsten Follak
 *
 *  auto_test.py is part of the iCub ANNarchy interface
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  The iCub ANNarchy interface is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this headers. If not, see <http://www.gnu.org/licenses/>.
Function Documentation
check_position_double_all()
def auto_test.check_position_double_all (name, read_method, position)
check_position_double_mult()
def auto_test.check_position_double_mult (name, start, jnt_count, read_method, position)
check_position_pop_all()
def auto_test.check_position_pop_all (name, read_method, position)
check_position_pop_mult()
def auto_test.check_position_pop_mult (name, start, jnt_count, read_method, position)
rel_pos_double()
def auto_test.rel_pos_double (ann_wrapper, name, key, target_positions)
rel_pos_pop()
def auto_test.rel_pos_pop (ann_wrapper, name, key, target_positions)
test_joint_positioning()
def auto_test.test_joint_positioning (ann_wrapper)
    Test the joint control in case of writing and reading. The results are compared to check the correct movement of the joints.
    params:
        ann_wrapper     -- iCub_ANNarchy Interface
test_tactile_reading()
def auto_test.test_tactile_reading (ann_wrapper)
    Test the tactile sensing module of the interface, by touching the robot arm with a sphere at multiple points.
    params:
        ann_wrapper     -- iCub_ANNarchy Interface
test_visual_perception()
def auto_test.test_visual_perception (ann_wrapper)
    Test the visual perception module, by presenting the iCub several objects and save the recorded images.
    params:
        ann_wrapper     -- iCub_ANNarchy Interface
write_joint_all()
def auto_test.write_joint_all (ann_wrapper, pos_type, positioning, block, name, target_positions, write_method, read_method, check_method, res_path, rel_method = None, positions_double = None)
Referenced by test_joint_positioning().
write_joint_each()
def auto_test.write_joint_each (ann_wrapper, pos_type, positioning, block, name, target_positions, write_method, read_method, check_method, res_path, jnts, rel_method = None, positions_double = None)
Referenced by test_joint_positioning().
write_joint_mult()
def auto_test.write_joint_mult (ann_wrapper, pos_type, positioning, block, name, target_positions, write_method, read_method, check_method, res_path, jnt_sel, rel_method = None, positions_double = None)
Referenced by test_joint_positioning().
Variable Documentation
wrapper
auto_test.wrapper = iCub_Interface.iCubANN_wrapper()