ANNarchy iCub Interface: iCubInterfaceMessages::SkinHandRequest Class Reference
iCubInterfaceMessages::SkinHandRequest Class Reference
#include <icub.pb.h>
Public Member Functions
SkinHandRequest ()
virtual ~SkinHandRequest ()
SkinHandRequest (const SkinHandRequest &from)
SkinHandRequest & operator= (const SkinHandRequest &from)
void Swap (SkinHandRequest *other)
SkinHandRequest * New () const final
SkinHandRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SkinHandRequest &from)
void MergeFrom (const SkinHandRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
SkinHandRequest ()
virtual ~SkinHandRequest ()
SkinHandRequest (const SkinHandRequest &from)
SkinHandRequest & operator= (const SkinHandRequest &from)
void Swap (SkinHandRequest *other)
SkinHandRequest * New () const final
SkinHandRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SkinHandRequest &from)
void MergeFrom (const SkinHandRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SkinHandRequest & default_instance ()
static void InitAsDefaultInstance ()
static const SkinHandRequest * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const SkinHandRequest & default_instance ()
static void InitAsDefaultInstance ()
static const SkinHandRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (SkinHandRequest &a, SkinHandRequest &b)
void swap (SkinHandRequest &a, SkinHandRequest &b)
Detailed Description
Definition at line 3115 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
SkinHandRequest() [1/4]
iCubInterfaceMessages::SkinHandRequest::SkinHandRequest ()
Definition at line 7529 of file icub.pb.cc.
~SkinHandRequest() [1/2]
iCubInterfaceMessages::SkinHandRequest::~SkinHandRequest () virtual
Definition at line 7546 of file icub.pb.cc.
SkinHandRequest() [2/4]
iCubInterfaceMessages::SkinHandRequest::SkinHandRequest (const SkinHandRequest & from)
Definition at line 7536 of file icub.pb.cc.
SkinHandRequest() [3/4]
iCubInterfaceMessages::SkinHandRequest::SkinHandRequest ()
~SkinHandRequest() [2/2]
virtual iCubInterfaceMessages::SkinHandRequest::~SkinHandRequest () virtual
SkinHandRequest() [4/4]
iCubInterfaceMessages::SkinHandRequest::SkinHandRequest (const SkinHandRequest & from)
Member Function Documentation
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::SkinHandRequest::ByteSizeLong () const final
Definition at line 7630 of file icub.pb.cc.
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::SkinHandRequest::ByteSizeLong () const final
Clear() [1/2]
void iCubInterfaceMessages::SkinHandRequest::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::SkinHandRequest::Clear () final
Definition at line 7568 of file icub.pb.cc.
Referenced by CopyFrom().
CopyFrom() [1/4]
void iCubInterfaceMessages::SkinHandRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 7668 of file icub.pb.cc.
CopyFrom() [2/4]
void iCubInterfaceMessages::SkinHandRequest::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [3/4]
void iCubInterfaceMessages::SkinHandRequest::CopyFrom (const SkinHandRequest & from)
Definition at line 7675 of file icub.pb.cc.
CopyFrom() [4/4]
void iCubInterfaceMessages::SkinHandRequest::CopyFrom (const SkinHandRequest & from)
default_instance() [1/2]
const SkinHandRequest & iCubInterfaceMessages::SkinHandRequest::default_instance () static
Definition at line 7562 of file icub.pb.cc.
default_instance() [2/2]
static const SkinHandRequest& iCubInterfaceMessages::SkinHandRequest::default_instance () static
descriptor() [1/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::SkinHandRequest::descriptor () static
descriptor() [2/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::SkinHandRequest::descriptor () static
Definition at line 7557 of file icub.pb.cc.
GetCachedSize() [1/2]
int iCubInterfaceMessages::SkinHandRequest::GetCachedSize () const inline final
Definition at line 3180 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::SkinHandRequest::GetCachedSize () const inline final
Definition at line 3180 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
google::protobuf::Metadata iCubInterfaceMessages::SkinHandRequest::GetMetadata () const final
Definition at line 7695 of file icub.pb.cc.
GetMetadata() [2/2]
::google::protobuf::Metadata iCubInterfaceMessages::SkinHandRequest::GetMetadata () const final
InitAsDefaultInstance() [1/2]
void iCubInterfaceMessages::SkinHandRequest::InitAsDefaultInstance () static
Definition at line 7524 of file icub.pb.cc.
InitAsDefaultInstance() [2/2]
static void iCubInterfaceMessages::SkinHandRequest::InitAsDefaultInstance () static
internal_default_instance() [1/2]
static const SkinHandRequest* iCubInterfaceMessages::SkinHandRequest::internal_default_instance () inline static
Definition at line 3145 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
internal_default_instance() [2/2]
static const SkinHandRequest* iCubInterfaceMessages::SkinHandRequest::internal_default_instance () inline static
Definition at line 3145 of file iCub_ANN_Interface/grpc/icub.pb.h.
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::SkinHandRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 7615 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::SkinHandRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::SkinHandRequest::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::SkinHandRequest::IsInitialized () const final
Definition at line 7682 of file icub.pb.cc.
MergeFrom() [1/4]
void iCubInterfaceMessages::SkinHandRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 7644 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/4]
void iCubInterfaceMessages::SkinHandRequest::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [3/4]
void iCubInterfaceMessages::SkinHandRequest::MergeFrom (const SkinHandRequest & from)
MergeFrom() [4/4]
void iCubInterfaceMessages::SkinHandRequest::MergeFrom (const SkinHandRequest & from)
Definition at line 7659 of file icub.pb.cc.
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::SkinHandRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::SkinHandRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 7577 of file icub.pb.cc.
New() [1/4]
SkinHandRequest* iCubInterfaceMessages::SkinHandRequest::New () const inline final
Definition at line 3159 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
SkinHandRequest* iCubInterfaceMessages::SkinHandRequest::New () const inline final
Definition at line 3159 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
SkinHandRequest* iCubInterfaceMessages::SkinHandRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 3163 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
SkinHandRequest* iCubInterfaceMessages::SkinHandRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 3163 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
SkinHandRequest& iCubInterfaceMessages::SkinHandRequest::operator= (const SkinHandRequest & from) inline
Definition at line 3122 of file iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
SkinHandRequest& iCubInterfaceMessages::SkinHandRequest::operator= (const SkinHandRequest & from) inline
Definition at line 3122 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::SkinHandRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 7602 of file icub.pb.cc.
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::SkinHandRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Swap() [1/2]
void iCubInterfaceMessages::SkinHandRequest::Swap (SkinHandRequest * other)
Definition at line 7686 of file icub.pb.cc.
Swap() [2/2]
void iCubInterfaceMessages::SkinHandRequest::Swap (SkinHandRequest * other)
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 3207 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (SkinHandRequest & a, SkinHandRequest & b) friend
Definition at line 3153 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (SkinHandRequest & a, SkinHandRequest & b) friend
Definition at line 3153 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::SkinHandRequest::kIndexInFileMessages static constexpr
Initial value:
=
    27
Definition at line 3149 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc