ANNarchy iCub Interface: iCubInterfaceMessages::TestResponse Class Reference
iCubInterfaceMessages::TestResponse Class Reference
#include <icub.pb.h>
Public Member Functions
TestResponse ()
virtual ~TestResponse ()
TestResponse (const TestResponse &from)
TestResponse & operator= (const TestResponse &from)
void Swap (TestResponse *other)
TestResponse * New () const final
TestResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const TestResponse &from)
void MergeFrom (const TestResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const TestResponse & default_instance ()
static void InitAsDefaultInstance ()
static const TestResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kStatusFieldNumber = 2
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (TestResponse &a, TestResponse &b)
Detailed Description
Definition at line 399 of file icub.pb.h.
Constructor & Destructor Documentation
TestResponse() [1/2]
iCubInterfaceMessages::TestResponse::TestResponse ()
Definition at line 1398 of file icub.pb.cc.
~TestResponse()
iCubInterfaceMessages::TestResponse::~TestResponse () virtual
Definition at line 1417 of file icub.pb.cc.
TestResponse() [2/2]
iCubInterfaceMessages::TestResponse::TestResponse (const TestResponse & from)
Definition at line 1405 of file icub.pb.cc.
Member Function Documentation
ByteSizeLong()
size_t iCubInterfaceMessages::TestResponse::ByteSizeLong () const final
Definition at line 1534 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::TestResponse::Clear () final
Definition at line 1439 of file icub.pb.cc.
Referenced by CopyFrom().
clear_status()
void iCubInterfaceMessages::TestResponse::clear_status () inline
Definition at line 3259 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::TestResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 1581 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::TestResponse::CopyFrom (const TestResponse & from)
Definition at line 1588 of file icub.pb.cc.
default_instance()
const TestResponse & iCubInterfaceMessages::TestResponse::default_instance () static
Definition at line 1433 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::TestResponse::descriptor () static
Definition at line 1428 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::TestResponse::GetCachedSize () const inline final
Definition at line 464 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::TestResponse::GetMetadata () const final
Definition at line 1609 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::TestResponse::InitAsDefaultInstance () static
Definition at line 1392 of file icub.pb.cc.
internal_default_instance()
static const TestResponse* iCubInterfaceMessages::TestResponse::internal_default_instance () inline static
Definition at line 429 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::TestResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 1513 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::TestResponse::IsInitialized () const final
Definition at line 1595 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::TestResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 1554 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::TestResponse::MergeFrom (const TestResponse & from)
Definition at line 1569 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::TestResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 1449 of file icub.pb.cc.
New() [1/2]
TestResponse* iCubInterfaceMessages::TestResponse::New () const inline final
Definition at line 443 of file icub.pb.h.
New() [2/2]
TestResponse* iCubInterfaceMessages::TestResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 447 of file icub.pb.h.
operator=()
TestResponse& iCubInterfaceMessages::TestResponse::operator= (const TestResponse & from) inline
Definition at line 406 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::TestResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 1494 of file icub.pb.cc.
set_status()
void iCubInterfaceMessages::TestResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 3266 of file icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status()
iCubInterfaceMessages::Status iCubInterfaceMessages::TestResponse::status () const inline
Definition at line 3262 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
Swap()
void iCubInterfaceMessages::TestResponse::Swap (TestResponse * other)
Definition at line 1599 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 498 of file icub.pb.h.
swap
void swap (TestResponse & a, TestResponse & b) friend
Definition at line 437 of file icub.pb.h.
Member Data Documentation
kIndexInFileMessages
constexpr int iCubInterfaceMessages::TestResponse::kIndexInFileMessages static constexpr
Initial value:
=
    2
Definition at line 433 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kStatusFieldNumber
const int iCubInterfaceMessages::TestResponse::kStatusFieldNumber = 2 static
Definition at line 488 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc