ANNarchy iCub Interface: iCubInterfaceMessages::DoubleVector Class Reference
iCubInterfaceMessages::DoubleVector Class Reference
#include <icub.pb.h>
Public Member Functions
DoubleVector ()
virtual ~DoubleVector ()
DoubleVector (const DoubleVector &from)
DoubleVector & operator= (const DoubleVector &from)
void Swap (DoubleVector *other)
DoubleVector * New () const final
DoubleVector * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const DoubleVector &from)
void MergeFrom (const DoubleVector &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int values_size () const
void clear_values ()
double values (int index) const
void set_values (int index, double value)
void add_values (double value)
const ::google::protobuf::RepeatedField< double > & values () const
::google::protobuf::RepeatedField< double > * mutable_values ()
DoubleVector ()
virtual ~DoubleVector ()
DoubleVector (const DoubleVector &from)
DoubleVector & operator= (const DoubleVector &from)
void Swap (DoubleVector *other)
DoubleVector * New () const final
DoubleVector * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const DoubleVector &from)
void MergeFrom (const DoubleVector &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int values_size () const
void clear_values ()
double values (int index) const
void set_values (int index, double value)
void add_values (double value)
const ::google::protobuf::RepeatedField< double > & values () const
::google::protobuf::RepeatedField< double > * mutable_values ()
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const DoubleVector & default_instance ()
static void InitAsDefaultInstance ()
static const DoubleVector * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const DoubleVector & default_instance ()
static void InitAsDefaultInstance ()
static const DoubleVector * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kValuesFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (DoubleVector &a, DoubleVector &b)
void swap (DoubleVector &a, DoubleVector &b)
Detailed Description
Definition at line 193 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
DoubleVector() [1/4]
iCubInterfaceMessages::DoubleVector::DoubleVector ()
Definition at line 973 of file icub.pb.cc.
~DoubleVector() [1/2]
iCubInterfaceMessages::DoubleVector::~DoubleVector () virtual
Definition at line 991 of file icub.pb.cc.
DoubleVector() [2/4]
iCubInterfaceMessages::DoubleVector::DoubleVector (const DoubleVector & from)
Definition at line 980 of file icub.pb.cc.
DoubleVector() [3/4]
iCubInterfaceMessages::DoubleVector::DoubleVector ()
~DoubleVector() [2/2]
virtual iCubInterfaceMessages::DoubleVector::~DoubleVector () virtual
DoubleVector() [4/4]
iCubInterfaceMessages::DoubleVector::DoubleVector (const DoubleVector & from)
Member Function Documentation
add_values() [1/2]
void iCubInterfaceMessages::DoubleVector::add_values (double value) inline
Definition at line 3235 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
add_values() [2/2]
void iCubInterfaceMessages::DoubleVector::add_values (double value)
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::DoubleVector::ByteSizeLong () const final
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::DoubleVector::ByteSizeLong () const final
Definition at line 1122 of file icub.pb.cc.
Clear() [1/2]
void iCubInterfaceMessages::DoubleVector::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::DoubleVector::Clear () final
Definition at line 1013 of file icub.pb.cc.
Referenced by CopyFrom().
clear_values() [1/2]
void iCubInterfaceMessages::DoubleVector::clear_values () inline
Definition at line 3224 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_values() [2/2]
void iCubInterfaceMessages::DoubleVector::clear_values ()
CopyFrom() [1/4]
void iCubInterfaceMessages::DoubleVector::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/4]
void iCubInterfaceMessages::DoubleVector::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 1177 of file icub.pb.cc.
Referenced by operator=(), iCubInterfaceMessages::TestRequest::operator=(), iCubInterfaceMessages::TestResponse::operator=(), iCubInterfaceMessages::ImageRequest::operator=(), iCubInterfaceMessages::ImageResponse::operator=(), iCubInterfaceMessages::SingleJointRequest::operator=(), iCubInterfaceMessages::SingleJointResponse::operator=(), iCubInterfaceMessages::MultiJointRequest::operator=(), iCubInterfaceMessages::MultiJointResponse::operator=(), iCubInterfaceMessages::AllJointsRequest::operator=(), iCubInterfaceMessages::AllJointsResponse::operator=(), iCubInterfaceMessages::SingleTargetRequest::operator=(), iCubInterfaceMessages::SingleTargetResponse::operator=(), iCubInterfaceMessages::MultiTargetRequest::operator=(), iCubInterfaceMessages::MultiTargetResponse::operator=(), iCubInterfaceMessages::AllTargetRequest::operator=(), iCubInterfaceMessages::AllTargetResponse::operator=(), iCubInterfaceMessages::SingleTargetEncodedRequest::operator=(), iCubInterfaceMessages::SingleTargetEncodedResponse::operator=(), iCubInterfaceMessages::MultiTargetEncodedRequest::operator=(), iCubInterfaceMessages::MultiTargetEncodedResponse::operator=(), iCubInterfaceMessages::AllTargetEncodedRequest::operator=(), iCubInterfaceMessages::AllTargetEncodedResponse::operator=(), iCubInterfaceMessages::SkinRequest::operator=(), iCubInterfaceMessages::SkinResponse::operator=(), iCubInterfaceMessages::SkinArmRequest::operator=(), iCubInterfaceMessages::SkinForearmRequest::operator=(), and iCubInterfaceMessages::SkinHandRequest::operator=().
CopyFrom() [3/4]
void iCubInterfaceMessages::DoubleVector::CopyFrom (const DoubleVector & from)
CopyFrom() [4/4]
void iCubInterfaceMessages::DoubleVector::CopyFrom (const DoubleVector & from)
Definition at line 1184 of file icub.pb.cc.
default_instance() [1/2]
const DoubleVector & iCubInterfaceMessages::DoubleVector::default_instance () static
Definition at line 1007 of file icub.pb.cc.
default_instance() [2/2]
static const DoubleVector& iCubInterfaceMessages::DoubleVector::default_instance () static
descriptor() [1/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::DoubleVector::descriptor () static
Definition at line 1002 of file icub.pb.cc.
descriptor() [2/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::DoubleVector::descriptor () static
GetCachedSize() [1/2]
int iCubInterfaceMessages::DoubleVector::GetCachedSize () const inline final
Definition at line 258 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::DoubleVector::GetCachedSize () const inline final
Definition at line 258 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
::google::protobuf::Metadata iCubInterfaceMessages::DoubleVector::GetMetadata () const final
GetMetadata() [2/2]
google::protobuf::Metadata iCubInterfaceMessages::DoubleVector::GetMetadata () const final
Definition at line 1205 of file icub.pb.cc.
InitAsDefaultInstance() [1/2]
void iCubInterfaceMessages::DoubleVector::InitAsDefaultInstance () static
Definition at line 967 of file icub.pb.cc.
InitAsDefaultInstance() [2/2]
static void iCubInterfaceMessages::DoubleVector::InitAsDefaultInstance () static
internal_default_instance() [1/2]
static const DoubleVector* iCubInterfaceMessages::DoubleVector::internal_default_instance () inline static
Definition at line 223 of file iCub_ANN_Interface/grpc/icub.pb.h.
internal_default_instance() [2/2]
static const DoubleVector* iCubInterfaceMessages::DoubleVector::internal_default_instance () inline static
Definition at line 223 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::DoubleVector::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 1094 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::DoubleVector::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::DoubleVector::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::DoubleVector::IsInitialized () const final
Definition at line 1191 of file icub.pb.cc.
MergeFrom() [1/4]
void iCubInterfaceMessages::DoubleVector::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/4]
void iCubInterfaceMessages::DoubleVector::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 1152 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [3/4]
void iCubInterfaceMessages::DoubleVector::MergeFrom (const DoubleVector & from)
MergeFrom() [4/4]
void iCubInterfaceMessages::DoubleVector::MergeFrom (const DoubleVector & from)
Definition at line 1167 of file icub.pb.cc.
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::DoubleVector::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 1023 of file icub.pb.cc.
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::DoubleVector::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_values() [1/2]
google::protobuf::RepeatedField< double > * iCubInterfaceMessages::DoubleVector::mutable_values () inline
Definition at line 3245 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_values() [2/2]
::google::protobuf::RepeatedField< double >* iCubInterfaceMessages::DoubleVector::mutable_values ()
New() [1/4]
DoubleVector* iCubInterfaceMessages::DoubleVector::New () const inline final
Definition at line 237 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
DoubleVector* iCubInterfaceMessages::DoubleVector::New () const inline final
Definition at line 237 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
DoubleVector* iCubInterfaceMessages::DoubleVector::New (::google::protobuf::Arena * arena) const inline final
Definition at line 241 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
DoubleVector* iCubInterfaceMessages::DoubleVector::New (::google::protobuf::Arena * arena) const inline final
Definition at line 241 of file iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
DoubleVector& iCubInterfaceMessages::DoubleVector::operator= (const DoubleVector & from) inline
Definition at line 200 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
DoubleVector& iCubInterfaceMessages::DoubleVector::operator= (const DoubleVector & from) inline
Definition at line 200 of file iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::DoubleVector::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::DoubleVector::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 1072 of file icub.pb.cc.
set_values() [1/2]
void iCubInterfaceMessages::DoubleVector::set_values (int index, double value)
set_values() [2/2]
void iCubInterfaceMessages::DoubleVector::set_values (int index, double value) inline
Definition at line 3231 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Swap() [1/2]
void iCubInterfaceMessages::DoubleVector::Swap (DoubleVector * other)
Swap() [2/2]
void iCubInterfaceMessages::DoubleVector::Swap (DoubleVector * other)
Definition at line 1195 of file icub.pb.cc.
values() [1/4]
const ::google::protobuf::RepeatedField< double >& iCubInterfaceMessages::DoubleVector::values () const
values() [2/4]
const ::google::protobuf::RepeatedField< double > & iCubInterfaceMessages::DoubleVector::values () const inline
Definition at line 3240 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by SerializeWithCachedSizes().
values() [3/4]
double iCubInterfaceMessages::DoubleVector::values (int index) const inline
Definition at line 3227 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
values() [4/4]
double iCubInterfaceMessages::DoubleVector::values (int index) const
values_size() [1/2]
int iCubInterfaceMessages::DoubleVector::values_size () const inline
Definition at line 3221 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
values_size() [2/2]
int iCubInterfaceMessages::DoubleVector::values_size () const
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 299 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (DoubleVector & a, DoubleVector & b) friend
Definition at line 231 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (DoubleVector & a, DoubleVector & b) friend
Definition at line 231 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::DoubleVector::kIndexInFileMessages static constexpr
Initial value:
=
    0
Definition at line 227 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kValuesFieldNumber
static const int iCubInterfaceMessages::DoubleVector::kValuesFieldNumber = 1 static
Definition at line 283 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc