ANNarchy iCub Interface: Network Namespace Reference
Network Namespace Reference
Variables
dt
vis_pop_right
Interface Populations Visual input populations.
geometry
port
name
vis_pop_left
joint_ctrl_neuron
string parameters
string equations
tuple joints = (3, 4)
joint_read = iCub_pop.JointReadout(geometry=(2,), joints=joints, name="head_read")
joint_write = iCub_pop.JointControl(geometry=(2,), neuron=joint_ctrl_neuron, name="head_ctrl")
rand_neuron
Normal ANNarchy ANNarchy neurons.
sum_neuron
rand_population = ann.Population(geometry=(2,), neuron=rand_neuron, name="rand")
sum_population = ann.Population(geometry=(2,), neuron=sum_neuron, name="sum")
rand_sum = ann.Projection(rand_population, sum_population, "rand_num")
weights
joint_sum = ann.Projection(joint_read, sum_population, "joint")
sum_ctrl = ann.Projection(sum_population, joint_write, "exc")
sum_ctrl1 = ann.Projection(sum_population[0], joint_write[1], "inh")
sum_ctrl2 = ann.Projection(sum_population[1], joint_write[0], "inh")
m_right_eye = ann.Monitor(vis_pop_right, 'r')
m_left_eye = ann.Monitor(vis_pop_left, 'r')
m_joint_read = ann.Monitor(joint_read, 'r')
m_joint_ctrl = ann.Monitor(joint_write, ['r'])
net = ann.Network(everything=True)
Detailed Description
 *  Copyright (C) 2021 Torsten Fietzek
 *
 *  Network.py is part of the iCub ANNarchy interface
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  The iCub ANNarchy interface is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this headers. If not, see <http://www.gnu.org/licenses/>.
Variable Documentation
dt
Network.dt
Definition at line 25 of file Network.py.
equations
string Network.equations
Initial value:
 = """
         min_value = ite((sum(inh) < 0), (y0_min_m + m_min_m * sum(inh)), (y0_min_p + m_min_p * sum(inh)))
         max_value = ite((sum(inh) < 0), (y0_max_m + m_max_m * sum(inh)), (y0_max_p + m_max_p * sum(inh)))
         r = sum(exc): min=min_value, max=max_value
     """)
Definition at line 43 of file Network.py.
geometry
Network.geometry
Definition at line 29 of file Network.py.
joint_ctrl_neuron
Network.joint_ctrl_neuron
Definition at line 32 of file Network.py.
joint_read
Network.joint_read = iCub_pop.JointReadout(geometry=(2,), joints=joints, name="head_read")
Definition at line 52 of file Network.py.
joint_sum
Network.joint_sum = ann.Projection(joint_read, sum_population, "joint")
Definition at line 80 of file Network.py.
joint_write
Network.joint_write = iCub_pop.JointControl(geometry=(2,), neuron=joint_ctrl_neuron, name="head_ctrl")
Definition at line 55 of file Network.py.
joints
tuple Network.joints = (3, 4)
Definition at line 51 of file Network.py.
Referenced by JointWriter.GetJointCount(), JointReader.GetJointCount(), JointWriter.GetNeuronsPerJoint(), JointReader.GetNeuronsPerJoint(), JointWriter.Init(), JointReader.Init(), JointReader.ReadDoubleAll(), JointReader.ReadDoubleAllTime(), JointReader.ReadDoubleMultiple(), JointReader.ReadDoubleMultipleTime(), JointReader.ReadPopAll(), JointReader.ReadPopMultiple(), ClientInstance.retrieve_multijoints(), JointWriter.SetJointControlMode(), JointWriter.SetJointVelocity(), JointWriter.WriteDoubleAll(), JointWriter.WriteDoubleMultiple(), JointWriter.WriteDoubleOne(), JointWriter.WritePopAll(), JointWriter.WritePopMultiple(), and JointWriter.WritePopOne().
m_joint_ctrl
Network.m_joint_ctrl = ann.Monitor(joint_write, ['r'])
Definition at line 99 of file Network.py.
m_joint_read
Network.m_joint_read = ann.Monitor(joint_read, 'r')
Definition at line 98 of file Network.py.
m_left_eye
Network.m_left_eye = ann.Monitor(vis_pop_left, 'r')
Definition at line 96 of file Network.py.
m_right_eye
Network.m_right_eye = ann.Monitor(vis_pop_right, 'r')
Definition at line 95 of file Network.py.
name
Network.name
Definition at line 29 of file Network.py.
Referenced by INIReader.Get(), INIReader.GetBoolean(), INIReader.GetInteger(), INIReader.GetReal(), ini_parse_stream(), SkinReader.Init(), and iCubInterfaceMessages.Status_Parse().
net
Network.net = ann.Network(everything=True)
Definition at line 105 of file Network.py.
parameters
string Network.parameters
Initial value:
 = """
         y0_min_p = 0.
         y0_max_p = 0.
         m_min_p = 0.
         m_max_p = 0.
         y0_min_m = 0.
         y0_max_m = 0.
         m_min_m = 0.
         m_max_m = 0.
         """,
Definition at line 33 of file Network.py.
port
Network.port
Definition at line 29 of file Network.py.
Referenced by ClientInstance.ClientInstance(), ServerInstance.ServerInstance(), WriteClientInstance.WriteClientInstance(), and WriteOutputServerInstance< ANNarchyPopulation >.WriteOutputServerInstance().
rand_neuron
Network.rand_neuron
Initial value:
 =  ann.Neuron(
     parameters=,
     equations=)
Normal ANNarchy ANNarchy neurons.
Definition at line 59 of file Network.py.
rand_population
Network.rand_population = ann.Population(geometry=(2,), neuron=rand_neuron, name="rand")
Definition at line 73 of file Network.py.
rand_sum
Network.rand_sum = ann.Projection(rand_population, sum_population, "rand_num")
Definition at line 77 of file Network.py.
sum_ctrl
Network.sum_ctrl = ann.Projection(sum_population, joint_write, "exc")
Definition at line 83 of file Network.py.
sum_ctrl1
Network.sum_ctrl1 = ann.Projection(sum_population[0], joint_write[1], "inh")
Definition at line 87 of file Network.py.
sum_ctrl2
Network.sum_ctrl2 = ann.Projection(sum_population[1], joint_write[0], "inh")
Definition at line 90 of file Network.py.
sum_neuron
Network.sum_neuron
Initial value:
 =  ann.Neuron(
     parameters=,
     equations="r = sum(joint) + sum(rand_num): min=min_val, max=max_val")
Definition at line 65 of file Network.py.
sum_population
Network.sum_population = ann.Population(geometry=(2,), neuron=sum_neuron, name="sum")
Definition at line 74 of file Network.py.
vis_pop_left
Network.vis_pop_left
Definition at line 30 of file Network.py.
vis_pop_right
Network.vis_pop_right
Interface Populations Visual input populations.
Definition at line 29 of file Network.py.
weights
Network.weights
Definition at line 78 of file Network.py.