ANNarchy iCub Interface: google::protobuf Namespace Reference
google::protobuf Namespace Reference
Classes
struct is_proto_enum< ::iCubInterfaceMessages::Status >
Functions
template<>
::iCubInterfaceMessages::AllJointsRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllJointsRequest > (Arena *)
template<>
::iCubInterfaceMessages::AllJointsResponse * Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllJointsResponse > (Arena *)
template<>
::iCubInterfaceMessages::AllTargetEncodedRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllTargetEncodedRequest > (Arena *)
template<>
::iCubInterfaceMessages::AllTargetEncodedResponse * Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllTargetEncodedResponse > (Arena *)
template<>
::iCubInterfaceMessages::AllTargetRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllTargetRequest > (Arena *)
template<>
::iCubInterfaceMessages::AllTargetResponse * Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllTargetResponse > (Arena *)
template<>
::iCubInterfaceMessages::DoubleVector * Arena::CreateMaybeMessage<::iCubInterfaceMessages::DoubleVector > (Arena *)
template<>
::iCubInterfaceMessages::ImageRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::ImageRequest > (Arena *)
template<>
::iCubInterfaceMessages::ImageResponse * Arena::CreateMaybeMessage<::iCubInterfaceMessages::ImageResponse > (Arena *)
template<>
::iCubInterfaceMessages::MultiJointRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiJointRequest > (Arena *)
template<>
::iCubInterfaceMessages::MultiJointResponse * Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiJointResponse > (Arena *)
template<>
::iCubInterfaceMessages::MultiTargetEncodedRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiTargetEncodedRequest > (Arena *)
template<>
::iCubInterfaceMessages::MultiTargetEncodedResponse * Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiTargetEncodedResponse > (Arena *)
template<>
::iCubInterfaceMessages::MultiTargetRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiTargetRequest > (Arena *)
template<>
::iCubInterfaceMessages::MultiTargetResponse * Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiTargetResponse > (Arena *)
template<>
::iCubInterfaceMessages::SingleJointRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleJointRequest > (Arena *)
template<>
::iCubInterfaceMessages::SingleJointResponse * Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleJointResponse > (Arena *)
template<>
::iCubInterfaceMessages::SingleTargetEncodedRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleTargetEncodedRequest > (Arena *)
template<>
::iCubInterfaceMessages::SingleTargetEncodedResponse * Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleTargetEncodedResponse > (Arena *)
template<>
::iCubInterfaceMessages::SingleTargetRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleTargetRequest > (Arena *)
template<>
::iCubInterfaceMessages::SingleTargetResponse * Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleTargetResponse > (Arena *)
template<>
::iCubInterfaceMessages::SkinArmRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinArmRequest > (Arena *)
template<>
::iCubInterfaceMessages::SkinForearmRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinForearmRequest > (Arena *)
template<>
::iCubInterfaceMessages::SkinHandRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinHandRequest > (Arena *)
template<>
::iCubInterfaceMessages::SkinRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinRequest > (Arena *)
template<>
::iCubInterfaceMessages::SkinResponse * Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinResponse > (Arena *)
template<>
::iCubInterfaceMessages::TestRequest * Arena::CreateMaybeMessage<::iCubInterfaceMessages::TestRequest > (Arena *)
template<>
::iCubInterfaceMessages::TestResponse * Arena::CreateMaybeMessage<::iCubInterfaceMessages::TestResponse > (Arena *)
template<>
const EnumDescriptor * GetEnumDescriptor< ::iCubInterfaceMessages::Status > ()
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::DoubleVector * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::DoubleVector > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::TestRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::TestRequest > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::TestResponse * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::TestResponse > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::ImageRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::ImageRequest > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::ImageResponse * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::ImageResponse > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SingleJointRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleJointRequest > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SingleJointResponse * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleJointResponse > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::MultiJointRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiJointRequest > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::MultiJointResponse * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiJointResponse > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::AllJointsRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllJointsRequest > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::AllJointsResponse * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllJointsResponse > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SingleTargetRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetRequest > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SingleTargetResponse * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetResponse > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::MultiTargetRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetRequest > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::MultiTargetResponse * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetResponse > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::AllTargetRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetRequest > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::AllTargetResponse * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetResponse > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SingleTargetEncodedRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetEncodedRequest > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SingleTargetEncodedResponse * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetEncodedResponse > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::MultiTargetEncodedRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetEncodedRequest > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::MultiTargetEncodedResponse * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetEncodedResponse > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::AllTargetEncodedRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetEncodedRequest > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::AllTargetEncodedResponse * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetEncodedResponse > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SkinRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinRequest > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SkinResponse * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinResponse > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SkinArmRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinArmRequest > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SkinForearmRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinForearmRequest > (Arena *arena)
template<>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SkinHandRequest * Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinHandRequest > (Arena *arena)
Function Documentation
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllJointsRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::AllJointsRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllJointsRequest > (Arena * arena)
Definition at line 7732 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllJointsRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllJointsResponse >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::AllJointsResponse* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllJointsResponse > (Arena * arena)
Definition at line 7735 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllJointsResponse >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetEncodedRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::AllTargetEncodedRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetEncodedRequest > (Arena * arena)
Definition at line 7768 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetEncodedRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetEncodedResponse >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::AllTargetEncodedResponse* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetEncodedResponse > (Arena * arena)
Definition at line 7771 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetEncodedResponse >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::AllTargetRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetRequest > (Arena * arena)
Definition at line 7750 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetResponse >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::AllTargetResponse* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetResponse > (Arena * arena)
Definition at line 7753 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::AllTargetResponse >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::DoubleVector >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::DoubleVector* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::DoubleVector > (Arena * arena)
Definition at line 7705 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::DoubleVector >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::ImageRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::ImageRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::ImageRequest > (Arena * arena)
Definition at line 7714 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::ImageRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::ImageResponse >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::ImageResponse* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::ImageResponse > (Arena * arena)
Definition at line 7717 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::ImageResponse >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiJointRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::MultiJointRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiJointRequest > (Arena * arena)
Definition at line 7726 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiJointRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiJointResponse >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::MultiJointResponse* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiJointResponse > (Arena * arena)
Definition at line 7729 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiJointResponse >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetEncodedRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::MultiTargetEncodedRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetEncodedRequest > (Arena * arena)
Definition at line 7762 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetEncodedRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetEncodedResponse >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::MultiTargetEncodedResponse* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetEncodedResponse > (Arena * arena)
Definition at line 7765 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetEncodedResponse >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::MultiTargetRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetRequest > (Arena * arena)
Definition at line 7744 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetResponse >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::MultiTargetResponse* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetResponse > (Arena * arena)
Definition at line 7747 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::MultiTargetResponse >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleJointRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SingleJointRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleJointRequest > (Arena * arena)
Definition at line 7720 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleJointRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleJointResponse >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SingleJointResponse* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleJointResponse > (Arena * arena)
Definition at line 7723 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleJointResponse >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetEncodedRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SingleTargetEncodedRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetEncodedRequest > (Arena * arena)
Definition at line 7756 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetEncodedRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetEncodedResponse >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SingleTargetEncodedResponse* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetEncodedResponse > (Arena * arena)
Definition at line 7759 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetEncodedResponse >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SingleTargetRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetRequest > (Arena * arena)
Definition at line 7738 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetResponse >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SingleTargetResponse* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetResponse > (Arena * arena)
Definition at line 7741 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SingleTargetResponse >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinArmRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SkinArmRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinArmRequest > (Arena * arena)
Definition at line 7780 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinArmRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinForearmRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SkinForearmRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinForearmRequest > (Arena * arena)
Definition at line 7783 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinForearmRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinHandRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SkinHandRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinHandRequest > (Arena * arena)
Definition at line 7786 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinHandRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SkinRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinRequest > (Arena * arena)
Definition at line 7774 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinResponse >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::SkinResponse* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinResponse > (Arena * arena)
Definition at line 7777 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::SkinResponse >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::TestRequest >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::TestRequest* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::TestRequest > (Arena * arena)
Definition at line 7708 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::TestRequest >().
Arena::CreateMaybeMessage< ::iCubInterfaceMessages::TestResponse >()
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::iCubInterfaceMessages::TestResponse* google::protobuf::Arena::CreateMaybeMessage< ::iCubInterfaceMessages::TestResponse > (Arena * arena)
Definition at line 7711 of file icub.pb.cc.
Referenced by Arena::CreateMaybeMessage< ::iCubInterfaceMessages::TestResponse >().
Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllJointsRequest >()
template<> ::iCubInterfaceMessages::AllJointsRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllJointsRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllJointsResponse >()
template<> ::iCubInterfaceMessages::AllJointsResponse* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllJointsResponse > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllTargetEncodedRequest >()
template<> ::iCubInterfaceMessages::AllTargetEncodedRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllTargetEncodedRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllTargetEncodedResponse >()
template<> ::iCubInterfaceMessages::AllTargetEncodedResponse* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllTargetEncodedResponse > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllTargetRequest >()
template<> ::iCubInterfaceMessages::AllTargetRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllTargetRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllTargetResponse >()
template<> ::iCubInterfaceMessages::AllTargetResponse* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::AllTargetResponse > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::DoubleVector >()
template<> ::iCubInterfaceMessages::DoubleVector* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::DoubleVector > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::ImageRequest >()
template<> ::iCubInterfaceMessages::ImageRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::ImageRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::ImageResponse >()
template<> ::iCubInterfaceMessages::ImageResponse* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::ImageResponse > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiJointRequest >()
template<> ::iCubInterfaceMessages::MultiJointRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiJointRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiJointResponse >()
template<> ::iCubInterfaceMessages::MultiJointResponse* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiJointResponse > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiTargetEncodedRequest >()
template<> ::iCubInterfaceMessages::MultiTargetEncodedRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiTargetEncodedRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiTargetEncodedResponse >()
template<> ::iCubInterfaceMessages::MultiTargetEncodedResponse* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiTargetEncodedResponse > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiTargetRequest >()
template<> ::iCubInterfaceMessages::MultiTargetRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiTargetRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiTargetResponse >()
template<> ::iCubInterfaceMessages::MultiTargetResponse* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::MultiTargetResponse > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleJointRequest >()
template<> ::iCubInterfaceMessages::SingleJointRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleJointRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleJointResponse >()
template<> ::iCubInterfaceMessages::SingleJointResponse* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleJointResponse > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleTargetEncodedRequest >()
template<> ::iCubInterfaceMessages::SingleTargetEncodedRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleTargetEncodedRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleTargetEncodedResponse >()
template<> ::iCubInterfaceMessages::SingleTargetEncodedResponse* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleTargetEncodedResponse > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleTargetRequest >()
template<> ::iCubInterfaceMessages::SingleTargetRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleTargetRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleTargetResponse >()
template<> ::iCubInterfaceMessages::SingleTargetResponse* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::SingleTargetResponse > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinArmRequest >()
template<> ::iCubInterfaceMessages::SkinArmRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinArmRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinForearmRequest >()
template<> ::iCubInterfaceMessages::SkinForearmRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinForearmRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinHandRequest >()
template<> ::iCubInterfaceMessages::SkinHandRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinHandRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinRequest >()
template<> ::iCubInterfaceMessages::SkinRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinResponse >()
template<> ::iCubInterfaceMessages::SkinResponse* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::SkinResponse > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::TestRequest >()
template<> ::iCubInterfaceMessages::TestRequest* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::TestRequest > (Arena *)
Arena::CreateMaybeMessage<::iCubInterfaceMessages::TestResponse >()
template<> ::iCubInterfaceMessages::TestResponse* google::protobuf::Arena::CreateMaybeMessage<::iCubInterfaceMessages::TestResponse > (Arena *)
GetEnumDescriptor< ::iCubInterfaceMessages::Status >()
template<> const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::iCubInterfaceMessages::Status > () inline
Definition at line 4104 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.