ANNarchy iCub Interface: INIReader Class Reference
INIReader Class Reference
#include <INIReader.h>
Public Member Functions
INIReader (const std::string &filename)
int ParseError () const
std::string Get (const std::string &section, const std::string &name, const std::string &default_value) const
long GetInteger (const std::string &section, const std::string &name, long default_value) const
double GetReal (const std::string &section, const std::string &name, double default_value) const
bool GetBoolean (const std::string &section, const std::string &name, bool default_value) const
Detailed Description
Definition at line 16 of file INIReader.h.
Constructor & Destructor Documentation
INIReader()
INIReader::INIReader (const std::string & filename)
Definition at line 17 of file INIReader.cpp.
Member Function Documentation
Get()
string INIReader::Get (const std::string & section, const std::string & name, const std::string & default_value) const
Definition at line 27 of file INIReader.cpp.
Referenced by GetBoolean(), GetInteger(), GetReal(), JointWriter::Init(), JointReader::Init(), VisualReader::Init(), and SkinReader::Init().
GetBoolean()
bool INIReader::GetBoolean (const std::string & section, const std::string & name, bool default_value) const
Definition at line 53 of file INIReader.cpp.
Referenced by JointReader::Init(), JointWriter::Init(), VisualReader::Init(), and SkinReader::Init().
GetInteger()
long INIReader::GetInteger (const std::string & section, const std::string & name, long default_value) const
Definition at line 34 of file INIReader.cpp.
GetReal()
double INIReader::GetReal (const std::string & section, const std::string & name, double default_value) const
Definition at line 44 of file INIReader.cpp.
Referenced by JointReader::Init(), and JointWriter::Init().
ParseError()
int INIReader::ParseError () const
Definition at line 22 of file INIReader.cpp.
The documentation for this class was generated from the following files:
INIReader.h
INIReader.cpp