ANNarchy iCub Interface: iCubInterfaceMessages::ProvideInput::Service Class Reference
iCubInterfaceMessages::ProvideInput::Service Class Reference
#include <icub.grpc.pb.h>
Public Member Functions
Service ()
virtual ~Service ()
virtual ::grpc::Status ReadTest (::grpc::ServerContext *context, const ::iCubInterfaceMessages::TestRequest *request, ::iCubInterfaceMessages::TestResponse *response)
virtual ::grpc::Status ReadImage (::grpc::ServerContext *context, const ::iCubInterfaceMessages::ImageRequest *request, ::iCubInterfaceMessages::ImageResponse *response)
virtual ::grpc::Status ReadSingleJoint (::grpc::ServerContext *context, const ::iCubInterfaceMessages::SingleJointRequest *request, ::iCubInterfaceMessages::SingleJointResponse *response)
virtual ::grpc::Status ReadMultiJoints (::grpc::ServerContext *context, const ::iCubInterfaceMessages::MultiJointRequest *request, ::iCubInterfaceMessages::MultiJointResponse *response)
virtual ::grpc::Status ReadAllJoints (::grpc::ServerContext *context, const ::iCubInterfaceMessages::AllJointsRequest *request, ::iCubInterfaceMessages::AllJointsResponse *response)
virtual ::grpc::Status ReadSkin (::grpc::ServerContext *context, const ::iCubInterfaceMessages::SkinRequest *request, ::iCubInterfaceMessages::SkinResponse *response)
virtual ::grpc::Status ReadSkinArm (::grpc::ServerContext *context, const ::iCubInterfaceMessages::SkinArmRequest *request, ::iCubInterfaceMessages::SkinResponse *response)
virtual ::grpc::Status ReadSkinForearm (::grpc::ServerContext *context, const ::iCubInterfaceMessages::SkinForearmRequest *request, ::iCubInterfaceMessages::SkinResponse *response)
virtual ::grpc::Status ReadSkinHand (::grpc::ServerContext *context, const ::iCubInterfaceMessages::SkinHandRequest *request, ::iCubInterfaceMessages::SkinResponse *response)
Detailed Description
Definition at line 272 of file icub.grpc.pb.h.
Constructor & Destructor Documentation
Service()
iCubInterfaceMessages::ProvideInput::Service::Service ()
Definition at line 194 of file icub.grpc.pb.cc.
~Service()
iCubInterfaceMessages::ProvideInput::Service::~Service () virtual
Definition at line 242 of file icub.grpc.pb.cc.
Member Function Documentation
ReadAllJoints()
grpc::Status iCubInterfaceMessages::ProvideInput::Service::ReadAllJoints (::grpc::ServerContext * context, const ::iCubInterfaceMessages::AllJointsRequest * request, ::iCubInterfaceMessages::AllJointsResponse * response)
Definition at line 273 of file icub.grpc.pb.cc.
Referenced by Service().
ReadImage()
grpc::Status iCubInterfaceMessages::ProvideInput::Service::ReadImage (::grpc::ServerContext * context, const ::iCubInterfaceMessages::ImageRequest * request, ::iCubInterfaceMessages::ImageResponse * response)
Definition at line 252 of file icub.grpc.pb.cc.
Referenced by Service().
ReadMultiJoints()
grpc::Status iCubInterfaceMessages::ProvideInput::Service::ReadMultiJoints (::grpc::ServerContext * context, const ::iCubInterfaceMessages::MultiJointRequest * request, ::iCubInterfaceMessages::MultiJointResponse * response)
Definition at line 266 of file icub.grpc.pb.cc.
Referenced by Service().
ReadSingleJoint()
grpc::Status iCubInterfaceMessages::ProvideInput::Service::ReadSingleJoint (::grpc::ServerContext * context, const ::iCubInterfaceMessages::SingleJointRequest * request, ::iCubInterfaceMessages::SingleJointResponse * response)
Definition at line 259 of file icub.grpc.pb.cc.
Referenced by Service().
ReadSkin()
grpc::Status iCubInterfaceMessages::ProvideInput::Service::ReadSkin (::grpc::ServerContext * context, const ::iCubInterfaceMessages::SkinRequest * request, ::iCubInterfaceMessages::SkinResponse * response)
Definition at line 280 of file icub.grpc.pb.cc.
Referenced by Service().
ReadSkinArm()
grpc::Status iCubInterfaceMessages::ProvideInput::Service::ReadSkinArm (::grpc::ServerContext * context, const ::iCubInterfaceMessages::SkinArmRequest * request, ::iCubInterfaceMessages::SkinResponse * response)
Definition at line 287 of file icub.grpc.pb.cc.
Referenced by Service().
ReadSkinForearm()
grpc::Status iCubInterfaceMessages::ProvideInput::Service::ReadSkinForearm (::grpc::ServerContext * context, const ::iCubInterfaceMessages::SkinForearmRequest * request, ::iCubInterfaceMessages::SkinResponse * response)
Definition at line 294 of file icub.grpc.pb.cc.
Referenced by Service().
ReadSkinHand()
grpc::Status iCubInterfaceMessages::ProvideInput::Service::ReadSkinHand (::grpc::ServerContext * context, const ::iCubInterfaceMessages::SkinHandRequest * request, ::iCubInterfaceMessages::SkinResponse * response)
Definition at line 301 of file icub.grpc.pb.cc.
Referenced by Service().
ReadTest()
grpc::Status iCubInterfaceMessages::ProvideInput::Service::ReadTest (::grpc::ServerContext * context, const ::iCubInterfaceMessages::TestRequest * request, ::iCubInterfaceMessages::TestResponse * response)
Definition at line 245 of file icub.grpc.pb.cc.
Referenced by Service().
The documentation for this class was generated from the following files:
icub.grpc.pb.h
icub.grpc.pb.cc