ANNarchy iCub Interface: iCubInterfaceMessages::AllJointResponse Class Reference
iCubInterfaceMessages::AllJointResponse Class Reference
#include <icub.pb.h>
Public Member Functions
AllJointResponse ()
virtual ~AllJointResponse ()
AllJointResponse (const AllJointResponse &from)
AllJointResponse & operator= (const AllJointResponse &from)
void Swap (AllJointResponse *other)
AllJointResponse * New () const final
AllJointResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const AllJointResponse &from)
void MergeFrom (const AllJointResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const AllJointResponse & default_instance ()
static void InitAsDefaultInstance ()
static const AllJointResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kAngleFieldNumber = 2
static const int kStatusFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (AllJointResponse &a, AllJointResponse &b)
Detailed Description
Definition at line 856 of file icub.pb.h.
Constructor & Destructor Documentation
AllJointResponse() [1/2]
iCubInterfaceMessages::AllJointResponse::AllJointResponse ()
Definition at line 2403 of file icub.pb.cc.
~AllJointResponse()
iCubInterfaceMessages::AllJointResponse::~AllJointResponse () virtual
Definition at line 2423 of file icub.pb.cc.
AllJointResponse() [2/2]
iCubInterfaceMessages::AllJointResponse::AllJointResponse (const AllJointResponse & from)
Definition at line 2410 of file icub.pb.cc.
Member Function Documentation
add_angle()
void iCubInterfaceMessages::AllJointResponse::add_angle (double value) inline
Definition at line 2933 of file icub.pb.h.
angle() [1/2]
const ::google::protobuf::RepeatedField< double > & iCubInterfaceMessages::AllJointResponse::angle () const inline
Definition at line 2938 of file icub.pb.h.
Referenced by SerializeWithCachedSizes().
angle() [2/2]
double iCubInterfaceMessages::AllJointResponse::angle (int index) const inline
Definition at line 2925 of file icub.pb.h.
angle_size()
int iCubInterfaceMessages::AllJointResponse::angle_size () const inline
Definition at line 2919 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
ByteSizeLong()
size_t iCubInterfaceMessages::AllJointResponse::ByteSizeLong () const final
Definition at line 2582 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::AllJointResponse::Clear () final
Definition at line 2445 of file icub.pb.cc.
Referenced by CopyFrom().
clear_angle()
void iCubInterfaceMessages::AllJointResponse::clear_angle () inline
Definition at line 2922 of file icub.pb.h.
clear_status()
void iCubInterfaceMessages::AllJointResponse::clear_status () inline
Definition at line 2905 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::AllJointResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 2646 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::AllJointResponse::CopyFrom (const AllJointResponse & from)
Definition at line 2653 of file icub.pb.cc.
default_instance()
const AllJointResponse & iCubInterfaceMessages::AllJointResponse::default_instance () static
Definition at line 2439 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::AllJointResponse::descriptor () static
Definition at line 2434 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::AllJointResponse::GetCachedSize () const inline final
Definition at line 921 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::AllJointResponse::GetMetadata () const final
Definition at line 2675 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::AllJointResponse::InitAsDefaultInstance () static
Definition at line 2396 of file icub.pb.cc.
internal_default_instance()
static const AllJointResponse* iCubInterfaceMessages::AllJointResponse::internal_default_instance () inline static
Definition at line 886 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::AllJointResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 2548 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::AllJointResponse::IsInitialized () const final
Definition at line 2660 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::AllJointResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 2618 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::AllJointResponse::MergeFrom (const AllJointResponse & from)
Definition at line 2633 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::AllJointResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 2456 of file icub.pb.cc.
mutable_angle()
google::protobuf::RepeatedField< double > * iCubInterfaceMessages::AllJointResponse::mutable_angle () inline
Definition at line 2943 of file icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/2]
AllJointResponse* iCubInterfaceMessages::AllJointResponse::New () const inline final
Definition at line 900 of file icub.pb.h.
New() [2/2]
AllJointResponse* iCubInterfaceMessages::AllJointResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 904 of file icub.pb.h.
operator=()
AllJointResponse& iCubInterfaceMessages::AllJointResponse::operator= (const AllJointResponse & from) inline
Definition at line 863 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::AllJointResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 2520 of file icub.pb.cc.
set_angle()
void iCubInterfaceMessages::AllJointResponse::set_angle (int index, double value) inline
Definition at line 2929 of file icub.pb.h.
set_status()
void iCubInterfaceMessages::AllJointResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 2912 of file icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status()
iCubInterfaceMessages::Status iCubInterfaceMessages::AllJointResponse::status () const inline
Definition at line 2908 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
Swap()
void iCubInterfaceMessages::AllJointResponse::Swap (AllJointResponse * other)
Definition at line 2664 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 969 of file icub.pb.h.
swap
void swap (AllJointResponse & a, AllJointResponse & b) friend
Definition at line 894 of file icub.pb.h.
Member Data Documentation
kAngleFieldNumber
const int iCubInterfaceMessages::AllJointResponse::kAngleFieldNumber = 2 static
Definition at line 946 of file icub.pb.h.
kIndexInFileMessages
constexpr int iCubInterfaceMessages::AllJointResponse::kIndexInFileMessages static constexpr
Initial value:
=
    6
Definition at line 890 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kStatusFieldNumber
const int iCubInterfaceMessages::AllJointResponse::kStatusFieldNumber = 1 static
Definition at line 957 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc