ANNarchy iCub Interface: iCubInterfaceMessages::AllJointEncodedResponse Class Reference
iCubInterfaceMessages::AllJointEncodedResponse Class Reference
#include <icub.pb.h>
Public Member Functions
AllJointEncodedResponse ()
virtual ~AllJointEncodedResponse ()
AllJointEncodedResponse (const AllJointEncodedResponse &from)
AllJointEncodedResponse & operator= (const AllJointEncodedResponse &from)
void Swap (AllJointEncodedResponse *other)
AllJointEncodedResponse * New () const final
AllJointEncodedResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const AllJointEncodedResponse &from)
void MergeFrom (const AllJointEncodedResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
::iCubInterfaceMessages::DoubleVector * mutable_angle (int index)
::google::protobuf::RepeatedPtrField< ::iCubInterfaceMessages::DoubleVector > * mutable_angle ()
const ::iCubInterfaceMessages::DoubleVector & angle (int index) const
::iCubInterfaceMessages::DoubleVector * add_angle ()
const ::google::protobuf::RepeatedPtrField< ::iCubInterfaceMessages::DoubleVector > & angle () const
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const AllJointEncodedResponse & default_instance ()
static void InitAsDefaultInstance ()
static const AllJointEncodedResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kAngleFieldNumber = 2
static const int kStatusFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (AllJointEncodedResponse &a, AllJointEncodedResponse &b)
Detailed Description
Definition at line 1319 of file icub.pb.h.
Constructor & Destructor Documentation
AllJointEncodedResponse() [1/2]
iCubInterfaceMessages::AllJointEncodedResponse::AllJointEncodedResponse ()
Definition at line 3500 of file icub.pb.cc.
~AllJointEncodedResponse()
iCubInterfaceMessages::AllJointEncodedResponse::~AllJointEncodedResponse () virtual
Definition at line 3520 of file icub.pb.cc.
AllJointEncodedResponse() [2/2]
iCubInterfaceMessages::AllJointEncodedResponse::AllJointEncodedResponse (const AllJointEncodedResponse & from)
Definition at line 3507 of file icub.pb.cc.
Member Function Documentation
add_angle()
iCubInterfaceMessages::DoubleVector * iCubInterfaceMessages::AllJointEncodedResponse::add_angle () inline
Definition at line 3162 of file icub.pb.h.
Referenced by MergePartialFromCodedStream().
angle() [1/2]
const ::google::protobuf::RepeatedPtrField<::iCubInterfaceMessages::DoubleVector > & iCubInterfaceMessages::AllJointEncodedResponse::angle () const inline
Definition at line 3167 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
angle() [2/2]
const ::iCubInterfaceMessages::DoubleVector & iCubInterfaceMessages::AllJointEncodedResponse::angle (int index) const inline
Definition at line 3158 of file icub.pb.h.
angle_size()
int iCubInterfaceMessages::AllJointEncodedResponse::angle_size () const inline
Definition at line 3143 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
ByteSizeLong()
size_t iCubInterfaceMessages::AllJointEncodedResponse::ByteSizeLong () const final
Definition at line 3667 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::AllJointEncodedResponse::Clear () final
Definition at line 3542 of file icub.pb.cc.
Referenced by CopyFrom().
clear_angle()
void iCubInterfaceMessages::AllJointEncodedResponse::clear_angle () inline
Definition at line 3146 of file icub.pb.h.
clear_status()
void iCubInterfaceMessages::AllJointEncodedResponse::clear_status () inline
Definition at line 3129 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::AllJointEncodedResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 3726 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::AllJointEncodedResponse::CopyFrom (const AllJointEncodedResponse & from)
Definition at line 3733 of file icub.pb.cc.
default_instance()
const AllJointEncodedResponse & iCubInterfaceMessages::AllJointEncodedResponse::default_instance () static
Definition at line 3536 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::AllJointEncodedResponse::descriptor () static
Definition at line 3531 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::AllJointEncodedResponse::GetCachedSize () const inline final
Definition at line 1384 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::AllJointEncodedResponse::GetMetadata () const final
Definition at line 3755 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::AllJointEncodedResponse::InitAsDefaultInstance () static
Definition at line 3493 of file icub.pb.cc.
internal_default_instance()
static const AllJointEncodedResponse* iCubInterfaceMessages::AllJointEncodedResponse::internal_default_instance () inline static
Definition at line 1349 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::AllJointEncodedResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 3638 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::AllJointEncodedResponse::IsInitialized () const final
Definition at line 3740 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::AllJointEncodedResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 3698 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::AllJointEncodedResponse::MergeFrom (const AllJointEncodedResponse & from)
Definition at line 3713 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::AllJointEncodedResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 3553 of file icub.pb.cc.
mutable_angle() [1/2]
google::protobuf::RepeatedPtrField<::iCubInterfaceMessages::DoubleVector > * iCubInterfaceMessages::AllJointEncodedResponse::mutable_angle () inline
Definition at line 3154 of file icub.pb.h.
mutable_angle() [2/2]
iCubInterfaceMessages::DoubleVector * iCubInterfaceMessages::AllJointEncodedResponse::mutable_angle (int index) inline
Definition at line 3149 of file icub.pb.h.
New() [1/2]
AllJointEncodedResponse* iCubInterfaceMessages::AllJointEncodedResponse::New () const inline final
Definition at line 1363 of file icub.pb.h.
New() [2/2]
AllJointEncodedResponse* iCubInterfaceMessages::AllJointEncodedResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1367 of file icub.pb.h.
operator=()
AllJointEncodedResponse& iCubInterfaceMessages::AllJointEncodedResponse::operator= (const AllJointEncodedResponse & from) inline
Definition at line 1326 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::AllJointEncodedResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 3610 of file icub.pb.cc.
set_status()
void iCubInterfaceMessages::AllJointEncodedResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 3136 of file icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status()
iCubInterfaceMessages::Status iCubInterfaceMessages::AllJointEncodedResponse::status () const inline
Definition at line 3132 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
Swap()
void iCubInterfaceMessages::AllJointEncodedResponse::Swap (AllJointEncodedResponse * other)
Definition at line 3744 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 1431 of file icub.pb.h.
swap
void swap (AllJointEncodedResponse & a, AllJointEncodedResponse & b) friend
Definition at line 1357 of file icub.pb.h.
Member Data Documentation
kAngleFieldNumber
const int iCubInterfaceMessages::AllJointEncodedResponse::kAngleFieldNumber = 2 static
Definition at line 1409 of file icub.pb.h.
kIndexInFileMessages
constexpr int iCubInterfaceMessages::AllJointEncodedResponse::kIndexInFileMessages static constexpr
Initial value:
=
    10
Definition at line 1353 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kStatusFieldNumber
const int iCubInterfaceMessages::AllJointEncodedResponse::kStatusFieldNumber = 1 static
Definition at line 1420 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc