ANNarchy iCub Interface: iCubInterfaceMessages::MultiTargetEncodedRequest Class Reference
iCubInterfaceMessages::MultiTargetEncodedRequest Class Reference
#include <icub.pb.h>
Public Member Functions
MultiTargetEncodedRequest ()
virtual ~MultiTargetEncodedRequest ()
MultiTargetEncodedRequest (const MultiTargetEncodedRequest &from)
MultiTargetEncodedRequest & operator= (const MultiTargetEncodedRequest &from)
void Swap (MultiTargetEncodedRequest *other)
MultiTargetEncodedRequest * New () const final
MultiTargetEncodedRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const MultiTargetEncodedRequest &from)
void MergeFrom (const MultiTargetEncodedRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const MultiTargetEncodedRequest & default_instance ()
static void InitAsDefaultInstance ()
static const MultiTargetEncodedRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (MultiTargetEncodedRequest &a, MultiTargetEncodedRequest &b)
Detailed Description
Definition at line 2269 of file icub.pb.h.
Constructor & Destructor Documentation
MultiTargetEncodedRequest() [1/2]
iCubInterfaceMessages::MultiTargetEncodedRequest::MultiTargetEncodedRequest ()
Definition at line 5710 of file icub.pb.cc.
~MultiTargetEncodedRequest()
iCubInterfaceMessages::MultiTargetEncodedRequest::~MultiTargetEncodedRequest () virtual
Definition at line 5727 of file icub.pb.cc.
MultiTargetEncodedRequest() [2/2]
iCubInterfaceMessages::MultiTargetEncodedRequest::MultiTargetEncodedRequest (const MultiTargetEncodedRequest & from)
Definition at line 5717 of file icub.pb.cc.
Member Function Documentation
ByteSizeLong()
size_t iCubInterfaceMessages::MultiTargetEncodedRequest::ByteSizeLong () const final
Definition at line 5811 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::MultiTargetEncodedRequest::Clear () final
Definition at line 5749 of file icub.pb.cc.
Referenced by CopyFrom().
CopyFrom() [1/2]
void iCubInterfaceMessages::MultiTargetEncodedRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 5849 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::MultiTargetEncodedRequest::CopyFrom (const MultiTargetEncodedRequest & from)
Definition at line 5856 of file icub.pb.cc.
default_instance()
const MultiTargetEncodedRequest & iCubInterfaceMessages::MultiTargetEncodedRequest::default_instance () static
Definition at line 5743 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::MultiTargetEncodedRequest::descriptor () static
Definition at line 5738 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::MultiTargetEncodedRequest::GetCachedSize () const inline final
Definition at line 2334 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::MultiTargetEncodedRequest::GetMetadata () const final
Definition at line 5876 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::MultiTargetEncodedRequest::InitAsDefaultInstance () static
Definition at line 5705 of file icub.pb.cc.
internal_default_instance()
static const MultiTargetEncodedRequest* iCubInterfaceMessages::MultiTargetEncodedRequest::internal_default_instance () inline static
Definition at line 2299 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::MultiTargetEncodedRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 5796 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::MultiTargetEncodedRequest::IsInitialized () const final
Definition at line 5863 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::MultiTargetEncodedRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 5825 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::MultiTargetEncodedRequest::MergeFrom (const MultiTargetEncodedRequest & from)
Definition at line 5840 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::MultiTargetEncodedRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 5758 of file icub.pb.cc.
New() [1/2]
MultiTargetEncodedRequest* iCubInterfaceMessages::MultiTargetEncodedRequest::New () const inline final
Definition at line 2313 of file icub.pb.h.
New() [2/2]
MultiTargetEncodedRequest* iCubInterfaceMessages::MultiTargetEncodedRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 2317 of file icub.pb.h.
operator=()
MultiTargetEncodedRequest& iCubInterfaceMessages::MultiTargetEncodedRequest::operator= (const MultiTargetEncodedRequest & from) inline
Definition at line 2276 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::MultiTargetEncodedRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 5783 of file icub.pb.cc.
Swap()
void iCubInterfaceMessages::MultiTargetEncodedRequest::Swap (MultiTargetEncodedRequest * other)
Definition at line 5867 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 2361 of file icub.pb.h.
swap
void swap (MultiTargetEncodedRequest & a, MultiTargetEncodedRequest & b) friend
Definition at line 2307 of file icub.pb.h.
Member Data Documentation
kIndexInFileMessages
constexpr int iCubInterfaceMessages::MultiTargetEncodedRequest::kIndexInFileMessages static constexpr
Initial value:
=
    19
Definition at line 2303 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc