ANNarchy iCub Interface: iCubInterfaceMessages::SingleJointEncodedRequest Class Reference
iCubInterfaceMessages::SingleJointEncodedRequest Class Reference
#include <icub.pb.h>
Public Member Functions
SingleJointEncodedRequest ()
virtual ~SingleJointEncodedRequest ()
SingleJointEncodedRequest (const SingleJointEncodedRequest &from)
SingleJointEncodedRequest & operator= (const SingleJointEncodedRequest &from)
void Swap (SingleJointEncodedRequest *other)
SingleJointEncodedRequest * New () const final
SingleJointEncodedRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SingleJointEncodedRequest &from)
void MergeFrom (const SingleJointEncodedRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_part ()
const ::std::string & part () const
void set_part (const ::std::string &value)
void set_part (const char *value)
void set_part (const char *value, size_t size)
::std::string * mutable_part ()
::std::string * release_part ()
void set_allocated_part (::std::string *part)
void clear_joint ()
::google::protobuf::int32 joint () const
void set_joint (::google::protobuf::int32 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SingleJointEncodedRequest & default_instance ()
static void InitAsDefaultInstance ()
static const SingleJointEncodedRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kPartFieldNumber = 1
static const int kJointFieldNumber = 2
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (SingleJointEncodedRequest &a, SingleJointEncodedRequest &b)
Detailed Description
Definition at line 973 of file icub.pb.h.
Constructor & Destructor Documentation
SingleJointEncodedRequest() [1/2]
iCubInterfaceMessages::SingleJointEncodedRequest::SingleJointEncodedRequest ()
Definition at line 2690 of file icub.pb.cc.
~SingleJointEncodedRequest()
iCubInterfaceMessages::SingleJointEncodedRequest::~SingleJointEncodedRequest () virtual
Definition at line 2714 of file icub.pb.cc.
SingleJointEncodedRequest() [2/2]
iCubInterfaceMessages::SingleJointEncodedRequest::SingleJointEncodedRequest (const SingleJointEncodedRequest & from)
Definition at line 2697 of file icub.pb.cc.
Member Function Documentation
ByteSizeLong()
size_t iCubInterfaceMessages::SingleJointEncodedRequest::ByteSizeLong () const final
Definition at line 2867 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::SingleJointEncodedRequest::Clear () final
Definition at line 2737 of file icub.pb.cc.
Referenced by CopyFrom().
clear_joint()
void iCubInterfaceMessages::SingleJointEncodedRequest::clear_joint () inline
Definition at line 3006 of file icub.pb.h.
clear_part()
void iCubInterfaceMessages::SingleJointEncodedRequest::clear_part () inline
Definition at line 2953 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::SingleJointEncodedRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 2926 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::SingleJointEncodedRequest::CopyFrom (const SingleJointEncodedRequest & from)
Definition at line 2933 of file icub.pb.cc.
default_instance()
const SingleJointEncodedRequest & iCubInterfaceMessages::SingleJointEncodedRequest::default_instance () static
Definition at line 2731 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::SingleJointEncodedRequest::descriptor () static
Definition at line 2726 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::SingleJointEncodedRequest::GetCachedSize () const inline final
Definition at line 1038 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::SingleJointEncodedRequest::GetMetadata () const final
Definition at line 2956 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::SingleJointEncodedRequest::InitAsDefaultInstance () static
Definition at line 2683 of file icub.pb.cc.
internal_default_instance()
static const SingleJointEncodedRequest* iCubInterfaceMessages::SingleJointEncodedRequest::internal_default_instance () inline static
Definition at line 1003 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::SingleJointEncodedRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 2836 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::SingleJointEncodedRequest::IsInitialized () const final
Definition at line 2940 of file icub.pb.cc.
joint()
google::protobuf::int32 iCubInterfaceMessages::SingleJointEncodedRequest::joint () const inline
Definition at line 3009 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
MergeFrom() [1/2]
void iCubInterfaceMessages::SingleJointEncodedRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 2895 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::SingleJointEncodedRequest::MergeFrom (const SingleJointEncodedRequest & from)
Definition at line 2910 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::SingleJointEncodedRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 2748 of file icub.pb.cc.
mutable_part()
std::string * iCubInterfaceMessages::SingleJointEncodedRequest::mutable_part () inline
Definition at line 2985 of file icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/2]
SingleJointEncodedRequest* iCubInterfaceMessages::SingleJointEncodedRequest::New () const inline final
Definition at line 1017 of file icub.pb.h.
New() [2/2]
SingleJointEncodedRequest* iCubInterfaceMessages::SingleJointEncodedRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1021 of file icub.pb.h.
operator=()
SingleJointEncodedRequest& iCubInterfaceMessages::SingleJointEncodedRequest::operator= (const SingleJointEncodedRequest & from) inline
Definition at line 980 of file icub.pb.h.
part()
const ::std::string & iCubInterfaceMessages::SingleJointEncodedRequest::part () const inline
Definition at line 2956 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), and SingleJointEncodedRequest().
release_part()
std::string * iCubInterfaceMessages::SingleJointEncodedRequest::release_part () inline
Definition at line 2990 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::SingleJointEncodedRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 2808 of file icub.pb.cc.
set_allocated_part()
void iCubInterfaceMessages::SingleJointEncodedRequest::set_allocated_part (::std::string * part) inline
Definition at line 2995 of file icub.pb.h.
set_joint()
void iCubInterfaceMessages::SingleJointEncodedRequest::set_joint (::google::protobuf::int32 value) inline
Definition at line 3013 of file icub.pb.h.
Referenced by MergeFrom().
set_part() [1/3]
void iCubInterfaceMessages::SingleJointEncodedRequest::set_part (const ::std::string & value) inline
Definition at line 2960 of file icub.pb.h.
set_part() [2/3]
void iCubInterfaceMessages::SingleJointEncodedRequest::set_part (const char * value) inline
Definition at line 2973 of file icub.pb.h.
set_part() [3/3]
void iCubInterfaceMessages::SingleJointEncodedRequest::set_part (const char * value, size_t size) inline
Definition at line 2979 of file icub.pb.h.
Swap()
void iCubInterfaceMessages::SingleJointEncodedRequest::Swap (SingleJointEncodedRequest * other)
Definition at line 2944 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 1087 of file icub.pb.h.
swap
void swap (SingleJointEncodedRequest & a, SingleJointEncodedRequest & b) friend
Definition at line 1011 of file icub.pb.h.
Member Data Documentation
kIndexInFileMessages
constexpr int iCubInterfaceMessages::SingleJointEncodedRequest::kIndexInFileMessages static constexpr
Initial value:
=
    7
Definition at line 1007 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kJointFieldNumber
const int iCubInterfaceMessages::SingleJointEncodedRequest::kJointFieldNumber = 2 static
Definition at line 1076 of file icub.pb.h.
kPartFieldNumber
const int iCubInterfaceMessages::SingleJointEncodedRequest::kPartFieldNumber = 1 static
Definition at line 1062 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc