ANNarchy iCub Interface: supplementary.auxilary_methods Namespace Reference
supplementary.auxilary_methods Namespace Reference
Functions
def normal_pdf (value, mean, sigma)
auxilary methods ###################
def encode (part, joint, pop_size, joint_angle, sigma, resolution=0.0, relative=False)
Detailed Description
Created on Thu Jul 9 20:05:53 CEST 2020
@author: tofo
auxilary methods for interface testing
Function Documentation
encode()
def supplementary.auxilary_methods.encode (part, joint, pop_size, joint_angle, sigma, resolution = 0.0, relative = False)
    Encode a joint angle as double value in a population code.
    params:
        part            -- robot part
        joint           -- joint number
        pop_size        -- size of the population
        joint_angle     -- joint angle read from the robot
        sigma           -- sigma for population coding gaussian
        resolution      -- if non-zero fixed resolution for all joints instead of fixed population size
    return:
                        -- population encoded joint angle
Referenced by simple_call_test.call_test_jwriter(), auto_test.rel_pos_pop(), performance_test.speed_test_jwriter(), and auto_test.test_joint_positioning().
normal_pdf()
def supplementary.auxilary_methods.normal_pdf (value, mean, sigma)
auxilary methods ###################
    Return the function value of a normal distribution for a given value.
    params:
        value           -- value to calculate normal distribution at
        mean            -- mean of the normal distribution
        sigma           -- sigma of the normal distribution
    return:
                        -- function value for the normal distribution
Referenced by supplementary.auxilary_methods.encode().