ANNarchy iCub Interface: iCubInterfaceMessages::MultiJointResponse Class Reference
iCubInterfaceMessages::MultiJointResponse Class Reference
#include <icub.pb.h>
Public Member Functions
MultiJointResponse ()
virtual ~MultiJointResponse ()
MultiJointResponse (const MultiJointResponse &from)
MultiJointResponse & operator= (const MultiJointResponse &from)
void Swap (MultiJointResponse *other)
MultiJointResponse * New () const final
MultiJointResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const MultiJointResponse &from)
void MergeFrom (const MultiJointResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const MultiJointResponse & default_instance ()
static void InitAsDefaultInstance ()
static const MultiJointResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kAngleFieldNumber = 2
static const int kStatusFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (MultiJointResponse &a, MultiJointResponse &b)
Detailed Description
Definition at line 1073 of file icub.pb.h.
Constructor & Destructor Documentation
MultiJointResponse() [1/2]
iCubInterfaceMessages::MultiJointResponse::MultiJointResponse ()
Definition at line 2987 of file icub.pb.cc.
~MultiJointResponse()
iCubInterfaceMessages::MultiJointResponse::~MultiJointResponse () virtual
Definition at line 3007 of file icub.pb.cc.
MultiJointResponse() [2/2]
iCubInterfaceMessages::MultiJointResponse::MultiJointResponse (const MultiJointResponse & from)
Definition at line 2994 of file icub.pb.cc.
Member Function Documentation
add_angle()
void iCubInterfaceMessages::MultiJointResponse::add_angle (double value) inline
Definition at line 3515 of file icub.pb.h.
angle() [1/2]
const ::google::protobuf::RepeatedField< double > & iCubInterfaceMessages::MultiJointResponse::angle () const inline
Definition at line 3520 of file icub.pb.h.
Referenced by SerializeWithCachedSizes().
angle() [2/2]
double iCubInterfaceMessages::MultiJointResponse::angle (int index) const inline
Definition at line 3507 of file icub.pb.h.
Referenced by ClientInstance::retrieve_multijoints().
angle_size()
int iCubInterfaceMessages::MultiJointResponse::angle_size () const inline
Definition at line 3501 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
ByteSizeLong()
size_t iCubInterfaceMessages::MultiJointResponse::ByteSizeLong () const final
Definition at line 3166 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::MultiJointResponse::Clear () final
Definition at line 3029 of file icub.pb.cc.
Referenced by CopyFrom().
clear_angle()
void iCubInterfaceMessages::MultiJointResponse::clear_angle () inline
Definition at line 3504 of file icub.pb.h.
clear_status()
void iCubInterfaceMessages::MultiJointResponse::clear_status () inline
Definition at line 3487 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::MultiJointResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 3230 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::MultiJointResponse::CopyFrom (const MultiJointResponse & from)
Definition at line 3237 of file icub.pb.cc.
default_instance()
const MultiJointResponse & iCubInterfaceMessages::MultiJointResponse::default_instance () static
Definition at line 3023 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::MultiJointResponse::descriptor () static
Definition at line 3018 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::MultiJointResponse::GetCachedSize () const inline final
Definition at line 1138 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::MultiJointResponse::GetMetadata () const final
Definition at line 3259 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::MultiJointResponse::InitAsDefaultInstance () static
Definition at line 2980 of file icub.pb.cc.
internal_default_instance()
static const MultiJointResponse* iCubInterfaceMessages::MultiJointResponse::internal_default_instance () inline static
Definition at line 1103 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::MultiJointResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 3132 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::MultiJointResponse::IsInitialized () const final
Definition at line 3244 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::MultiJointResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 3202 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::MultiJointResponse::MergeFrom (const MultiJointResponse & from)
Definition at line 3217 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::MultiJointResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 3040 of file icub.pb.cc.
mutable_angle()
google::protobuf::RepeatedField< double > * iCubInterfaceMessages::MultiJointResponse::mutable_angle () inline
Definition at line 3525 of file icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/2]
MultiJointResponse* iCubInterfaceMessages::MultiJointResponse::New () const inline final
Definition at line 1117 of file icub.pb.h.
New() [2/2]
MultiJointResponse* iCubInterfaceMessages::MultiJointResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1121 of file icub.pb.h.
operator=()
MultiJointResponse& iCubInterfaceMessages::MultiJointResponse::operator= (const MultiJointResponse & from) inline
Definition at line 1080 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::MultiJointResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 3104 of file icub.pb.cc.
set_angle()
void iCubInterfaceMessages::MultiJointResponse::set_angle (int index, double value) inline
Definition at line 3511 of file icub.pb.h.
set_status()
void iCubInterfaceMessages::MultiJointResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 3494 of file icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status()
iCubInterfaceMessages::Status iCubInterfaceMessages::MultiJointResponse::status () const inline
Definition at line 3490 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
Swap()
void iCubInterfaceMessages::MultiJointResponse::Swap (MultiJointResponse * other)
Definition at line 3248 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 1186 of file icub.pb.h.
swap
void swap (MultiJointResponse & a, MultiJointResponse & b) friend
Definition at line 1111 of file icub.pb.h.
Member Data Documentation
kAngleFieldNumber
const int iCubInterfaceMessages::MultiJointResponse::kAngleFieldNumber = 2 static
Definition at line 1163 of file icub.pb.h.
kIndexInFileMessages
constexpr int iCubInterfaceMessages::MultiJointResponse::kIndexInFileMessages static constexpr
Initial value:
=
    8
Definition at line 1107 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kStatusFieldNumber
const int iCubInterfaceMessages::MultiJointResponse::kStatusFieldNumber = 1 static
Definition at line 1174 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc