ANNarchy iCub Interface: iCubInterfaceMessages::AllTargetResponse Class Reference
iCubInterfaceMessages::AllTargetResponse Class Reference
#include <icub.pb.h>
Public Member Functions
AllTargetResponse ()
virtual ~AllTargetResponse ()
AllTargetResponse (const AllTargetResponse &from)
AllTargetResponse & operator= (const AllTargetResponse &from)
void Swap (AllTargetResponse *other)
AllTargetResponse * New () const final
AllTargetResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const AllTargetResponse &from)
void MergeFrom (const AllTargetResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
AllTargetResponse ()
virtual ~AllTargetResponse ()
AllTargetResponse (const AllTargetResponse &from)
AllTargetResponse & operator= (const AllTargetResponse &from)
void Swap (AllTargetResponse *other)
AllTargetResponse * New () const final
AllTargetResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const AllTargetResponse &from)
void MergeFrom (const AllTargetResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const AllTargetResponse & default_instance ()
static void InitAsDefaultInstance ()
static const AllTargetResponse * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const AllTargetResponse & default_instance ()
static void InitAsDefaultInstance ()
static const AllTargetResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kAngleFieldNumber = 2
static const int kStatusFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (AllTargetResponse &a, AllTargetResponse &b)
void swap (AllTargetResponse &a, AllTargetResponse &b)
Detailed Description
Definition at line 1932 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
AllTargetResponse() [1/4]
iCubInterfaceMessages::AllTargetResponse::AllTargetResponse ()
Definition at line 4915 of file icub.pb.cc.
~AllTargetResponse() [1/2]
iCubInterfaceMessages::AllTargetResponse::~AllTargetResponse () virtual
Definition at line 4935 of file icub.pb.cc.
AllTargetResponse() [2/4]
iCubInterfaceMessages::AllTargetResponse::AllTargetResponse (const AllTargetResponse & from)
Definition at line 4922 of file icub.pb.cc.
AllTargetResponse() [3/4]
iCubInterfaceMessages::AllTargetResponse::AllTargetResponse ()
~AllTargetResponse() [2/2]
virtual iCubInterfaceMessages::AllTargetResponse::~AllTargetResponse () virtual
AllTargetResponse() [4/4]
iCubInterfaceMessages::AllTargetResponse::AllTargetResponse (const AllTargetResponse & from)
Member Function Documentation
add_angle() [1/2]
void iCubInterfaceMessages::AllTargetResponse::add_angle (double value) inline
Definition at line 3735 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
add_angle() [2/2]
void iCubInterfaceMessages::AllTargetResponse::add_angle (double value)
angle() [1/4]
const ::google::protobuf::RepeatedField< double > & iCubInterfaceMessages::AllTargetResponse::angle () const inline
Definition at line 3740 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by SerializeWithCachedSizes().
angle() [2/4]
const ::google::protobuf::RepeatedField< double >& iCubInterfaceMessages::AllTargetResponse::angle () const
angle() [3/4]
double iCubInterfaceMessages::AllTargetResponse::angle (int index) const inline
Definition at line 3727 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by WriteClientInstance::retrieve_alltarget().
angle() [4/4]
double iCubInterfaceMessages::AllTargetResponse::angle (int index) const
angle_size() [1/2]
int iCubInterfaceMessages::AllTargetResponse::angle_size () const inline
Definition at line 3721 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
angle_size() [2/2]
int iCubInterfaceMessages::AllTargetResponse::angle_size () const
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::AllTargetResponse::ByteSizeLong () const final
Definition at line 5094 of file icub.pb.cc.
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::AllTargetResponse::ByteSizeLong () const final
Clear() [1/2]
void iCubInterfaceMessages::AllTargetResponse::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::AllTargetResponse::Clear () final
Definition at line 4957 of file icub.pb.cc.
Referenced by CopyFrom().
clear_angle() [1/2]
void iCubInterfaceMessages::AllTargetResponse::clear_angle () inline
Definition at line 3724 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_angle() [2/2]
void iCubInterfaceMessages::AllTargetResponse::clear_angle ()
clear_status() [1/2]
void iCubInterfaceMessages::AllTargetResponse::clear_status () inline
Definition at line 3707 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_status() [2/2]
void iCubInterfaceMessages::AllTargetResponse::clear_status ()
CopyFrom() [1/4]
void iCubInterfaceMessages::AllTargetResponse::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/4]
void iCubInterfaceMessages::AllTargetResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 5158 of file icub.pb.cc.
CopyFrom() [3/4]
void iCubInterfaceMessages::AllTargetResponse::CopyFrom (const AllTargetResponse & from)
CopyFrom() [4/4]
void iCubInterfaceMessages::AllTargetResponse::CopyFrom (const AllTargetResponse & from)
Definition at line 5165 of file icub.pb.cc.
default_instance() [1/2]
static const AllTargetResponse& iCubInterfaceMessages::AllTargetResponse::default_instance () static
default_instance() [2/2]
const AllTargetResponse & iCubInterfaceMessages::AllTargetResponse::default_instance () static
Definition at line 4951 of file icub.pb.cc.
descriptor() [1/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::AllTargetResponse::descriptor () static
descriptor() [2/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::AllTargetResponse::descriptor () static
Definition at line 4946 of file icub.pb.cc.
GetCachedSize() [1/2]
int iCubInterfaceMessages::AllTargetResponse::GetCachedSize () const inline final
Definition at line 1997 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::AllTargetResponse::GetCachedSize () const inline final
Definition at line 1997 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
google::protobuf::Metadata iCubInterfaceMessages::AllTargetResponse::GetMetadata () const final
Definition at line 5187 of file icub.pb.cc.
GetMetadata() [2/2]
::google::protobuf::Metadata iCubInterfaceMessages::AllTargetResponse::GetMetadata () const final
InitAsDefaultInstance() [1/2]
static void iCubInterfaceMessages::AllTargetResponse::InitAsDefaultInstance () static
InitAsDefaultInstance() [2/2]
void iCubInterfaceMessages::AllTargetResponse::InitAsDefaultInstance () static
Definition at line 4908 of file icub.pb.cc.
internal_default_instance() [1/2]
static const AllTargetResponse* iCubInterfaceMessages::AllTargetResponse::internal_default_instance () inline static
Definition at line 1962 of file iCub_ANN_Interface/grpc/icub.pb.h.
internal_default_instance() [2/2]
static const AllTargetResponse* iCubInterfaceMessages::AllTargetResponse::internal_default_instance () inline static
Definition at line 1962 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::AllTargetResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 5060 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::AllTargetResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::AllTargetResponse::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::AllTargetResponse::IsInitialized () const final
Definition at line 5172 of file icub.pb.cc.
MergeFrom() [1/4]
void iCubInterfaceMessages::AllTargetResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 5130 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/4]
void iCubInterfaceMessages::AllTargetResponse::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [3/4]
void iCubInterfaceMessages::AllTargetResponse::MergeFrom (const AllTargetResponse & from)
MergeFrom() [4/4]
void iCubInterfaceMessages::AllTargetResponse::MergeFrom (const AllTargetResponse & from)
Definition at line 5145 of file icub.pb.cc.
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::AllTargetResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 4968 of file icub.pb.cc.
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::AllTargetResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_angle() [1/2]
::google::protobuf::RepeatedField< double >* iCubInterfaceMessages::AllTargetResponse::mutable_angle ()
mutable_angle() [2/2]
google::protobuf::RepeatedField< double > * iCubInterfaceMessages::AllTargetResponse::mutable_angle () inline
Definition at line 3745 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/4]
AllTargetResponse* iCubInterfaceMessages::AllTargetResponse::New () const inline final
Definition at line 1976 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
AllTargetResponse* iCubInterfaceMessages::AllTargetResponse::New () const inline final
Definition at line 1976 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
AllTargetResponse* iCubInterfaceMessages::AllTargetResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1980 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
AllTargetResponse* iCubInterfaceMessages::AllTargetResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1980 of file iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
AllTargetResponse& iCubInterfaceMessages::AllTargetResponse::operator= (const AllTargetResponse & from) inline
Definition at line 1939 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
AllTargetResponse& iCubInterfaceMessages::AllTargetResponse::operator= (const AllTargetResponse & from) inline
Definition at line 1939 of file iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::AllTargetResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 5032 of file icub.pb.cc.
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::AllTargetResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_angle() [1/2]
void iCubInterfaceMessages::AllTargetResponse::set_angle (int index, double value)
set_angle() [2/2]
void iCubInterfaceMessages::AllTargetResponse::set_angle (int index, double value) inline
Definition at line 3731 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
set_status() [1/2]
void iCubInterfaceMessages::AllTargetResponse::set_status (::iCubInterfaceMessages::Status value)
set_status() [2/2]
void iCubInterfaceMessages::AllTargetResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 3714 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status() [1/2]
iCubInterfaceMessages::Status iCubInterfaceMessages::AllTargetResponse::status () const inline
Definition at line 3710 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
status() [2/2]
::iCubInterfaceMessages::Status iCubInterfaceMessages::AllTargetResponse::status () const
Swap() [1/2]
void iCubInterfaceMessages::AllTargetResponse::Swap (AllTargetResponse * other)
Definition at line 5176 of file icub.pb.cc.
Swap() [2/2]
void iCubInterfaceMessages::AllTargetResponse::Swap (AllTargetResponse * other)
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 2045 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (AllTargetResponse & a, AllTargetResponse & b) friend
Definition at line 1970 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (AllTargetResponse & a, AllTargetResponse & b) friend
Definition at line 1970 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kAngleFieldNumber
static const int iCubInterfaceMessages::AllTargetResponse::kAngleFieldNumber = 2 static
Definition at line 2022 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::AllTargetResponse::kIndexInFileMessages static constexpr
Initial value:
=
    16
Definition at line 1966 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kStatusFieldNumber
static const int iCubInterfaceMessages::AllTargetResponse::kStatusFieldNumber = 1 static
Definition at line 2033 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc