from typing import Any

textToList: cython_function_or_method

class ANNiCub_wrapper:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def clear(self) -> Any: ...
    def get_jreader_by_name(self, unicodename) -> PyJointReader: ...
    def get_jreader_by_part(self, unicodepart) -> PyJointReader: ...
    def get_jwriter_by_name(self, unicodename) -> PyJointWriter: ...
    def get_jwriter_by_part(self, unicodepart) -> PyJointWriter: ...
    def get_skinreader_by_name(self, unicodename) -> PySkinReader: ...
    def get_vis_reader_by_name(self, unicodename) -> PyVisualReader: ...
    def init_robot_from_file(self, xml_file) -> Any: ...
    def register_jreader(self, unicodename, PyJointReadermodule) -> Any: ...
    def register_jwriter(self, unicodename, PyJointWritermodule) -> Any: ...
    def register_kin_reader(self, unicodename, PyKinematicReadermodule) -> Any: ...
    def register_kin_writer(self, unicodename, PyKinematicWritermodule) -> Any: ...
    def register_skin_reader(self, unicodename, PySkinReadermodule) -> Any: ...
    def register_vis_reader(self, unicodename, PyVisualReadermodule) -> Any: ...
    def save_robot_to_file(self, xml_file, description = ...) -> Any: ...
    def unregister_jreader(self, PyJointReadermodule) -> Any: ...
    def unregister_jwriter(self, PyJointWritermodule) -> Any: ...
    def unregister_kin_reader(self, PyKinematicReadermodule) -> Any: ...
    def unregister_kin_writer(self, PyKinematicWritermodule) -> Any: ...
    def unregister_skin_reader(self, PySkinReadermodule) -> Any: ...
    def unregister_vis_reader(self, PyVisualReadermodule) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...
