from typing import Any

class PyJointReader:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def close(self, ANNiCub_wrapperiCub) -> Any: ...
    def get_joint_count(self) -> Any: ...
    def get_joints_deg_res(self) -> Any: ...
    def get_neurons_per_joint(self) -> Any: ...
    def init(self, ANNiCub_wrapperiCub, unicodename, unicodepart, doublesigma, unsignedintn_pop, doubledegr_per_neuron = ..., unicodeini_path = ...) -> Any: ...
    def init_grpc(self, ANNiCub_wrapperiCub, unicodename, unicodepart, doublesigma, unsignedintn_pop, doubledegr_per_neuron = ..., unicodeini_path = ..., unicodeip_address = ..., unsignedintport = ...) -> Any: ...
    def read_double_all(self) -> Any: ...
    def read_double_multiple(self, joints) -> Any: ...
    def read_double_one(self, intjoint) -> Any: ...
    def read_pop_all(self) -> Any: ...
    def read_pop_multiple(self, joints) -> Any: ...
    def read_pop_one(self, intjoint) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...
