from typing import Any

class PyKinematicReader:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def block_links(self, blocked_joints) -> Any: ...
    def close(self, ANNiCub_wrapperiCub) -> Any: ...
    def get_DOF(self) -> Any: ...
    def get_DOF_links(self) -> Any: ...
    def get_blocked_links(self) -> Any: ...
    def get_handposition(self) -> Any: ...
    def get_jointangles(self) -> Any: ...
    def get_jointposition(self, unsignedintjoint) -> Any: ...
    def init(self, ANNiCub_wrapperiCub, unicodename, unicodepart, floatversion, unicodeini_path = ..., offline_mode = ...) -> Any: ...
    def init_grpc(self, ANNiCub_wrapperiCub, unicodename, unicodepart, floatversion, unicodeini_path = ..., unicodeip_address = ..., unsignedintport = ..., offline_mode = ...) -> Any: ...
    def release_links(self, release_joints) -> Any: ...
    def set_jointangles(self, joint_angles) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...
