from typing import Any

class PyKinematicWriter:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def close(self, ANNiCub_wrapperiCub) -> Any: ...
    def get_DOF(self) -> Any: ...
    def init(self, ANNiCub_wrapperiCub, unicodename, unicodepart, floatversion, unicodeini_path = ...) -> Any: ...
    def init_grpc(self, ANNiCub_wrapperiCub, unicodename, unicodepart, floatversion, unicodeini_path = ..., unicodeip_address = ..., unsignedintport = ...) -> Any: ...
    def solve_InvKin(self, position, blocked_links) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...
