from typing import Any

class PySkinReader:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def close(self, ANNiCub_wrapperiCub) -> Any: ...
    def get_tactile_arm(self) -> Any: ...
    def get_tactile_arm_size(self) -> Any: ...
    def get_tactile_forearm(self) -> Any: ...
    def get_tactile_forearm_size(self) -> Any: ...
    def get_tactile_hand(self) -> Any: ...
    def get_tactile_hand_size(self) -> Any: ...
    def get_taxel_pos(self, unicodeskin_part) -> Any: ...
    def init(self, ANNiCub_wrapperiCub, unicodename, unicodearm, norm = ..., unicodeini_path = ...) -> Any: ...
    def init_grpc(self, ANNiCub_wrapperiCub, unicodename, unicodearm, norm = ..., unicodeini_path = ..., unicodeip_address = ..., unsignedintport = ...) -> Any: ...
    def read_tactile(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...
