from typing import Any

class PyVisualReader:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def close(self, ANNiCub_wrapperiCub) -> Any: ...
    def init(self, ANNiCub_wrapperiCub, unicodename, unicodeeye, doublefov_width = ..., doublefov_height = ..., intimg_width = ..., intimg_height = ..., fast_filter = ..., unicodeini_path = ...) -> Any: ...
    def init_grpc(self, ANNiCub_wrapperiCub, unicodename, unicodeeye, doublefov_width = ..., doublefov_height = ..., intimg_width = ..., intimg_height = ..., fast_filter = ..., unicodeini_path = ..., unicodeip_address = ..., unsignedintport = ...) -> Any: ...
    def read_robot_eyes(self) -> Any: ...
    def retrieve_robot_eye(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...
