ANNarchy iCub Interface: iCubInterfaceMessages::ImageRequest Class Reference
iCubInterfaceMessages::ImageRequest Class Reference
#include <icub.pb.h>
Public Member Functions
ImageRequest ()
virtual ~ImageRequest ()
ImageRequest (const ImageRequest &from)
ImageRequest & operator= (const ImageRequest &from)
void Swap (ImageRequest *other)
ImageRequest * New () const final
ImageRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const ImageRequest &from)
void MergeFrom (const ImageRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_eye ()
const ::std::string & eye () const
void set_eye (const ::std::string &value)
void set_eye (const char *value)
void set_eye (const char *value, size_t size)
::std::string * mutable_eye ()
::std::string * release_eye ()
void set_allocated_eye (::std::string *eye)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const ImageRequest & default_instance ()
static void InitAsDefaultInstance ()
static const ImageRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kEyeFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (ImageRequest &a, ImageRequest &b)
Detailed Description
Definition at line 275 of file icub.pb.h.
Constructor & Destructor Documentation
ImageRequest() [1/2]
iCubInterfaceMessages::ImageRequest::ImageRequest ()
Definition at line 1023 of file icub.pb.cc.
~ImageRequest()
iCubInterfaceMessages::ImageRequest::~ImageRequest () virtual
Definition at line 1045 of file icub.pb.cc.
ImageRequest() [2/2]
iCubInterfaceMessages::ImageRequest::ImageRequest (const ImageRequest & from)
Definition at line 1030 of file icub.pb.cc.
Member Function Documentation
ByteSizeLong()
size_t iCubInterfaceMessages::ImageRequest::ByteSizeLong () const final
Definition at line 1173 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::ImageRequest::Clear () final
Definition at line 1068 of file icub.pb.cc.
Referenced by CopyFrom().
clear_eye()
void iCubInterfaceMessages::ImageRequest::clear_eye () inline
Definition at line 2610 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::ImageRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 1222 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::ImageRequest::CopyFrom (const ImageRequest & from)
Definition at line 1229 of file icub.pb.cc.
default_instance()
const ImageRequest & iCubInterfaceMessages::ImageRequest::default_instance () static
Definition at line 1062 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::ImageRequest::descriptor () static
Definition at line 1057 of file icub.pb.cc.
eye()
const ::std::string & iCubInterfaceMessages::ImageRequest::eye () const inline
Definition at line 2613 of file icub.pb.h.
Referenced by ByteSizeLong(), ImageRequest(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), and SerializeWithCachedSizes().
GetCachedSize()
int iCubInterfaceMessages::ImageRequest::GetCachedSize () const inline final
Definition at line 340 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::ImageRequest::GetMetadata () const final
Definition at line 1251 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::ImageRequest::InitAsDefaultInstance () static
Definition at line 1017 of file icub.pb.cc.
internal_default_instance()
static const ImageRequest* iCubInterfaceMessages::ImageRequest::internal_default_instance () inline static
Definition at line 305 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::ImageRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 1147 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::ImageRequest::IsInitialized () const final
Definition at line 1236 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::ImageRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 1194 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::ImageRequest::MergeFrom (const ImageRequest & from)
Definition at line 1209 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::ImageRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 1078 of file icub.pb.cc.
mutable_eye()
std::string * iCubInterfaceMessages::ImageRequest::mutable_eye () inline
Definition at line 2642 of file icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/2]
ImageRequest* iCubInterfaceMessages::ImageRequest::New () const inline final
Definition at line 319 of file icub.pb.h.
New() [2/2]
ImageRequest* iCubInterfaceMessages::ImageRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 323 of file icub.pb.h.
operator=()
ImageRequest& iCubInterfaceMessages::ImageRequest::operator= (const ImageRequest & from) inline
Definition at line 282 of file icub.pb.h.
release_eye()
std::string * iCubInterfaceMessages::ImageRequest::release_eye () inline
Definition at line 2647 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::ImageRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 1124 of file icub.pb.cc.
set_allocated_eye()
void iCubInterfaceMessages::ImageRequest::set_allocated_eye (::std::string * eye) inline
Definition at line 2652 of file icub.pb.h.
set_eye() [1/3]
void iCubInterfaceMessages::ImageRequest::set_eye (const ::std::string & value) inline
Definition at line 2617 of file icub.pb.h.
set_eye() [2/3]
void iCubInterfaceMessages::ImageRequest::set_eye (const char * value) inline
Definition at line 2630 of file icub.pb.h.
set_eye() [3/3]
void iCubInterfaceMessages::ImageRequest::set_eye (const char * value, size_t size) inline
Definition at line 2636 of file icub.pb.h.
Swap()
void iCubInterfaceMessages::ImageRequest::Swap (ImageRequest * other)
Definition at line 1240 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 382 of file icub.pb.h.
swap
void swap (ImageRequest & a, ImageRequest & b) friend
Definition at line 313 of file icub.pb.h.
Member Data Documentation
kEyeFieldNumber
const int iCubInterfaceMessages::ImageRequest::kEyeFieldNumber = 1 static
Definition at line 364 of file icub.pb.h.
kIndexInFileMessages
constexpr int iCubInterfaceMessages::ImageRequest::kIndexInFileMessages static constexpr
Initial value:
=
    1
Definition at line 309 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc