ANNarchy iCub Interface: iCubInterfaceMessages::SingleJointRequest Class Reference
iCubInterfaceMessages::SingleJointRequest Class Reference
#include <icub.pb.h>
Public Member Functions
SingleJointRequest ()
virtual ~SingleJointRequest ()
SingleJointRequest (const SingleJointRequest &from)
SingleJointRequest & operator= (const SingleJointRequest &from)
void Swap (SingleJointRequest *other)
SingleJointRequest * New () const final
SingleJointRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SingleJointRequest &from)
void MergeFrom (const SingleJointRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_part ()
const ::std::string & part () const
void set_part (const ::std::string &value)
void set_part (const char *value)
void set_part (const char *value, size_t size)
::std::string * mutable_part ()
::std::string * release_part ()
void set_allocated_part (::std::string *part)
void clear_joint ()
::google::protobuf::int32 joint () const
void set_joint (::google::protobuf::int32 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SingleJointRequest & default_instance ()
static void InitAsDefaultInstance ()
static const SingleJointRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kPartFieldNumber = 1
static const int kJointFieldNumber = 2
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (SingleJointRequest &a, SingleJointRequest &b)
Detailed Description
Definition at line 517 of file icub.pb.h.
Constructor & Destructor Documentation
SingleJointRequest() [1/2]
iCubInterfaceMessages::SingleJointRequest::SingleJointRequest ()
Definition at line 1615 of file icub.pb.cc.
~SingleJointRequest()
iCubInterfaceMessages::SingleJointRequest::~SingleJointRequest () virtual
Definition at line 1639 of file icub.pb.cc.
SingleJointRequest() [2/2]
iCubInterfaceMessages::SingleJointRequest::SingleJointRequest (const SingleJointRequest & from)
Definition at line 1622 of file icub.pb.cc.
Member Function Documentation
ByteSizeLong()
size_t iCubInterfaceMessages::SingleJointRequest::ByteSizeLong () const final
Definition at line 1792 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::SingleJointRequest::Clear () final
Definition at line 1662 of file icub.pb.cc.
Referenced by CopyFrom().
clear_joint()
void iCubInterfaceMessages::SingleJointRequest::clear_joint () inline
Definition at line 2798 of file icub.pb.h.
clear_part()
void iCubInterfaceMessages::SingleJointRequest::clear_part () inline
Definition at line 2745 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::SingleJointRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 1851 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::SingleJointRequest::CopyFrom (const SingleJointRequest & from)
Definition at line 1858 of file icub.pb.cc.
default_instance()
const SingleJointRequest & iCubInterfaceMessages::SingleJointRequest::default_instance () static
Definition at line 1656 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::SingleJointRequest::descriptor () static
Definition at line 1651 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::SingleJointRequest::GetCachedSize () const inline final
Definition at line 582 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::SingleJointRequest::GetMetadata () const final
Definition at line 1881 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::SingleJointRequest::InitAsDefaultInstance () static
Definition at line 1608 of file icub.pb.cc.
internal_default_instance()
static const SingleJointRequest* iCubInterfaceMessages::SingleJointRequest::internal_default_instance () inline static
Definition at line 547 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::SingleJointRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 1761 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::SingleJointRequest::IsInitialized () const final
Definition at line 1865 of file icub.pb.cc.
joint()
google::protobuf::int32 iCubInterfaceMessages::SingleJointRequest::joint () const inline
Definition at line 2801 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
MergeFrom() [1/2]
void iCubInterfaceMessages::SingleJointRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 1820 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::SingleJointRequest::MergeFrom (const SingleJointRequest & from)
Definition at line 1835 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::SingleJointRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 1673 of file icub.pb.cc.
mutable_part()
std::string * iCubInterfaceMessages::SingleJointRequest::mutable_part () inline
Definition at line 2777 of file icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/2]
SingleJointRequest* iCubInterfaceMessages::SingleJointRequest::New () const inline final
Definition at line 561 of file icub.pb.h.
New() [2/2]
SingleJointRequest* iCubInterfaceMessages::SingleJointRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 565 of file icub.pb.h.
operator=()
SingleJointRequest& iCubInterfaceMessages::SingleJointRequest::operator= (const SingleJointRequest & from) inline
Definition at line 524 of file icub.pb.h.
part()
const ::std::string & iCubInterfaceMessages::SingleJointRequest::part () const inline
Definition at line 2748 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), and SingleJointRequest().
release_part()
std::string * iCubInterfaceMessages::SingleJointRequest::release_part () inline
Definition at line 2782 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::SingleJointRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 1733 of file icub.pb.cc.
set_allocated_part()
void iCubInterfaceMessages::SingleJointRequest::set_allocated_part (::std::string * part) inline
Definition at line 2787 of file icub.pb.h.
set_joint()
void iCubInterfaceMessages::SingleJointRequest::set_joint (::google::protobuf::int32 value) inline
Definition at line 2805 of file icub.pb.h.
Referenced by MergeFrom().
set_part() [1/3]
void iCubInterfaceMessages::SingleJointRequest::set_part (const ::std::string & value) inline
Definition at line 2752 of file icub.pb.h.
set_part() [2/3]
void iCubInterfaceMessages::SingleJointRequest::set_part (const char * value) inline
Definition at line 2765 of file icub.pb.h.
set_part() [3/3]
void iCubInterfaceMessages::SingleJointRequest::set_part (const char * value, size_t size) inline
Definition at line 2771 of file icub.pb.h.
Swap()
void iCubInterfaceMessages::SingleJointRequest::Swap (SingleJointRequest * other)
Definition at line 1869 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 631 of file icub.pb.h.
swap
void swap (SingleJointRequest & a, SingleJointRequest & b) friend
Definition at line 555 of file icub.pb.h.
Member Data Documentation
kIndexInFileMessages
constexpr int iCubInterfaceMessages::SingleJointRequest::kIndexInFileMessages static constexpr
Initial value:
=
    3
Definition at line 551 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kJointFieldNumber
const int iCubInterfaceMessages::SingleJointRequest::kJointFieldNumber = 2 static
Definition at line 620 of file icub.pb.h.
kPartFieldNumber
const int iCubInterfaceMessages::SingleJointRequest::kPartFieldNumber = 1 static
Definition at line 606 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc