ANNarchy iCub Interface: iCubInterfaceMessages::SingleJointEncodedResponse Class Reference
iCubInterfaceMessages::SingleJointEncodedResponse Class Reference
#include <icub.pb.h>
Public Member Functions
SingleJointEncodedResponse ()
virtual ~SingleJointEncodedResponse ()
SingleJointEncodedResponse (const SingleJointEncodedResponse &from)
SingleJointEncodedResponse & operator= (const SingleJointEncodedResponse &from)
void Swap (SingleJointEncodedResponse *other)
SingleJointEncodedResponse * New () const final
SingleJointEncodedResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SingleJointEncodedResponse &from)
void MergeFrom (const SingleJointEncodedResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SingleJointEncodedResponse & default_instance ()
static void InitAsDefaultInstance ()
static const SingleJointEncodedResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kAngleFieldNumber = 2
static const int kStatusFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (SingleJointEncodedResponse &a, SingleJointEncodedResponse &b)
Detailed Description
Definition at line 1091 of file icub.pb.h.
Constructor & Destructor Documentation
SingleJointEncodedResponse() [1/2]
iCubInterfaceMessages::SingleJointEncodedResponse::SingleJointEncodedResponse ()
Definition at line 2971 of file icub.pb.cc.
~SingleJointEncodedResponse()
iCubInterfaceMessages::SingleJointEncodedResponse::~SingleJointEncodedResponse () virtual
Definition at line 2991 of file icub.pb.cc.
SingleJointEncodedResponse() [2/2]
iCubInterfaceMessages::SingleJointEncodedResponse::SingleJointEncodedResponse (const SingleJointEncodedResponse & from)
Definition at line 2978 of file icub.pb.cc.
Member Function Documentation
add_angle()
void iCubInterfaceMessages::SingleJointEncodedResponse::add_angle (double value) inline
Definition at line 3052 of file icub.pb.h.
angle() [1/2]
const ::google::protobuf::RepeatedField< double > & iCubInterfaceMessages::SingleJointEncodedResponse::angle () const inline
Definition at line 3057 of file icub.pb.h.
Referenced by SerializeWithCachedSizes().
angle() [2/2]
double iCubInterfaceMessages::SingleJointEncodedResponse::angle (int index) const inline
Definition at line 3044 of file icub.pb.h.
angle_size()
int iCubInterfaceMessages::SingleJointEncodedResponse::angle_size () const inline
Definition at line 3038 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
ByteSizeLong()
size_t iCubInterfaceMessages::SingleJointEncodedResponse::ByteSizeLong () const final
Definition at line 3150 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::SingleJointEncodedResponse::Clear () final
Definition at line 3013 of file icub.pb.cc.
Referenced by CopyFrom().
clear_angle()
void iCubInterfaceMessages::SingleJointEncodedResponse::clear_angle () inline
Definition at line 3041 of file icub.pb.h.
clear_status()
void iCubInterfaceMessages::SingleJointEncodedResponse::clear_status () inline
Definition at line 3024 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::SingleJointEncodedResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 3214 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::SingleJointEncodedResponse::CopyFrom (const SingleJointEncodedResponse & from)
Definition at line 3221 of file icub.pb.cc.
default_instance()
const SingleJointEncodedResponse & iCubInterfaceMessages::SingleJointEncodedResponse::default_instance () static
Definition at line 3007 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::SingleJointEncodedResponse::descriptor () static
Definition at line 3002 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::SingleJointEncodedResponse::GetCachedSize () const inline final
Definition at line 1156 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::SingleJointEncodedResponse::GetMetadata () const final
Definition at line 3243 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::SingleJointEncodedResponse::InitAsDefaultInstance () static
Definition at line 2964 of file icub.pb.cc.
internal_default_instance()
static const SingleJointEncodedResponse* iCubInterfaceMessages::SingleJointEncodedResponse::internal_default_instance () inline static
Definition at line 1121 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::SingleJointEncodedResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 3116 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::SingleJointEncodedResponse::IsInitialized () const final
Definition at line 3228 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::SingleJointEncodedResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 3186 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::SingleJointEncodedResponse::MergeFrom (const SingleJointEncodedResponse & from)
Definition at line 3201 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::SingleJointEncodedResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 3024 of file icub.pb.cc.
mutable_angle()
google::protobuf::RepeatedField< double > * iCubInterfaceMessages::SingleJointEncodedResponse::mutable_angle () inline
Definition at line 3062 of file icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/2]
SingleJointEncodedResponse* iCubInterfaceMessages::SingleJointEncodedResponse::New () const inline final
Definition at line 1135 of file icub.pb.h.
New() [2/2]
SingleJointEncodedResponse* iCubInterfaceMessages::SingleJointEncodedResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1139 of file icub.pb.h.
operator=()
SingleJointEncodedResponse& iCubInterfaceMessages::SingleJointEncodedResponse::operator= (const SingleJointEncodedResponse & from) inline
Definition at line 1098 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::SingleJointEncodedResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 3088 of file icub.pb.cc.
set_angle()
void iCubInterfaceMessages::SingleJointEncodedResponse::set_angle (int index, double value) inline
Definition at line 3048 of file icub.pb.h.
set_status()
void iCubInterfaceMessages::SingleJointEncodedResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 3031 of file icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status()
iCubInterfaceMessages::Status iCubInterfaceMessages::SingleJointEncodedResponse::status () const inline
Definition at line 3027 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
Swap()
void iCubInterfaceMessages::SingleJointEncodedResponse::Swap (SingleJointEncodedResponse * other)
Definition at line 3232 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 1204 of file icub.pb.h.
swap
void swap (SingleJointEncodedResponse & a, SingleJointEncodedResponse & b) friend
Definition at line 1129 of file icub.pb.h.
Member Data Documentation
kAngleFieldNumber
const int iCubInterfaceMessages::SingleJointEncodedResponse::kAngleFieldNumber = 2 static
Definition at line 1181 of file icub.pb.h.
kIndexInFileMessages
constexpr int iCubInterfaceMessages::SingleJointEncodedResponse::kIndexInFileMessages static constexpr
Initial value:
=
    8
Definition at line 1125 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kStatusFieldNumber
const int iCubInterfaceMessages::SingleJointEncodedResponse::kStatusFieldNumber = 1 static
Definition at line 1192 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc