from ANNarchy.core.SpecificPopulation import SpecificPopulation
from _typeshed import Incomplete

class VisionPopulation(SpecificPopulation):
    name: Incomplete
    def __init__(self, geometry=..., ip_address: str = ..., port: int = ..., copied: bool = ..., name: Incomplete | None = ...) -> None: ...
    @property
    def ip_address(self): ...
    @ip_address.setter
    def ip_address(self, value) -> None: ...
    @property
    def port(self): ...
    @port.setter
    def port(self, value) -> None: ...
    @property
    def period(self): ...
    @period.setter
    def period(self, value) -> None: ...
    @property
    def offset(self): ...
    @offset.setter
    def offset(self, value) -> None: ...
    def connect(self) -> None: ...
