ANNarchy iCub Interface: iCub_Python_Lib.YARP_motor_control Namespace Reference
iCub_Python_Lib.YARP_motor_control Namespace Reference
Functions
def motor_init (part, control="position", robot_prefix="icubSim", client_prefix="client")
Init motor control #########################.
def motor_init_cartesian (part, ctrl_prior="position", robot_prefix="icubSim", client_prefix="client")
def goto_zero_head_pos (iPos_head, iEnc_head, jnts_head)
go to head zero position ######################
def goto_position_block (iPos, iEnc, jnts, position)
Move joints of controlled part to a new position ##########.
def move_eyes (eye_pos, iPos_h, jnts_h, offset_h=0.0)
Move eyes to new position ######################.
def get_joint_position (iEnc, jnts, as_np=False)
get the joints positions ######################
def create_motor_dict (parts_used)
map motor control to dictionary ###################
def set_pos_vector (pos_vec, val_j0, val_j1, val_j2, val_j3, val_j4, val_j5)
set YARP position vector with given values #############
def set_pos_vector_array (position, jnts)
def set_pos_vector_same (value, jnts)
def npvec_2_yarpvec (array)
Convert between YARP vector and numpy array #############.
def yarpvec_2_npvec (yarp_vec)
Variables
dictionary parts
Detailed Description
Created on Thu Apr 13 15:16:32 2018
@author: tofo
library for functions related to the motor control
Function Documentation
create_motor_dict()
def iCub_Python_Lib.YARP_motor_control.create_motor_dict (parts_used)
map motor control to dictionary ###################
    wrap the motor control interfaces in a dictionary for a given set of robot parts
    (Used to connect the CPG to the iCub)
    params: parts_used      -- list with strings for the used robot parts
    return: joint_mapping   -- mapping of the part joint numbers to a sequence containing all joints
            ctrl_interfaces -- dictionary for all control interfaces
            motor_driver    -- list with all created device drivers
get_joint_position()
def iCub_Python_Lib.YARP_motor_control.get_joint_position (iEnc, jnts, as_np = False)
get the joints positions ######################
    get position of controlled joints
    params: iEnc        -- Encoder for the controlled joints
            jnts        -- number of joints
            as_np       -- if True: a numpy array is returned
                              False: a YARP vector is returned
    return: vector containing the joint positions -> YARP-Vector or numpy array dependent on as_np
Referenced by iCub_Python_Lib.YARP_motor_control.goto_position_block(), and iCub_Python_Lib.YARP_motor_control.goto_zero_head_pos().
goto_position_block()
def iCub_Python_Lib.YARP_motor_control.goto_position_block (iPos, iEnc, jnts, position)
Move joints of controlled part to a new position ##########.
    Go to given position and block until motion done
    params: iPos        -- Position Controller for the iCub part
            iEnc        -- Encoder for the joints
            jnts        -- number of controlled joints
            position    -- new position as YARP-Vector
goto_zero_head_pos()
def iCub_Python_Lib.YARP_motor_control.goto_zero_head_pos (iPos_head, iEnc_head, jnts_head)
go to head zero position ######################
    go to the all joints at 0 degree position
    params: iPos_head   -- Position Controller for the iCub head
            iEnc_head   -- Encoder for the head joints
            jnts_head   -- number of head joints
motor_init()
def iCub_Python_Lib.YARP_motor_control.motor_init (part, control = "position", robot_prefix = "icubSim", client_prefix = "client")
Init motor control #########################.
    initialize motor control for the given part
    params: part            -- part of the iCub to be controlled (string: head, left_arm, right_arm, torso, right_leg, left_leg)
            control         -- control type: position(default) -> joint angle control ; velocity -> joint velocity control
            robot_prefix    -- robot name; normally "iCubSim" for simulation and "icub" for real robot
            client_prefix   -- client name; normally no need to change; only if multiple user work in the same YARP-network
    return: iPos    -- Position/Velocity Controller for the given iCub part
            iEnc    -- Encoder for the controlled joints
            jnts    -- number of controlled joints
            driver  -- device driver; need to be returned, otherwise joint controlboard is closed
            Returns None for all if an error occured
Referenced by iCub_Python_Lib.YARP_motor_control.create_motor_dict().
motor_init_cartesian()
def iCub_Python_Lib.YARP_motor_control.motor_init_cartesian (part, ctrl_prior = "position", robot_prefix = "icubSim", client_prefix = "client")
    initialize motor control for the given part
    params: part            -- part of the iCub to be controlled (string: left_arm, right_arm, right_leg, left_leg)
            ctrl_prior      -- control priority; either position or orientation of the end-effector (hand or foot)
            robot_prefix    -- robot name; normally "iCubSim" for simulation and "icub" for real robot
            client_prefix   -- client name; normally no need to change; only if multiple user work in the same YARP-network
    return: iCart   -- Cartesian Controller for the given iCub part -> None in case of failure
            driver  -- device driver; need to be returned, otherwise joint controlboard is closed -> None in case of failure
move_eyes()
def iCub_Python_Lib.YARP_motor_control.move_eyes (eye_pos, iPos_h, jnts_h, offset_h = 0.0)
Move eyes to new position ######################.
    move the iCub eyes to a new position
    params: eye_pos     -- target eye position [ gaze_y, gaze_x, vergence_angle ]
            iPos_h      -- Position Controller for the iCub head
            jnts_h      -- number of head joints
            offset_h    -- head offset in left/right direction
npvec_2_yarpvec()
def iCub_Python_Lib.YARP_motor_control.npvec_2_yarpvec (array)
Convert between YARP vector and numpy array #############.
    convert a 1D numpy array into a YARP vector
    params: array       -- 1D array-like position vector
    return: yarp_vec    -- YARP vector, result of conversion
set_pos_vector()
def iCub_Python_Lib.YARP_motor_control.set_pos_vector (pos_vec, val_j0, val_j1, val_j2, val_j3, val_j4, val_j5)
set YARP position vector with given values #############
    set position vector with given values for each joint (6 joints like iCub head)
    params: pos_vec     -- YARP position vector
            val_j0      -- value joint 0, double value
            val_j1      -- value joint 1, double value
            val_j2      -- value joint 2, double value
            val_j3      -- value joint 3, double value
            val_j4      -- value joint 4, double value
            val_j5      -- value joint 5, double value
    return: pos_vec     -- position as YARP vector
set_pos_vector_array()
def iCub_Python_Lib.YARP_motor_control.set_pos_vector_array (position, jnts)
    set position vector with given values for each joint (e.g. 6 joints for iCub head)
    params: position    -- position in array-like structure (list/numpy array), double values
            jnts        -- number of joints
    return: pos_vec     -- position as YARP vector
set_pos_vector_same()
def iCub_Python_Lib.YARP_motor_control.set_pos_vector_same (value, jnts)
    set position vector with one value for all joints
    params: pos_vec     -- position vector
            value       -- value for all joints, double value
            jnts        -- number of joints
    return: pos_vec     -- position as YARP vector
Referenced by iCub_Python_Lib.YARP_motor_control.goto_zero_head_pos(), and iCub_Python_Lib.YARP_motor_control.move_eyes().
yarpvec_2_npvec()
def iCub_Python_Lib.YARP_motor_control.yarpvec_2_npvec (yarp_vec)
    convert a YARP vector into a 1D numpy array
    params: yarp_vec    -- 1D YARP vector
    return: vector      -- 1D Numpy array, result of conversion
Referenced by iCub_Python_Lib.YARP_motor_control.get_joint_position().
Variable Documentation
parts
dictionary iCub_Python_Lib.YARP_motor_control.parts
Initial value:
 =  {"head": True, "left_arm": False, "right_arm": False,
          "torso": True, "right_leg": False, "left_leg": False}