ANNarchy iCub Interface: iCubInterfaceMessages::SkinRequest Class Reference
iCubInterfaceMessages::SkinRequest Class Reference
#include <icub.pb.h>
Public Member Functions
SkinRequest ()
virtual ~SkinRequest ()
SkinRequest (const SkinRequest &from)
SkinRequest & operator= (const SkinRequest &from)
void Swap (SkinRequest *other)
SkinRequest * New () const final
SkinRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SkinRequest &from)
void MergeFrom (const SkinRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_skin_section ()
const ::std::string & skin_section () const
void set_skin_section (const ::std::string &value)
void set_skin_section (const char *value)
void set_skin_section (const char *value, size_t size)
::std::string * mutable_skin_section ()
::std::string * release_skin_section ()
void set_allocated_skin_section (::std::string *skin_section)
SkinRequest ()
virtual ~SkinRequest ()
SkinRequest (const SkinRequest &from)
SkinRequest & operator= (const SkinRequest &from)
void Swap (SkinRequest *other)
SkinRequest * New () const final
SkinRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SkinRequest &from)
void MergeFrom (const SkinRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_skin_section ()
const ::std::string & skin_section () const
void set_skin_section (const ::std::string &value)
void set_skin_section (const char *value)
void set_skin_section (const char *value, size_t size)
::std::string * mutable_skin_section ()
::std::string * release_skin_section ()
void set_allocated_skin_section (::std::string *skin_section)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SkinRequest & default_instance ()
static void InitAsDefaultInstance ()
static const SkinRequest * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const SkinRequest & default_instance ()
static void InitAsDefaultInstance ()
static const SkinRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kSkinSectionFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (SkinRequest &a, SkinRequest &b)
void swap (SkinRequest &a, SkinRequest &b)
Detailed Description
Definition at line 2695 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
SkinRequest() [1/4]
iCubInterfaceMessages::SkinRequest::SkinRequest ()
Definition at line 6643 of file icub.pb.cc.
~SkinRequest() [1/2]
iCubInterfaceMessages::SkinRequest::~SkinRequest () virtual
Definition at line 6665 of file icub.pb.cc.
SkinRequest() [2/4]
iCubInterfaceMessages::SkinRequest::SkinRequest (const SkinRequest & from)
Definition at line 6650 of file icub.pb.cc.
SkinRequest() [3/4]
iCubInterfaceMessages::SkinRequest::SkinRequest ()
~SkinRequest() [2/2]
virtual iCubInterfaceMessages::SkinRequest::~SkinRequest () virtual
SkinRequest() [4/4]
iCubInterfaceMessages::SkinRequest::SkinRequest (const SkinRequest & from)
Member Function Documentation
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::SkinRequest::ByteSizeLong () const final
Definition at line 6793 of file icub.pb.cc.
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::SkinRequest::ByteSizeLong () const final
Clear() [1/2]
void iCubInterfaceMessages::SkinRequest::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::SkinRequest::Clear () final
Definition at line 6688 of file icub.pb.cc.
Referenced by CopyFrom().
clear_skin_section() [1/2]
void iCubInterfaceMessages::SkinRequest::clear_skin_section () inline
Definition at line 3925 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_skin_section() [2/2]
void iCubInterfaceMessages::SkinRequest::clear_skin_section ()
CopyFrom() [1/4]
void iCubInterfaceMessages::SkinRequest::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/4]
void iCubInterfaceMessages::SkinRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 6842 of file icub.pb.cc.
CopyFrom() [3/4]
void iCubInterfaceMessages::SkinRequest::CopyFrom (const SkinRequest & from)
CopyFrom() [4/4]
void iCubInterfaceMessages::SkinRequest::CopyFrom (const SkinRequest & from)
Definition at line 6849 of file icub.pb.cc.
default_instance() [1/2]
const SkinRequest & iCubInterfaceMessages::SkinRequest::default_instance () static
Definition at line 6682 of file icub.pb.cc.
default_instance() [2/2]
static const SkinRequest& iCubInterfaceMessages::SkinRequest::default_instance () static
descriptor() [1/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::SkinRequest::descriptor () static
Definition at line 6677 of file icub.pb.cc.
descriptor() [2/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::SkinRequest::descriptor () static
GetCachedSize() [1/2]
int iCubInterfaceMessages::SkinRequest::GetCachedSize () const inline final
Definition at line 2760 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::SkinRequest::GetCachedSize () const inline final
Definition at line 2760 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
google::protobuf::Metadata iCubInterfaceMessages::SkinRequest::GetMetadata () const final
Definition at line 6871 of file icub.pb.cc.
GetMetadata() [2/2]
::google::protobuf::Metadata iCubInterfaceMessages::SkinRequest::GetMetadata () const final
InitAsDefaultInstance() [1/2]
static void iCubInterfaceMessages::SkinRequest::InitAsDefaultInstance () static
InitAsDefaultInstance() [2/2]
void iCubInterfaceMessages::SkinRequest::InitAsDefaultInstance () static
Definition at line 6637 of file icub.pb.cc.
internal_default_instance() [1/2]
static const SkinRequest* iCubInterfaceMessages::SkinRequest::internal_default_instance () inline static
Definition at line 2725 of file iCub_ANN_Interface/grpc/icub.pb.h.
internal_default_instance() [2/2]
static const SkinRequest* iCubInterfaceMessages::SkinRequest::internal_default_instance () inline static
Definition at line 2725 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::SkinRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 6767 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::SkinRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::SkinRequest::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::SkinRequest::IsInitialized () const final
Definition at line 6856 of file icub.pb.cc.
MergeFrom() [1/4]
void iCubInterfaceMessages::SkinRequest::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/4]
void iCubInterfaceMessages::SkinRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 6814 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [3/4]
void iCubInterfaceMessages::SkinRequest::MergeFrom (const SkinRequest & from)
Definition at line 6829 of file icub.pb.cc.
MergeFrom() [4/4]
void iCubInterfaceMessages::SkinRequest::MergeFrom (const SkinRequest & from)
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::SkinRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 6698 of file icub.pb.cc.
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::SkinRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_skin_section() [1/2]
std::string * iCubInterfaceMessages::SkinRequest::mutable_skin_section () inline
Definition at line 3957 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergePartialFromCodedStream().
mutable_skin_section() [2/2]
::std::string* iCubInterfaceMessages::SkinRequest::mutable_skin_section ()
New() [1/4]
SkinRequest* iCubInterfaceMessages::SkinRequest::New () const inline final
Definition at line 2739 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
SkinRequest* iCubInterfaceMessages::SkinRequest::New () const inline final
Definition at line 2739 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
SkinRequest* iCubInterfaceMessages::SkinRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 2743 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
SkinRequest* iCubInterfaceMessages::SkinRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 2743 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
SkinRequest& iCubInterfaceMessages::SkinRequest::operator= (const SkinRequest & from) inline
Definition at line 2702 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
SkinRequest& iCubInterfaceMessages::SkinRequest::operator= (const SkinRequest & from) inline
Definition at line 2702 of file iCub_ANN_Interface/grpc/icub.pb.h.
release_skin_section() [1/2]
::std::string* iCubInterfaceMessages::SkinRequest::release_skin_section ()
release_skin_section() [2/2]
std::string * iCubInterfaceMessages::SkinRequest::release_skin_section () inline
Definition at line 3962 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::SkinRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 6744 of file icub.pb.cc.
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::SkinRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_skin_section() [1/2]
void iCubInterfaceMessages::SkinRequest::set_allocated_skin_section (::std::string * skin_section)
set_allocated_skin_section() [2/2]
void iCubInterfaceMessages::SkinRequest::set_allocated_skin_section (::std::string * skin_section) inline
Definition at line 3967 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
set_skin_section() [1/6]
void iCubInterfaceMessages::SkinRequest::set_skin_section (const ::std::string & value)
set_skin_section() [2/6]
void iCubInterfaceMessages::SkinRequest::set_skin_section (const ::std::string & value) inline
Definition at line 3932 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
set_skin_section() [3/6]
void iCubInterfaceMessages::SkinRequest::set_skin_section (const char * value) inline
Definition at line 3945 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
set_skin_section() [4/6]
void iCubInterfaceMessages::SkinRequest::set_skin_section (const char * value)
set_skin_section() [5/6]
void iCubInterfaceMessages::SkinRequest::set_skin_section (const char * value, size_t size) inline
Definition at line 3951 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
set_skin_section() [6/6]
void iCubInterfaceMessages::SkinRequest::set_skin_section (const char * value, size_t size)
skin_section() [1/2]
const ::std::string & iCubInterfaceMessages::SkinRequest::skin_section () const inline
Definition at line 3928 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), and SkinRequest().
skin_section() [2/2]
const ::std::string& iCubInterfaceMessages::SkinRequest::skin_section () const
Swap() [1/2]
void iCubInterfaceMessages::SkinRequest::Swap (SkinRequest * other)
Definition at line 6860 of file icub.pb.cc.
Swap() [2/2]
void iCubInterfaceMessages::SkinRequest::Swap (SkinRequest * other)
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 2802 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (SkinRequest & a, SkinRequest & b) friend
Definition at line 2733 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (SkinRequest & a, SkinRequest & b) friend
Definition at line 2733 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::SkinRequest::kIndexInFileMessages static constexpr
Initial value:
=
    23
Definition at line 2729 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kSkinSectionFieldNumber
static const int iCubInterfaceMessages::SkinRequest::kSkinSectionFieldNumber = 1 static
Definition at line 2784 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc