ANNarchy iCub Interface: iCubInterfaceMessages::ProvideInput::Stub Class Reference
iCubInterfaceMessages::ProvideInput::Stub Class Reference final
#include <icub.grpc.pb.h>
Classes
class experimental_async
Public Member Functions
Stub (const std::shared_ptr< ::grpc::ChannelInterface > &channel)
::grpc::Status ReadTest (::grpc::ClientContext *context, const ::iCubInterfaceMessages::TestRequest &request, ::iCubInterfaceMessages::TestResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::TestResponse > > AsyncReadTest (::grpc::ClientContext *context, const ::iCubInterfaceMessages::TestRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::TestResponse > > PrepareAsyncReadTest (::grpc::ClientContext *context, const ::iCubInterfaceMessages::TestRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadImage (::grpc::ClientContext *context, const ::iCubInterfaceMessages::ImageRequest &request, ::iCubInterfaceMessages::ImageResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::ImageResponse > > AsyncReadImage (::grpc::ClientContext *context, const ::iCubInterfaceMessages::ImageRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::ImageResponse > > PrepareAsyncReadImage (::grpc::ClientContext *context, const ::iCubInterfaceMessages::ImageRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadSingleJoint (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleJointRequest &request, ::iCubInterfaceMessages::SingleJointResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleJointResponse > > AsyncReadSingleJoint (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleJointRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleJointResponse > > PrepareAsyncReadSingleJoint (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleJointRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadMultiJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiJointRequest &request, ::iCubInterfaceMessages::MultiJointResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiJointResponse > > AsyncReadMultiJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiJointRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiJointResponse > > PrepareAsyncReadMultiJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiJointRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadAllJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllJointsRequest &request, ::iCubInterfaceMessages::AllJointsResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllJointsResponse > > AsyncReadAllJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllJointsRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllJointsResponse > > PrepareAsyncReadAllJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllJointsRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadSkin (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinRequest &request, ::iCubInterfaceMessages::SkinResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkin (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkin (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadSkinArm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinArmRequest &request, ::iCubInterfaceMessages::SkinResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkinArm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinArmRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkinArm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinArmRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadSkinForearm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinForearmRequest &request, ::iCubInterfaceMessages::SkinResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkinForearm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinForearmRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkinForearm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinForearmRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadSkinHand (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinHandRequest &request, ::iCubInterfaceMessages::SkinResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkinHand (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinHandRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkinHand (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinHandRequest &request, ::grpc::CompletionQueue *cq)
class experimental_async_interface * experimental_async () override
Stub (const std::shared_ptr< ::grpc::ChannelInterface > &channel)
::grpc::Status ReadTest (::grpc::ClientContext *context, const ::iCubInterfaceMessages::TestRequest &request, ::iCubInterfaceMessages::TestResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::TestResponse > > AsyncReadTest (::grpc::ClientContext *context, const ::iCubInterfaceMessages::TestRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::TestResponse > > PrepareAsyncReadTest (::grpc::ClientContext *context, const ::iCubInterfaceMessages::TestRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadImage (::grpc::ClientContext *context, const ::iCubInterfaceMessages::ImageRequest &request, ::iCubInterfaceMessages::ImageResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::ImageResponse > > AsyncReadImage (::grpc::ClientContext *context, const ::iCubInterfaceMessages::ImageRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::ImageResponse > > PrepareAsyncReadImage (::grpc::ClientContext *context, const ::iCubInterfaceMessages::ImageRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadSingleJoint (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleJointRequest &request, ::iCubInterfaceMessages::SingleJointResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleJointResponse > > AsyncReadSingleJoint (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleJointRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleJointResponse > > PrepareAsyncReadSingleJoint (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleJointRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadMultiJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiJointRequest &request, ::iCubInterfaceMessages::MultiJointResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiJointResponse > > AsyncReadMultiJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiJointRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiJointResponse > > PrepareAsyncReadMultiJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiJointRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadAllJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllJointsRequest &request, ::iCubInterfaceMessages::AllJointsResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllJointsResponse > > AsyncReadAllJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllJointsRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllJointsResponse > > PrepareAsyncReadAllJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllJointsRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadSkin (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinRequest &request, ::iCubInterfaceMessages::SkinResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkin (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkin (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadSkinArm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinArmRequest &request, ::iCubInterfaceMessages::SkinResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkinArm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinArmRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkinArm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinArmRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadSkinForearm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinForearmRequest &request, ::iCubInterfaceMessages::SkinResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkinForearm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinForearmRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkinForearm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinForearmRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status ReadSkinHand (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinHandRequest &request, ::iCubInterfaceMessages::SkinResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkinHand (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinHandRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkinHand (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinHandRequest &request, ::grpc::CompletionQueue *cq)
class experimental_async_interface * experimental_async () override
Public Member Functions inherited from iCubInterfaceMessages::ProvideInput::StubInterface
virtual ~StubInterface ()
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::TestResponse > > AsyncReadTest (::grpc::ClientContext *context, const ::iCubInterfaceMessages::TestRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::TestResponse > > PrepareAsyncReadTest (::grpc::ClientContext *context, const ::iCubInterfaceMessages::TestRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::ImageResponse > > AsyncReadImage (::grpc::ClientContext *context, const ::iCubInterfaceMessages::ImageRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::ImageResponse > > PrepareAsyncReadImage (::grpc::ClientContext *context, const ::iCubInterfaceMessages::ImageRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SingleJointResponse > > AsyncReadSingleJoint (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleJointRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SingleJointResponse > > PrepareAsyncReadSingleJoint (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleJointRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::MultiJointResponse > > AsyncReadMultiJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiJointRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::MultiJointResponse > > PrepareAsyncReadMultiJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiJointRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::AllJointsResponse > > AsyncReadAllJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllJointsRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::AllJointsResponse > > PrepareAsyncReadAllJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllJointsRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkin (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkin (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkinArm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinArmRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkinArm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinArmRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkinForearm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinForearmRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkinForearm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinForearmRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkinHand (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinHandRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkinHand (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinHandRequest &request, ::grpc::CompletionQueue *cq)
virtual ~StubInterface ()
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::TestResponse > > AsyncReadTest (::grpc::ClientContext *context, const ::iCubInterfaceMessages::TestRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::TestResponse > > PrepareAsyncReadTest (::grpc::ClientContext *context, const ::iCubInterfaceMessages::TestRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::ImageResponse > > AsyncReadImage (::grpc::ClientContext *context, const ::iCubInterfaceMessages::ImageRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::ImageResponse > > PrepareAsyncReadImage (::grpc::ClientContext *context, const ::iCubInterfaceMessages::ImageRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SingleJointResponse > > AsyncReadSingleJoint (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleJointRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SingleJointResponse > > PrepareAsyncReadSingleJoint (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleJointRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::MultiJointResponse > > AsyncReadMultiJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiJointRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::MultiJointResponse > > PrepareAsyncReadMultiJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiJointRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::AllJointsResponse > > AsyncReadAllJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllJointsRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::AllJointsResponse > > PrepareAsyncReadAllJoints (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllJointsRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkin (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkin (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkinArm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinArmRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkinArm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinArmRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkinForearm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinForearmRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkinForearm (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinForearmRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > AsyncReadSkinHand (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinHandRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SkinResponse > > PrepareAsyncReadSkinHand (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SkinHandRequest &request, ::grpc::CompletionQueue *cq)
Detailed Description
Definition at line 153 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
Constructor & Destructor Documentation
Stub() [1/2]
iCubInterfaceMessages::ProvideInput::Stub::Stub (const std::shared_ptr< ::grpc::ChannelInterface > & channel)
Definition at line 38 of file icub.grpc.pb.cc.
Stub() [2/2]
iCubInterfaceMessages::ProvideInput::Stub::Stub (const std::shared_ptr< ::grpc::ChannelInterface > & channel)
Member Function Documentation
AsyncReadAllJoints() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllJointsResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadAllJoints (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllJointsRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 185 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadAllJoints() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllJointsResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadAllJoints (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllJointsRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 185 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadImage() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::ImageResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadImage (::grpc::ClientContext * context, const ::iCubInterfaceMessages::ImageRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 164 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadImage() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::ImageResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadImage (::grpc::ClientContext * context, const ::iCubInterfaceMessages::ImageRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 164 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadMultiJoints() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiJointResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadMultiJoints (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiJointRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 178 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadMultiJoints() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiJointResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadMultiJoints (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiJointRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 178 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadSingleJoint() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleJointResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadSingleJoint (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleJointRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 171 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadSingleJoint() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleJointResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadSingleJoint (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleJointRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 171 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadSkin() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadSkin (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 192 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadSkin() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadSkin (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 192 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadSkinArm() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadSkinArm (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinArmRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 199 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadSkinArm() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadSkinArm (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinArmRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 199 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadSkinForearm() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadSkinForearm (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinForearmRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 206 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadSkinForearm() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadSkinForearm (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinForearmRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 206 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadSkinHand() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadSkinHand (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinHandRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 213 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadSkinHand() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadSkinHand (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinHandRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 213 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadTest() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::TestResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadTest (::grpc::ClientContext * context, const ::iCubInterfaceMessages::TestRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 157 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncReadTest() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::TestResponse> > iCubInterfaceMessages::ProvideInput::Stub::AsyncReadTest (::grpc::ClientContext * context, const ::iCubInterfaceMessages::TestRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 157 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
experimental_async() [1/2]
class experimental_async_interface* iCubInterfaceMessages::ProvideInput::Stub::experimental_async () inline override virtual
Reimplemented from iCubInterfaceMessages::ProvideInput::StubInterface.
Definition at line 237 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
experimental_async() [2/2]
class experimental_async_interface* iCubInterfaceMessages::ProvideInput::Stub::experimental_async () inline override virtual
Reimplemented from iCubInterfaceMessages::ProvideInput::StubInterface.
Definition at line 237 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadAllJoints() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllJointsResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadAllJoints (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllJointsRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 188 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadAllJoints() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllJointsResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadAllJoints (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllJointsRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 188 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadImage() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::ImageResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadImage (::grpc::ClientContext * context, const ::iCubInterfaceMessages::ImageRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 167 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadImage() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::ImageResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadImage (::grpc::ClientContext * context, const ::iCubInterfaceMessages::ImageRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 167 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadMultiJoints() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiJointResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadMultiJoints (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiJointRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 181 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadMultiJoints() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiJointResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadMultiJoints (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiJointRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 181 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadSingleJoint() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleJointResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadSingleJoint (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleJointRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 174 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadSingleJoint() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleJointResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadSingleJoint (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleJointRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 174 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadSkin() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadSkin (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 195 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadSkin() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadSkin (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 195 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadSkinArm() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadSkinArm (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinArmRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 202 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadSkinArm() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadSkinArm (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinArmRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 202 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadSkinForearm() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadSkinForearm (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinForearmRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 209 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadSkinForearm() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadSkinForearm (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinForearmRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 209 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadSkinHand() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadSkinHand (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinHandRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 216 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadSkinHand() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SkinResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadSkinHand (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinHandRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 216 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadTest() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::TestResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadTest (::grpc::ClientContext * context, const ::iCubInterfaceMessages::TestRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 160 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncReadTest() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::TestResponse> > iCubInterfaceMessages::ProvideInput::Stub::PrepareAsyncReadTest (::grpc::ClientContext * context, const ::iCubInterfaceMessages::TestRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 160 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
ReadAllJoints() [1/2]
grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadAllJoints (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllJointsRequest & request, ::iCubInterfaceMessages::AllJointsResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
Definition at line 114 of file icub.grpc.pb.cc.
Referenced by ClientInstance::retrieve_alljoints().
ReadAllJoints() [2/2]
::grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadAllJoints (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllJointsRequest & request, ::iCubInterfaceMessages::AllJointsResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
ReadImage() [1/2]
::grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadImage (::grpc::ClientContext * context, const ::iCubInterfaceMessages::ImageRequest & request, ::iCubInterfaceMessages::ImageResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
ReadImage() [2/2]
grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadImage (::grpc::ClientContext * context, const ::iCubInterfaceMessages::ImageRequest & request, ::iCubInterfaceMessages::ImageResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
Definition at line 66 of file icub.grpc.pb.cc.
Referenced by ClientInstance::retrieve_image().
ReadMultiJoints() [1/2]
grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadMultiJoints (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiJointRequest & request, ::iCubInterfaceMessages::MultiJointResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
Definition at line 98 of file icub.grpc.pb.cc.
Referenced by ClientInstance::retrieve_multijoints().
ReadMultiJoints() [2/2]
::grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadMultiJoints (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiJointRequest & request, ::iCubInterfaceMessages::MultiJointResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
ReadSingleJoint() [1/2]
::grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadSingleJoint (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleJointRequest & request, ::iCubInterfaceMessages::SingleJointResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
ReadSingleJoint() [2/2]
grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadSingleJoint (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleJointRequest & request, ::iCubInterfaceMessages::SingleJointResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
Definition at line 82 of file icub.grpc.pb.cc.
Referenced by ClientInstance::retrieve_singlejoint().
ReadSkin() [1/2]
::grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadSkin (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinRequest & request, ::iCubInterfaceMessages::SkinResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
ReadSkin() [2/2]
grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadSkin (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinRequest & request, ::iCubInterfaceMessages::SkinResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
Definition at line 130 of file icub.grpc.pb.cc.
ReadSkinArm() [1/2]
grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadSkinArm (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinArmRequest & request, ::iCubInterfaceMessages::SkinResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
Definition at line 146 of file icub.grpc.pb.cc.
Referenced by ClientInstance::retrieve_skin_arm().
ReadSkinArm() [2/2]
::grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadSkinArm (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinArmRequest & request, ::iCubInterfaceMessages::SkinResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
ReadSkinForearm() [1/2]
grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadSkinForearm (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinForearmRequest & request, ::iCubInterfaceMessages::SkinResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
Definition at line 162 of file icub.grpc.pb.cc.
Referenced by ClientInstance::retrieve_skin_forearm().
ReadSkinForearm() [2/2]
::grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadSkinForearm (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinForearmRequest & request, ::iCubInterfaceMessages::SkinResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
ReadSkinHand() [1/2]
grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadSkinHand (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinHandRequest & request, ::iCubInterfaceMessages::SkinResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
Definition at line 178 of file icub.grpc.pb.cc.
Referenced by ClientInstance::retrieve_skin_hand().
ReadSkinHand() [2/2]
::grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadSkinHand (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SkinHandRequest & request, ::iCubInterfaceMessages::SkinResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
ReadTest() [1/2]
::grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadTest (::grpc::ClientContext * context, const ::iCubInterfaceMessages::TestRequest & request, ::iCubInterfaceMessages::TestResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
ReadTest() [2/2]
grpc::Status iCubInterfaceMessages::ProvideInput::Stub::ReadTest (::grpc::ClientContext * context, const ::iCubInterfaceMessages::TestRequest & request, ::iCubInterfaceMessages::TestResponse * response) override virtual
Implements iCubInterfaceMessages::ProvideInput::StubInterface.
Definition at line 50 of file icub.grpc.pb.cc.
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h
icub.grpc.pb.cc