ANNarchy iCub Interface: iCubInterfaceMessages::AllTargetEncodedResponse Class Reference
iCubInterfaceMessages::AllTargetEncodedResponse Class Reference
#include <icub.pb.h>
Public Member Functions
AllTargetEncodedResponse ()
virtual ~AllTargetEncodedResponse ()
AllTargetEncodedResponse (const AllTargetEncodedResponse &from)
AllTargetEncodedResponse & operator= (const AllTargetEncodedResponse &from)
void Swap (AllTargetEncodedResponse *other)
AllTargetEncodedResponse * New () const final
AllTargetEncodedResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const AllTargetEncodedResponse &from)
void MergeFrom (const AllTargetEncodedResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
AllTargetEncodedResponse ()
virtual ~AllTargetEncodedResponse ()
AllTargetEncodedResponse (const AllTargetEncodedResponse &from)
AllTargetEncodedResponse & operator= (const AllTargetEncodedResponse &from)
void Swap (AllTargetEncodedResponse *other)
AllTargetEncodedResponse * New () const final
AllTargetEncodedResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const AllTargetEncodedResponse &from)
void MergeFrom (const AllTargetEncodedResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const AllTargetEncodedResponse & default_instance ()
static void InitAsDefaultInstance ()
static const AllTargetEncodedResponse * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const AllTargetEncodedResponse & default_instance ()
static void InitAsDefaultInstance ()
static const AllTargetEncodedResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kAngleFieldNumber = 2
static const int kStatusFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (AllTargetEncodedResponse &a, AllTargetEncodedResponse &b)
void swap (AllTargetEncodedResponse &a, AllTargetEncodedResponse &b)
Detailed Description
Definition at line 2578 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
AllTargetEncodedResponse() [1/4]
iCubInterfaceMessages::AllTargetEncodedResponse::AllTargetEncodedResponse ()
Definition at line 6357 of file icub.pb.cc.
~AllTargetEncodedResponse() [1/2]
iCubInterfaceMessages::AllTargetEncodedResponse::~AllTargetEncodedResponse () virtual
Definition at line 6377 of file icub.pb.cc.
AllTargetEncodedResponse() [2/4]
iCubInterfaceMessages::AllTargetEncodedResponse::AllTargetEncodedResponse (const AllTargetEncodedResponse & from)
Definition at line 6364 of file icub.pb.cc.
AllTargetEncodedResponse() [3/4]
iCubInterfaceMessages::AllTargetEncodedResponse::AllTargetEncodedResponse ()
~AllTargetEncodedResponse() [2/2]
virtual iCubInterfaceMessages::AllTargetEncodedResponse::~AllTargetEncodedResponse () virtual
AllTargetEncodedResponse() [4/4]
iCubInterfaceMessages::AllTargetEncodedResponse::AllTargetEncodedResponse (const AllTargetEncodedResponse & from)
Member Function Documentation
add_angle() [1/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::add_angle (double value) inline
Definition at line 3905 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
add_angle() [2/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::add_angle (double value)
angle() [1/4]
const ::google::protobuf::RepeatedField< double > & iCubInterfaceMessages::AllTargetEncodedResponse::angle () const inline
Definition at line 3910 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by SerializeWithCachedSizes().
angle() [2/4]
const ::google::protobuf::RepeatedField< double >& iCubInterfaceMessages::AllTargetEncodedResponse::angle () const
angle() [3/4]
double iCubInterfaceMessages::AllTargetEncodedResponse::angle (int index) const inline
Definition at line 3897 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by WriteClientInstance::retrieve_alltarget_enc().
angle() [4/4]
double iCubInterfaceMessages::AllTargetEncodedResponse::angle (int index) const
angle_size() [1/2]
int iCubInterfaceMessages::AllTargetEncodedResponse::angle_size () const inline
Definition at line 3891 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
angle_size() [2/2]
int iCubInterfaceMessages::AllTargetEncodedResponse::angle_size () const
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::AllTargetEncodedResponse::ByteSizeLong () const final
Definition at line 6536 of file icub.pb.cc.
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::AllTargetEncodedResponse::ByteSizeLong () const final
Clear() [1/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::Clear () final
Definition at line 6399 of file icub.pb.cc.
Referenced by CopyFrom().
clear_angle() [1/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::clear_angle () inline
Definition at line 3894 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_angle() [2/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::clear_angle ()
clear_status() [1/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::clear_status () inline
Definition at line 3877 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_status() [2/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::clear_status ()
CopyFrom() [1/4]
void iCubInterfaceMessages::AllTargetEncodedResponse::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/4]
void iCubInterfaceMessages::AllTargetEncodedResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 6600 of file icub.pb.cc.
CopyFrom() [3/4]
void iCubInterfaceMessages::AllTargetEncodedResponse::CopyFrom (const AllTargetEncodedResponse & from)
CopyFrom() [4/4]
void iCubInterfaceMessages::AllTargetEncodedResponse::CopyFrom (const AllTargetEncodedResponse & from)
Definition at line 6607 of file icub.pb.cc.
default_instance() [1/2]
static const AllTargetEncodedResponse& iCubInterfaceMessages::AllTargetEncodedResponse::default_instance () static
default_instance() [2/2]
const AllTargetEncodedResponse & iCubInterfaceMessages::AllTargetEncodedResponse::default_instance () static
Definition at line 6393 of file icub.pb.cc.
descriptor() [1/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::AllTargetEncodedResponse::descriptor () static
descriptor() [2/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::AllTargetEncodedResponse::descriptor () static
Definition at line 6388 of file icub.pb.cc.
GetCachedSize() [1/2]
int iCubInterfaceMessages::AllTargetEncodedResponse::GetCachedSize () const inline final
Definition at line 2643 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::AllTargetEncodedResponse::GetCachedSize () const inline final
Definition at line 2643 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
google::protobuf::Metadata iCubInterfaceMessages::AllTargetEncodedResponse::GetMetadata () const final
Definition at line 6629 of file icub.pb.cc.
GetMetadata() [2/2]
::google::protobuf::Metadata iCubInterfaceMessages::AllTargetEncodedResponse::GetMetadata () const final
InitAsDefaultInstance() [1/2]
static void iCubInterfaceMessages::AllTargetEncodedResponse::InitAsDefaultInstance () static
InitAsDefaultInstance() [2/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::InitAsDefaultInstance () static
Definition at line 6350 of file icub.pb.cc.
internal_default_instance() [1/2]
static const AllTargetEncodedResponse* iCubInterfaceMessages::AllTargetEncodedResponse::internal_default_instance () inline static
Definition at line 2608 of file iCub_ANN_Interface/grpc/icub.pb.h.
internal_default_instance() [2/2]
static const AllTargetEncodedResponse* iCubInterfaceMessages::AllTargetEncodedResponse::internal_default_instance () inline static
Definition at line 2608 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::AllTargetEncodedResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 6502 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::AllTargetEncodedResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::AllTargetEncodedResponse::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::AllTargetEncodedResponse::IsInitialized () const final
Definition at line 6614 of file icub.pb.cc.
MergeFrom() [1/4]
void iCubInterfaceMessages::AllTargetEncodedResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 6572 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/4]
void iCubInterfaceMessages::AllTargetEncodedResponse::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [3/4]
void iCubInterfaceMessages::AllTargetEncodedResponse::MergeFrom (const AllTargetEncodedResponse & from)
MergeFrom() [4/4]
void iCubInterfaceMessages::AllTargetEncodedResponse::MergeFrom (const AllTargetEncodedResponse & from)
Definition at line 6587 of file icub.pb.cc.
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::AllTargetEncodedResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 6410 of file icub.pb.cc.
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::AllTargetEncodedResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_angle() [1/2]
::google::protobuf::RepeatedField< double >* iCubInterfaceMessages::AllTargetEncodedResponse::mutable_angle ()
mutable_angle() [2/2]
google::protobuf::RepeatedField< double > * iCubInterfaceMessages::AllTargetEncodedResponse::mutable_angle () inline
Definition at line 3915 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/4]
AllTargetEncodedResponse* iCubInterfaceMessages::AllTargetEncodedResponse::New () const inline final
Definition at line 2622 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
AllTargetEncodedResponse* iCubInterfaceMessages::AllTargetEncodedResponse::New () const inline final
Definition at line 2622 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
AllTargetEncodedResponse* iCubInterfaceMessages::AllTargetEncodedResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 2626 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
AllTargetEncodedResponse* iCubInterfaceMessages::AllTargetEncodedResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 2626 of file iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
AllTargetEncodedResponse& iCubInterfaceMessages::AllTargetEncodedResponse::operator= (const AllTargetEncodedResponse & from) inline
Definition at line 2585 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
AllTargetEncodedResponse& iCubInterfaceMessages::AllTargetEncodedResponse::operator= (const AllTargetEncodedResponse & from) inline
Definition at line 2585 of file iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 6474 of file icub.pb.cc.
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_angle() [1/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::set_angle (int index, double value)
set_angle() [2/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::set_angle (int index, double value) inline
Definition at line 3901 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
set_status() [1/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::set_status (::iCubInterfaceMessages::Status value)
set_status() [2/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 3884 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status() [1/2]
iCubInterfaceMessages::Status iCubInterfaceMessages::AllTargetEncodedResponse::status () const inline
Definition at line 3880 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
status() [2/2]
::iCubInterfaceMessages::Status iCubInterfaceMessages::AllTargetEncodedResponse::status () const
Swap() [1/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::Swap (AllTargetEncodedResponse * other)
Definition at line 6618 of file icub.pb.cc.
Swap() [2/2]
void iCubInterfaceMessages::AllTargetEncodedResponse::Swap (AllTargetEncodedResponse * other)
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 2691 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (AllTargetEncodedResponse & a, AllTargetEncodedResponse & b) friend
Definition at line 2616 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (AllTargetEncodedResponse & a, AllTargetEncodedResponse & b) friend
Definition at line 2616 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kAngleFieldNumber
static const int iCubInterfaceMessages::AllTargetEncodedResponse::kAngleFieldNumber = 2 static
Definition at line 2668 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::AllTargetEncodedResponse::kIndexInFileMessages static constexpr
Initial value:
=
    22
Definition at line 2612 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kStatusFieldNumber
static const int iCubInterfaceMessages::AllTargetEncodedResponse::kStatusFieldNumber = 1 static
Definition at line 2679 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc