ANNarchy iCub Interface: iCubInterfaceMessages::SkinResponse Class Reference
iCubInterfaceMessages::SkinResponse Class Reference
#include <icub.pb.h>
Public Member Functions
SkinResponse ()
virtual ~SkinResponse ()
SkinResponse (const SkinResponse &from)
SkinResponse & operator= (const SkinResponse &from)
void Swap (SkinResponse *other)
SkinResponse * New () const final
SkinResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SkinResponse &from)
void MergeFrom (const SkinResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int sensor_data_size () const
void clear_sensor_data ()
double sensor_data (int index) const
void set_sensor_data (int index, double value)
void add_sensor_data (double value)
const ::google::protobuf::RepeatedField< double > & sensor_data () const
::google::protobuf::RepeatedField< double > * mutable_sensor_data ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SkinResponse & default_instance ()
static void InitAsDefaultInstance ()
static const SkinResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kSensorDataFieldNumber = 2
static const int kStatusFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (SkinResponse &a, SkinResponse &b)
Detailed Description
Definition at line 2806 of file icub.pb.h.
Constructor & Destructor Documentation
SkinResponse() [1/2]
iCubInterfaceMessages::SkinResponse::SkinResponse ()
Definition at line 6886 of file icub.pb.cc.
~SkinResponse()
iCubInterfaceMessages::SkinResponse::~SkinResponse () virtual
Definition at line 6906 of file icub.pb.cc.
SkinResponse() [2/2]
iCubInterfaceMessages::SkinResponse::SkinResponse (const SkinResponse & from)
Definition at line 6893 of file icub.pb.cc.
Member Function Documentation
add_sensor_data()
void iCubInterfaceMessages::SkinResponse::add_sensor_data (double value) inline
Definition at line 4010 of file icub.pb.h.
ByteSizeLong()
size_t iCubInterfaceMessages::SkinResponse::ByteSizeLong () const final
Definition at line 7065 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::SkinResponse::Clear () final
Definition at line 6928 of file icub.pb.cc.
Referenced by CopyFrom().
clear_sensor_data()
void iCubInterfaceMessages::SkinResponse::clear_sensor_data () inline
Definition at line 3999 of file icub.pb.h.
clear_status()
void iCubInterfaceMessages::SkinResponse::clear_status () inline
Definition at line 3982 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::SkinResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 7129 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::SkinResponse::CopyFrom (const SkinResponse & from)
Definition at line 7136 of file icub.pb.cc.
default_instance()
const SkinResponse & iCubInterfaceMessages::SkinResponse::default_instance () static
Definition at line 6922 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::SkinResponse::descriptor () static
Definition at line 6917 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::SkinResponse::GetCachedSize () const inline final
Definition at line 2871 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::SkinResponse::GetMetadata () const final
Definition at line 7158 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::SkinResponse::InitAsDefaultInstance () static
Definition at line 6879 of file icub.pb.cc.
internal_default_instance()
static const SkinResponse* iCubInterfaceMessages::SkinResponse::internal_default_instance () inline static
Definition at line 2836 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::SkinResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 7031 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::SkinResponse::IsInitialized () const final
Definition at line 7143 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::SkinResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 7101 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::SkinResponse::MergeFrom (const SkinResponse & from)
Definition at line 7116 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::SkinResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 6939 of file icub.pb.cc.
mutable_sensor_data()
google::protobuf::RepeatedField< double > * iCubInterfaceMessages::SkinResponse::mutable_sensor_data () inline
Definition at line 4020 of file icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/2]
SkinResponse* iCubInterfaceMessages::SkinResponse::New () const inline final
Definition at line 2850 of file icub.pb.h.
New() [2/2]
SkinResponse* iCubInterfaceMessages::SkinResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 2854 of file icub.pb.h.
operator=()
SkinResponse& iCubInterfaceMessages::SkinResponse::operator= (const SkinResponse & from) inline
Definition at line 2813 of file icub.pb.h.
sensor_data() [1/2]
const ::google::protobuf::RepeatedField< double > & iCubInterfaceMessages::SkinResponse::sensor_data () const inline
Definition at line 4015 of file icub.pb.h.
Referenced by SerializeWithCachedSizes().
sensor_data() [2/2]
double iCubInterfaceMessages::SkinResponse::sensor_data (int index) const inline
Definition at line 4002 of file icub.pb.h.
Referenced by ClientInstance::retrieve_skin_arm(), ClientInstance::retrieve_skin_forearm(), and ClientInstance::retrieve_skin_hand().
sensor_data_size()
int iCubInterfaceMessages::SkinResponse::sensor_data_size () const inline
Definition at line 3996 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
SerializeWithCachedSizes()
void iCubInterfaceMessages::SkinResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 7003 of file icub.pb.cc.
set_sensor_data()
void iCubInterfaceMessages::SkinResponse::set_sensor_data (int index, double value) inline
Definition at line 4006 of file icub.pb.h.
set_status()
void iCubInterfaceMessages::SkinResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 3989 of file icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status()
iCubInterfaceMessages::Status iCubInterfaceMessages::SkinResponse::status () const inline
Definition at line 3985 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
Swap()
void iCubInterfaceMessages::SkinResponse::Swap (SkinResponse * other)
Definition at line 7147 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 2919 of file icub.pb.h.
swap
void swap (SkinResponse & a, SkinResponse & b) friend
Definition at line 2844 of file icub.pb.h.
Member Data Documentation
kIndexInFileMessages
constexpr int iCubInterfaceMessages::SkinResponse::kIndexInFileMessages static constexpr
Initial value:
=
    24
Definition at line 2840 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kSensorDataFieldNumber
const int iCubInterfaceMessages::SkinResponse::kSensorDataFieldNumber = 2 static
Definition at line 2896 of file icub.pb.h.
kStatusFieldNumber
const int iCubInterfaceMessages::SkinResponse::kStatusFieldNumber = 1 static
Definition at line 2907 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc