ANNarchy iCub Interface: iCubInterfaceMessages::WriteOutput::Stub Class Reference
iCubInterfaceMessages::WriteOutput::Stub Class Reference final
#include <icub.grpc.pb.h>
Classes
class experimental_async
Public Member Functions
Stub (const std::shared_ptr< ::grpc::ChannelInterface > &channel)
::grpc::Status WriteSingleTarget (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetRequest &request, ::iCubInterfaceMessages::SingleTargetResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetResponse > > AsyncWriteSingleTarget (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetResponse > > PrepareAsyncWriteSingleTarget (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status WriteSingleTargetEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest &request, ::iCubInterfaceMessages::SingleTargetEncodedResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetEncodedResponse > > AsyncWriteSingleTargetEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetEncodedResponse > > PrepareAsyncWriteSingleTargetEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status WriteMultiTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetRequest &request, ::iCubInterfaceMessages::MultiTargetResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetResponse > > AsyncWriteMultiTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetResponse > > PrepareAsyncWriteMultiTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status WriteMultiTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest &request, ::iCubInterfaceMessages::MultiTargetEncodedResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetEncodedResponse > > AsyncWriteMultiTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetEncodedResponse > > PrepareAsyncWriteMultiTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status WriteAllTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetRequest &request, ::iCubInterfaceMessages::AllTargetResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetResponse > > AsyncWriteAllTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetResponse > > PrepareAsyncWriteAllTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status WriteAllTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetEncodedRequest &request, ::iCubInterfaceMessages::AllTargetEncodedResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetEncodedResponse > > AsyncWriteAllTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetEncodedResponse > > PrepareAsyncWriteAllTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
class experimental_async_interface * experimental_async () override
Stub (const std::shared_ptr< ::grpc::ChannelInterface > &channel)
::grpc::Status WriteSingleTarget (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetRequest &request, ::iCubInterfaceMessages::SingleTargetResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetResponse > > AsyncWriteSingleTarget (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetResponse > > PrepareAsyncWriteSingleTarget (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status WriteSingleTargetEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest &request, ::iCubInterfaceMessages::SingleTargetEncodedResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetEncodedResponse > > AsyncWriteSingleTargetEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetEncodedResponse > > PrepareAsyncWriteSingleTargetEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status WriteMultiTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetRequest &request, ::iCubInterfaceMessages::MultiTargetResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetResponse > > AsyncWriteMultiTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetResponse > > PrepareAsyncWriteMultiTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status WriteMultiTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest &request, ::iCubInterfaceMessages::MultiTargetEncodedResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetEncodedResponse > > AsyncWriteMultiTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetEncodedResponse > > PrepareAsyncWriteMultiTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status WriteAllTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetRequest &request, ::iCubInterfaceMessages::AllTargetResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetResponse > > AsyncWriteAllTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetResponse > > PrepareAsyncWriteAllTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetRequest &request, ::grpc::CompletionQueue *cq)
::grpc::Status WriteAllTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetEncodedRequest &request, ::iCubInterfaceMessages::AllTargetEncodedResponse *response) override
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetEncodedResponse > > AsyncWriteAllTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetEncodedResponse > > PrepareAsyncWriteAllTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
class experimental_async_interface * experimental_async () override
Public Member Functions inherited from iCubInterfaceMessages::WriteOutput::StubInterface
virtual ~StubInterface ()
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SingleTargetResponse > > AsyncWriteSingleTarget (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SingleTargetResponse > > PrepareAsyncWriteSingleTarget (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SingleTargetEncodedResponse > > AsyncWriteSingleTargetEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SingleTargetEncodedResponse > > PrepareAsyncWriteSingleTargetEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::MultiTargetResponse > > AsyncWriteMultiTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::MultiTargetResponse > > PrepareAsyncWriteMultiTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::MultiTargetEncodedResponse > > AsyncWriteMultiTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::MultiTargetEncodedResponse > > PrepareAsyncWriteMultiTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::AllTargetResponse > > AsyncWriteAllTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::AllTargetResponse > > PrepareAsyncWriteAllTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::AllTargetEncodedResponse > > AsyncWriteAllTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::AllTargetEncodedResponse > > PrepareAsyncWriteAllTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
virtual ~StubInterface ()
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SingleTargetResponse > > AsyncWriteSingleTarget (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SingleTargetResponse > > PrepareAsyncWriteSingleTarget (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SingleTargetEncodedResponse > > AsyncWriteSingleTargetEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::SingleTargetEncodedResponse > > PrepareAsyncWriteSingleTargetEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::MultiTargetResponse > > AsyncWriteMultiTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::MultiTargetResponse > > PrepareAsyncWriteMultiTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::MultiTargetEncodedResponse > > AsyncWriteMultiTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::MultiTargetEncodedResponse > > PrepareAsyncWriteMultiTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::AllTargetResponse > > AsyncWriteAllTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::AllTargetResponse > > PrepareAsyncWriteAllTargets (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::AllTargetEncodedResponse > > AsyncWriteAllTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iCubInterfaceMessages::AllTargetEncodedResponse > > PrepareAsyncWriteAllTargetsEncoded (::grpc::ClientContext *context, const ::iCubInterfaceMessages::AllTargetEncodedRequest &request, ::grpc::CompletionQueue *cq)
Detailed Description
Definition at line 1081 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
Constructor & Destructor Documentation
Stub() [1/2]
iCubInterfaceMessages::WriteOutput::Stub::Stub (const std::shared_ptr< ::grpc::ChannelInterface > & channel)
Definition at line 324 of file icub.grpc.pb.cc.
Stub() [2/2]
iCubInterfaceMessages::WriteOutput::Stub::Stub (const std::shared_ptr< ::grpc::ChannelInterface > & channel)
Member Function Documentation
AsyncWriteAllTargets() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetResponse> > iCubInterfaceMessages::WriteOutput::Stub::AsyncWriteAllTargets (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllTargetRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1113 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncWriteAllTargets() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetResponse> > iCubInterfaceMessages::WriteOutput::Stub::AsyncWriteAllTargets (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllTargetRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1113 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncWriteAllTargetsEncoded() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetEncodedResponse> > iCubInterfaceMessages::WriteOutput::Stub::AsyncWriteAllTargetsEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllTargetEncodedRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1120 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncWriteAllTargetsEncoded() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetEncodedResponse> > iCubInterfaceMessages::WriteOutput::Stub::AsyncWriteAllTargetsEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllTargetEncodedRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1120 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncWriteMultiTargets() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetResponse> > iCubInterfaceMessages::WriteOutput::Stub::AsyncWriteMultiTargets (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiTargetRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1099 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncWriteMultiTargets() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetResponse> > iCubInterfaceMessages::WriteOutput::Stub::AsyncWriteMultiTargets (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiTargetRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1099 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncWriteMultiTargetsEncoded() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetEncodedResponse> > iCubInterfaceMessages::WriteOutput::Stub::AsyncWriteMultiTargetsEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1106 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncWriteMultiTargetsEncoded() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetEncodedResponse> > iCubInterfaceMessages::WriteOutput::Stub::AsyncWriteMultiTargetsEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1106 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncWriteSingleTarget() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetResponse> > iCubInterfaceMessages::WriteOutput::Stub::AsyncWriteSingleTarget (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleTargetRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1085 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncWriteSingleTarget() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetResponse> > iCubInterfaceMessages::WriteOutput::Stub::AsyncWriteSingleTarget (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleTargetRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1085 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncWriteSingleTargetEncoded() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetEncodedResponse> > iCubInterfaceMessages::WriteOutput::Stub::AsyncWriteSingleTargetEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1092 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
AsyncWriteSingleTargetEncoded() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetEncodedResponse> > iCubInterfaceMessages::WriteOutput::Stub::AsyncWriteSingleTargetEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1092 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
experimental_async() [1/2]
class experimental_async_interface* iCubInterfaceMessages::WriteOutput::Stub::experimental_async () inline override virtual
Reimplemented from iCubInterfaceMessages::WriteOutput::StubInterface.
Definition at line 1141 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
experimental_async() [2/2]
class experimental_async_interface* iCubInterfaceMessages::WriteOutput::Stub::experimental_async () inline override virtual
Reimplemented from iCubInterfaceMessages::WriteOutput::StubInterface.
Definition at line 1141 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncWriteAllTargets() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetResponse> > iCubInterfaceMessages::WriteOutput::Stub::PrepareAsyncWriteAllTargets (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllTargetRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1116 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncWriteAllTargets() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetResponse> > iCubInterfaceMessages::WriteOutput::Stub::PrepareAsyncWriteAllTargets (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllTargetRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1116 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncWriteAllTargetsEncoded() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetEncodedResponse> > iCubInterfaceMessages::WriteOutput::Stub::PrepareAsyncWriteAllTargetsEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllTargetEncodedRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1123 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncWriteAllTargetsEncoded() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::AllTargetEncodedResponse> > iCubInterfaceMessages::WriteOutput::Stub::PrepareAsyncWriteAllTargetsEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllTargetEncodedRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1123 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncWriteMultiTargets() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetResponse> > iCubInterfaceMessages::WriteOutput::Stub::PrepareAsyncWriteMultiTargets (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiTargetRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1102 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncWriteMultiTargets() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetResponse> > iCubInterfaceMessages::WriteOutput::Stub::PrepareAsyncWriteMultiTargets (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiTargetRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1102 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncWriteMultiTargetsEncoded() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetEncodedResponse> > iCubInterfaceMessages::WriteOutput::Stub::PrepareAsyncWriteMultiTargetsEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1109 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncWriteMultiTargetsEncoded() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::MultiTargetEncodedResponse> > iCubInterfaceMessages::WriteOutput::Stub::PrepareAsyncWriteMultiTargetsEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1109 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncWriteSingleTarget() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetResponse> > iCubInterfaceMessages::WriteOutput::Stub::PrepareAsyncWriteSingleTarget (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleTargetRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1088 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncWriteSingleTarget() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetResponse> > iCubInterfaceMessages::WriteOutput::Stub::PrepareAsyncWriteSingleTarget (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleTargetRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1088 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncWriteSingleTargetEncoded() [1/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetEncodedResponse> > iCubInterfaceMessages::WriteOutput::Stub::PrepareAsyncWriteSingleTargetEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1095 of file iCub_ANN_Interface/grpc/icub.grpc.pb.h.
PrepareAsyncWriteSingleTargetEncoded() [2/2]
std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iCubInterfaceMessages::SingleTargetEncodedResponse> > iCubInterfaceMessages::WriteOutput::Stub::PrepareAsyncWriteSingleTargetEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest & request, ::grpc::CompletionQueue * cq) inline
Definition at line 1095 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
WriteAllTargets() [1/2]
::grpc::Status iCubInterfaceMessages::WriteOutput::Stub::WriteAllTargets (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllTargetRequest & request, ::iCubInterfaceMessages::AllTargetResponse * response) override virtual
Implements iCubInterfaceMessages::WriteOutput::StubInterface.
WriteAllTargets() [2/2]
grpc::Status iCubInterfaceMessages::WriteOutput::Stub::WriteAllTargets (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllTargetRequest & request, ::iCubInterfaceMessages::AllTargetResponse * response) override virtual
Implements iCubInterfaceMessages::WriteOutput::StubInterface.
Definition at line 397 of file icub.grpc.pb.cc.
Referenced by WriteClientInstance::retrieve_alltarget().
WriteAllTargetsEncoded() [1/2]
::grpc::Status iCubInterfaceMessages::WriteOutput::Stub::WriteAllTargetsEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllTargetEncodedRequest & request, ::iCubInterfaceMessages::AllTargetEncodedResponse * response) override virtual
Implements iCubInterfaceMessages::WriteOutput::StubInterface.
WriteAllTargetsEncoded() [2/2]
grpc::Status iCubInterfaceMessages::WriteOutput::Stub::WriteAllTargetsEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::AllTargetEncodedRequest & request, ::iCubInterfaceMessages::AllTargetEncodedResponse * response) override virtual
Implements iCubInterfaceMessages::WriteOutput::StubInterface.
Definition at line 413 of file icub.grpc.pb.cc.
Referenced by WriteClientInstance::retrieve_alltarget_enc().
WriteMultiTargets() [1/2]
::grpc::Status iCubInterfaceMessages::WriteOutput::Stub::WriteMultiTargets (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiTargetRequest & request, ::iCubInterfaceMessages::MultiTargetResponse * response) override virtual
Implements iCubInterfaceMessages::WriteOutput::StubInterface.
WriteMultiTargets() [2/2]
grpc::Status iCubInterfaceMessages::WriteOutput::Stub::WriteMultiTargets (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiTargetRequest & request, ::iCubInterfaceMessages::MultiTargetResponse * response) override virtual
Implements iCubInterfaceMessages::WriteOutput::StubInterface.
Definition at line 365 of file icub.grpc.pb.cc.
Referenced by WriteClientInstance::retrieve_multitarget().
WriteMultiTargetsEncoded() [1/2]
grpc::Status iCubInterfaceMessages::WriteOutput::Stub::WriteMultiTargetsEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest & request, ::iCubInterfaceMessages::MultiTargetEncodedResponse * response) override virtual
Implements iCubInterfaceMessages::WriteOutput::StubInterface.
Definition at line 381 of file icub.grpc.pb.cc.
Referenced by WriteClientInstance::retrieve_multitarget_enc().
WriteMultiTargetsEncoded() [2/2]
::grpc::Status iCubInterfaceMessages::WriteOutput::Stub::WriteMultiTargetsEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest & request, ::iCubInterfaceMessages::MultiTargetEncodedResponse * response) override virtual
Implements iCubInterfaceMessages::WriteOutput::StubInterface.
WriteSingleTarget() [1/2]
::grpc::Status iCubInterfaceMessages::WriteOutput::Stub::WriteSingleTarget (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleTargetRequest & request, ::iCubInterfaceMessages::SingleTargetResponse * response) override virtual
Implements iCubInterfaceMessages::WriteOutput::StubInterface.
WriteSingleTarget() [2/2]
grpc::Status iCubInterfaceMessages::WriteOutput::Stub::WriteSingleTarget (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleTargetRequest & request, ::iCubInterfaceMessages::SingleTargetResponse * response) override virtual
Implements iCubInterfaceMessages::WriteOutput::StubInterface.
Definition at line 333 of file icub.grpc.pb.cc.
Referenced by WriteClientInstance::retrieve_singletarget().
WriteSingleTargetEncoded() [1/2]
grpc::Status iCubInterfaceMessages::WriteOutput::Stub::WriteSingleTargetEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest & request, ::iCubInterfaceMessages::SingleTargetEncodedResponse * response) override virtual
Implements iCubInterfaceMessages::WriteOutput::StubInterface.
Definition at line 349 of file icub.grpc.pb.cc.
Referenced by WriteClientInstance::retrieve_singletarget_enc().
WriteSingleTargetEncoded() [2/2]
::grpc::Status iCubInterfaceMessages::WriteOutput::Stub::WriteSingleTargetEncoded (::grpc::ClientContext * context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest & request, ::iCubInterfaceMessages::SingleTargetEncodedResponse * response) override virtual
Implements iCubInterfaceMessages::WriteOutput::StubInterface.
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h
icub.grpc.pb.cc