ANNarchy iCub Interface: iCubInterfaceMessages::AllJointsResponse Class Reference
iCubInterfaceMessages::AllJointsResponse Class Reference
#include <icub.pb.h>
Public Member Functions
AllJointsResponse ()
virtual ~AllJointsResponse ()
AllJointsResponse (const AllJointsResponse &from)
AllJointsResponse & operator= (const AllJointsResponse &from)
void Swap (AllJointsResponse *other)
AllJointsResponse * New () const final
AllJointsResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const AllJointsResponse &from)
void MergeFrom (const AllJointsResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
AllJointsResponse ()
virtual ~AllJointsResponse ()
AllJointsResponse (const AllJointsResponse &from)
AllJointsResponse & operator= (const AllJointsResponse &from)
void Swap (AllJointsResponse *other)
AllJointsResponse * New () const final
AllJointsResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const AllJointsResponse &from)
void MergeFrom (const AllJointsResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const AllJointsResponse & default_instance ()
static void InitAsDefaultInstance ()
static const AllJointsResponse * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const AllJointsResponse & default_instance ()
static void InitAsDefaultInstance ()
static const AllJointsResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kAngleFieldNumber = 2
static const int kStatusFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (AllJointsResponse &a, AllJointsResponse &b)
void swap (AllJointsResponse &a, AllJointsResponse &b)
Detailed Description
Definition at line 1293 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
AllJointsResponse() [1/4]
iCubInterfaceMessages::AllJointsResponse::AllJointsResponse ()
Definition at line 3495 of file icub.pb.cc.
~AllJointsResponse() [1/2]
iCubInterfaceMessages::AllJointsResponse::~AllJointsResponse () virtual
Definition at line 3515 of file icub.pb.cc.
AllJointsResponse() [2/4]
iCubInterfaceMessages::AllJointsResponse::AllJointsResponse (const AllJointsResponse & from)
Definition at line 3502 of file icub.pb.cc.
AllJointsResponse() [3/4]
iCubInterfaceMessages::AllJointsResponse::AllJointsResponse ()
~AllJointsResponse() [2/2]
virtual iCubInterfaceMessages::AllJointsResponse::~AllJointsResponse () virtual
AllJointsResponse() [4/4]
iCubInterfaceMessages::AllJointsResponse::AllJointsResponse (const AllJointsResponse & from)
Member Function Documentation
add_angle() [1/2]
void iCubInterfaceMessages::AllJointsResponse::add_angle (double value) inline
Definition at line 3581 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
add_angle() [2/2]
void iCubInterfaceMessages::AllJointsResponse::add_angle (double value)
angle() [1/4]
const ::google::protobuf::RepeatedField< double > & iCubInterfaceMessages::AllJointsResponse::angle () const inline
Definition at line 3586 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by SerializeWithCachedSizes().
angle() [2/4]
const ::google::protobuf::RepeatedField< double >& iCubInterfaceMessages::AllJointsResponse::angle () const
angle() [3/4]
double iCubInterfaceMessages::AllJointsResponse::angle (int index) const inline
Definition at line 3573 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ClientInstance::retrieve_alljoints().
angle() [4/4]
double iCubInterfaceMessages::AllJointsResponse::angle (int index) const
angle_size() [1/2]
int iCubInterfaceMessages::AllJointsResponse::angle_size () const inline
Definition at line 3567 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
angle_size() [2/2]
int iCubInterfaceMessages::AllJointsResponse::angle_size () const
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::AllJointsResponse::ByteSizeLong () const final
Definition at line 3674 of file icub.pb.cc.
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::AllJointsResponse::ByteSizeLong () const final
Clear() [1/2]
void iCubInterfaceMessages::AllJointsResponse::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::AllJointsResponse::Clear () final
Definition at line 3537 of file icub.pb.cc.
Referenced by CopyFrom().
clear_angle() [1/2]
void iCubInterfaceMessages::AllJointsResponse::clear_angle () inline
Definition at line 3570 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_angle() [2/2]
void iCubInterfaceMessages::AllJointsResponse::clear_angle ()
clear_status() [1/2]
void iCubInterfaceMessages::AllJointsResponse::clear_status () inline
Definition at line 3553 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_status() [2/2]
void iCubInterfaceMessages::AllJointsResponse::clear_status ()
CopyFrom() [1/4]
void iCubInterfaceMessages::AllJointsResponse::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/4]
void iCubInterfaceMessages::AllJointsResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 3738 of file icub.pb.cc.
CopyFrom() [3/4]
void iCubInterfaceMessages::AllJointsResponse::CopyFrom (const AllJointsResponse & from)
CopyFrom() [4/4]
void iCubInterfaceMessages::AllJointsResponse::CopyFrom (const AllJointsResponse & from)
Definition at line 3745 of file icub.pb.cc.
default_instance() [1/2]
static const AllJointsResponse& iCubInterfaceMessages::AllJointsResponse::default_instance () static
default_instance() [2/2]
const AllJointsResponse & iCubInterfaceMessages::AllJointsResponse::default_instance () static
Definition at line 3531 of file icub.pb.cc.
descriptor() [1/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::AllJointsResponse::descriptor () static
descriptor() [2/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::AllJointsResponse::descriptor () static
Definition at line 3526 of file icub.pb.cc.
GetCachedSize() [1/2]
int iCubInterfaceMessages::AllJointsResponse::GetCachedSize () const inline final
Definition at line 1358 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::AllJointsResponse::GetCachedSize () const inline final
Definition at line 1358 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
google::protobuf::Metadata iCubInterfaceMessages::AllJointsResponse::GetMetadata () const final
Definition at line 3767 of file icub.pb.cc.
GetMetadata() [2/2]
::google::protobuf::Metadata iCubInterfaceMessages::AllJointsResponse::GetMetadata () const final
InitAsDefaultInstance() [1/2]
static void iCubInterfaceMessages::AllJointsResponse::InitAsDefaultInstance () static
InitAsDefaultInstance() [2/2]
void iCubInterfaceMessages::AllJointsResponse::InitAsDefaultInstance () static
Definition at line 3488 of file icub.pb.cc.
internal_default_instance() [1/2]
static const AllJointsResponse* iCubInterfaceMessages::AllJointsResponse::internal_default_instance () inline static
Definition at line 1323 of file iCub_ANN_Interface/grpc/icub.pb.h.
internal_default_instance() [2/2]
static const AllJointsResponse* iCubInterfaceMessages::AllJointsResponse::internal_default_instance () inline static
Definition at line 1323 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::AllJointsResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 3640 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::AllJointsResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::AllJointsResponse::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::AllJointsResponse::IsInitialized () const final
Definition at line 3752 of file icub.pb.cc.
MergeFrom() [1/4]
void iCubInterfaceMessages::AllJointsResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 3710 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/4]
void iCubInterfaceMessages::AllJointsResponse::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [3/4]
void iCubInterfaceMessages::AllJointsResponse::MergeFrom (const AllJointsResponse & from)
MergeFrom() [4/4]
void iCubInterfaceMessages::AllJointsResponse::MergeFrom (const AllJointsResponse & from)
Definition at line 3725 of file icub.pb.cc.
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::AllJointsResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 3548 of file icub.pb.cc.
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::AllJointsResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_angle() [1/2]
::google::protobuf::RepeatedField< double >* iCubInterfaceMessages::AllJointsResponse::mutable_angle ()
mutable_angle() [2/2]
google::protobuf::RepeatedField< double > * iCubInterfaceMessages::AllJointsResponse::mutable_angle () inline
Definition at line 3591 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/4]
AllJointsResponse* iCubInterfaceMessages::AllJointsResponse::New () const inline final
Definition at line 1337 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
AllJointsResponse* iCubInterfaceMessages::AllJointsResponse::New () const inline final
Definition at line 1337 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
AllJointsResponse* iCubInterfaceMessages::AllJointsResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1341 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
AllJointsResponse* iCubInterfaceMessages::AllJointsResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1341 of file iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
AllJointsResponse& iCubInterfaceMessages::AllJointsResponse::operator= (const AllJointsResponse & from) inline
Definition at line 1300 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
AllJointsResponse& iCubInterfaceMessages::AllJointsResponse::operator= (const AllJointsResponse & from) inline
Definition at line 1300 of file iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::AllJointsResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 3612 of file icub.pb.cc.
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::AllJointsResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_angle() [1/2]
void iCubInterfaceMessages::AllJointsResponse::set_angle (int index, double value)
set_angle() [2/2]
void iCubInterfaceMessages::AllJointsResponse::set_angle (int index, double value) inline
Definition at line 3577 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
set_status() [1/2]
void iCubInterfaceMessages::AllJointsResponse::set_status (::iCubInterfaceMessages::Status value)
set_status() [2/2]
void iCubInterfaceMessages::AllJointsResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 3560 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status() [1/2]
iCubInterfaceMessages::Status iCubInterfaceMessages::AllJointsResponse::status () const inline
Definition at line 3556 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
status() [2/2]
::iCubInterfaceMessages::Status iCubInterfaceMessages::AllJointsResponse::status () const
Swap() [1/2]
void iCubInterfaceMessages::AllJointsResponse::Swap (AllJointsResponse * other)
Definition at line 3756 of file icub.pb.cc.
Swap() [2/2]
void iCubInterfaceMessages::AllJointsResponse::Swap (AllJointsResponse * other)
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 1406 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (AllJointsResponse & a, AllJointsResponse & b) friend
Definition at line 1331 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (AllJointsResponse & a, AllJointsResponse & b) friend
Definition at line 1331 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kAngleFieldNumber
static const int iCubInterfaceMessages::AllJointsResponse::kAngleFieldNumber = 2 static
Definition at line 1383 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::AllJointsResponse::kIndexInFileMessages static constexpr
Initial value:
=
    10
Definition at line 1327 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kStatusFieldNumber
static const int iCubInterfaceMessages::AllJointsResponse::kStatusFieldNumber = 1 static
Definition at line 1394 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc