ANNarchy iCub Interface: iCubInterfaceMessages::SkinArmRequest Class Reference
iCubInterfaceMessages::SkinArmRequest Class Reference
#include <icub.pb.h>
Public Member Functions
SkinArmRequest ()
virtual ~SkinArmRequest ()
SkinArmRequest (const SkinArmRequest &from)
SkinArmRequest & operator= (const SkinArmRequest &from)
void Swap (SkinArmRequest *other)
SkinArmRequest * New () const final
SkinArmRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SkinArmRequest &from)
void MergeFrom (const SkinArmRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
SkinArmRequest ()
virtual ~SkinArmRequest ()
SkinArmRequest (const SkinArmRequest &from)
SkinArmRequest & operator= (const SkinArmRequest &from)
void Swap (SkinArmRequest *other)
SkinArmRequest * New () const final
SkinArmRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SkinArmRequest &from)
void MergeFrom (const SkinArmRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SkinArmRequest & default_instance ()
static void InitAsDefaultInstance ()
static const SkinArmRequest * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const SkinArmRequest & default_instance ()
static void InitAsDefaultInstance ()
static const SkinArmRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (SkinArmRequest &a, SkinArmRequest &b)
void swap (SkinArmRequest &a, SkinArmRequest &b)
Detailed Description
Definition at line 2923 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
SkinArmRequest() [1/4]
iCubInterfaceMessages::SkinArmRequest::SkinArmRequest ()
Definition at line 7171 of file icub.pb.cc.
~SkinArmRequest() [1/2]
iCubInterfaceMessages::SkinArmRequest::~SkinArmRequest () virtual
Definition at line 7188 of file icub.pb.cc.
SkinArmRequest() [2/4]
iCubInterfaceMessages::SkinArmRequest::SkinArmRequest (const SkinArmRequest & from)
Definition at line 7178 of file icub.pb.cc.
SkinArmRequest() [3/4]
iCubInterfaceMessages::SkinArmRequest::SkinArmRequest ()
~SkinArmRequest() [2/2]
virtual iCubInterfaceMessages::SkinArmRequest::~SkinArmRequest () virtual
SkinArmRequest() [4/4]
iCubInterfaceMessages::SkinArmRequest::SkinArmRequest (const SkinArmRequest & from)
Member Function Documentation
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::SkinArmRequest::ByteSizeLong () const final
Definition at line 7272 of file icub.pb.cc.
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::SkinArmRequest::ByteSizeLong () const final
Clear() [1/2]
void iCubInterfaceMessages::SkinArmRequest::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::SkinArmRequest::Clear () final
Definition at line 7210 of file icub.pb.cc.
Referenced by CopyFrom().
CopyFrom() [1/4]
void iCubInterfaceMessages::SkinArmRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 7310 of file icub.pb.cc.
CopyFrom() [2/4]
void iCubInterfaceMessages::SkinArmRequest::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [3/4]
void iCubInterfaceMessages::SkinArmRequest::CopyFrom (const SkinArmRequest & from)
Definition at line 7317 of file icub.pb.cc.
CopyFrom() [4/4]
void iCubInterfaceMessages::SkinArmRequest::CopyFrom (const SkinArmRequest & from)
default_instance() [1/2]
const SkinArmRequest & iCubInterfaceMessages::SkinArmRequest::default_instance () static
Definition at line 7204 of file icub.pb.cc.
default_instance() [2/2]
static const SkinArmRequest& iCubInterfaceMessages::SkinArmRequest::default_instance () static
descriptor() [1/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::SkinArmRequest::descriptor () static
descriptor() [2/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::SkinArmRequest::descriptor () static
Definition at line 7199 of file icub.pb.cc.
GetCachedSize() [1/2]
int iCubInterfaceMessages::SkinArmRequest::GetCachedSize () const inline final
Definition at line 2988 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::SkinArmRequest::GetCachedSize () const inline final
Definition at line 2988 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
google::protobuf::Metadata iCubInterfaceMessages::SkinArmRequest::GetMetadata () const final
Definition at line 7337 of file icub.pb.cc.
GetMetadata() [2/2]
::google::protobuf::Metadata iCubInterfaceMessages::SkinArmRequest::GetMetadata () const final
InitAsDefaultInstance() [1/2]
void iCubInterfaceMessages::SkinArmRequest::InitAsDefaultInstance () static
Definition at line 7166 of file icub.pb.cc.
InitAsDefaultInstance() [2/2]
static void iCubInterfaceMessages::SkinArmRequest::InitAsDefaultInstance () static
internal_default_instance() [1/2]
static const SkinArmRequest* iCubInterfaceMessages::SkinArmRequest::internal_default_instance () inline static
Definition at line 2953 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
internal_default_instance() [2/2]
static const SkinArmRequest* iCubInterfaceMessages::SkinArmRequest::internal_default_instance () inline static
Definition at line 2953 of file iCub_ANN_Interface/grpc/icub.pb.h.
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::SkinArmRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 7257 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::SkinArmRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::SkinArmRequest::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::SkinArmRequest::IsInitialized () const final
Definition at line 7324 of file icub.pb.cc.
MergeFrom() [1/4]
void iCubInterfaceMessages::SkinArmRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 7286 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/4]
void iCubInterfaceMessages::SkinArmRequest::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [3/4]
void iCubInterfaceMessages::SkinArmRequest::MergeFrom (const SkinArmRequest & from)
MergeFrom() [4/4]
void iCubInterfaceMessages::SkinArmRequest::MergeFrom (const SkinArmRequest & from)
Definition at line 7301 of file icub.pb.cc.
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::SkinArmRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::SkinArmRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 7219 of file icub.pb.cc.
New() [1/4]
SkinArmRequest* iCubInterfaceMessages::SkinArmRequest::New () const inline final
Definition at line 2967 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
SkinArmRequest* iCubInterfaceMessages::SkinArmRequest::New () const inline final
Definition at line 2967 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
SkinArmRequest* iCubInterfaceMessages::SkinArmRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 2971 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
SkinArmRequest* iCubInterfaceMessages::SkinArmRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 2971 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
SkinArmRequest& iCubInterfaceMessages::SkinArmRequest::operator= (const SkinArmRequest & from) inline
Definition at line 2930 of file iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
SkinArmRequest& iCubInterfaceMessages::SkinArmRequest::operator= (const SkinArmRequest & from) inline
Definition at line 2930 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::SkinArmRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 7244 of file icub.pb.cc.
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::SkinArmRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Swap() [1/2]
void iCubInterfaceMessages::SkinArmRequest::Swap (SkinArmRequest * other)
Definition at line 7328 of file icub.pb.cc.
Swap() [2/2]
void iCubInterfaceMessages::SkinArmRequest::Swap (SkinArmRequest * other)
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 3015 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (SkinArmRequest & a, SkinArmRequest & b) friend
Definition at line 2961 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (SkinArmRequest & a, SkinArmRequest & b) friend
Definition at line 2961 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::SkinArmRequest::kIndexInFileMessages static constexpr
Initial value:
=
    25
Definition at line 2957 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc