ANNarchy iCub Interface: iCubInterfaceMessages::WriteOutput::Service Class Reference
iCubInterfaceMessages::WriteOutput::Service Class Reference
#include <icub.grpc.pb.h>
Public Member Functions
Service ()
virtual ~Service ()
virtual ::grpc::Status WriteSingleTarget (::grpc::ServerContext *context, const ::iCubInterfaceMessages::SingleTargetRequest *request, ::iCubInterfaceMessages::SingleTargetResponse *response)
virtual ::grpc::Status WriteSingleTargetEncoded (::grpc::ServerContext *context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest *request, ::iCubInterfaceMessages::SingleTargetEncodedResponse *response)
virtual ::grpc::Status WriteMultiTargets (::grpc::ServerContext *context, const ::iCubInterfaceMessages::MultiTargetRequest *request, ::iCubInterfaceMessages::MultiTargetResponse *response)
virtual ::grpc::Status WriteMultiTargetsEncoded (::grpc::ServerContext *context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest *request, ::iCubInterfaceMessages::MultiTargetEncodedResponse *response)
virtual ::grpc::Status WriteAllTargets (::grpc::ServerContext *context, const ::iCubInterfaceMessages::AllTargetRequest *request, ::iCubInterfaceMessages::AllTargetResponse *response)
virtual ::grpc::Status WriteAllTargetsEncoded (::grpc::ServerContext *context, const ::iCubInterfaceMessages::AllTargetEncodedRequest *request, ::iCubInterfaceMessages::AllTargetEncodedResponse *response)
Service ()
virtual ~Service ()
virtual ::grpc::Status WriteSingleTarget (::grpc::ServerContext *context, const ::iCubInterfaceMessages::SingleTargetRequest *request, ::iCubInterfaceMessages::SingleTargetResponse *response)
virtual ::grpc::Status WriteSingleTargetEncoded (::grpc::ServerContext *context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest *request, ::iCubInterfaceMessages::SingleTargetEncodedResponse *response)
virtual ::grpc::Status WriteMultiTargets (::grpc::ServerContext *context, const ::iCubInterfaceMessages::MultiTargetRequest *request, ::iCubInterfaceMessages::MultiTargetResponse *response)
virtual ::grpc::Status WriteMultiTargetsEncoded (::grpc::ServerContext *context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest *request, ::iCubInterfaceMessages::MultiTargetEncodedResponse *response)
virtual ::grpc::Status WriteAllTargets (::grpc::ServerContext *context, const ::iCubInterfaceMessages::AllTargetRequest *request, ::iCubInterfaceMessages::AllTargetResponse *response)
virtual ::grpc::Status WriteAllTargetsEncoded (::grpc::ServerContext *context, const ::iCubInterfaceMessages::AllTargetEncodedRequest *request, ::iCubInterfaceMessages::AllTargetEncodedResponse *response)
Detailed Description
Definition at line 1167 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h.
Constructor & Destructor Documentation
Service() [1/2]
iCubInterfaceMessages::WriteOutput::Service::Service ()
Definition at line 429 of file icub.grpc.pb.cc.
~Service() [1/2]
iCubInterfaceMessages::WriteOutput::Service::~Service () virtual
Definition at line 462 of file icub.grpc.pb.cc.
Service() [2/2]
iCubInterfaceMessages::WriteOutput::Service::Service ()
~Service() [2/2]
virtual iCubInterfaceMessages::WriteOutput::Service::~Service () virtual
Member Function Documentation
WriteAllTargets() [1/2]
grpc::Status iCubInterfaceMessages::WriteOutput::Service::WriteAllTargets (::grpc::ServerContext * context, const ::iCubInterfaceMessages::AllTargetRequest * request, ::iCubInterfaceMessages::AllTargetResponse * response)
Definition at line 493 of file icub.grpc.pb.cc.
Referenced by Service().
WriteAllTargets() [2/2]
virtual ::grpc::Status iCubInterfaceMessages::WriteOutput::Service::WriteAllTargets (::grpc::ServerContext * context, const ::iCubInterfaceMessages::AllTargetRequest * request, ::iCubInterfaceMessages::AllTargetResponse * response)
WriteAllTargetsEncoded() [1/2]
grpc::Status iCubInterfaceMessages::WriteOutput::Service::WriteAllTargetsEncoded (::grpc::ServerContext * context, const ::iCubInterfaceMessages::AllTargetEncodedRequest * request, ::iCubInterfaceMessages::AllTargetEncodedResponse * response)
Definition at line 500 of file icub.grpc.pb.cc.
Referenced by Service().
WriteAllTargetsEncoded() [2/2]
virtual ::grpc::Status iCubInterfaceMessages::WriteOutput::Service::WriteAllTargetsEncoded (::grpc::ServerContext * context, const ::iCubInterfaceMessages::AllTargetEncodedRequest * request, ::iCubInterfaceMessages::AllTargetEncodedResponse * response)
WriteMultiTargets() [1/2]
virtual ::grpc::Status iCubInterfaceMessages::WriteOutput::Service::WriteMultiTargets (::grpc::ServerContext * context, const ::iCubInterfaceMessages::MultiTargetRequest * request, ::iCubInterfaceMessages::MultiTargetResponse * response)
WriteMultiTargets() [2/2]
grpc::Status iCubInterfaceMessages::WriteOutput::Service::WriteMultiTargets (::grpc::ServerContext * context, const ::iCubInterfaceMessages::MultiTargetRequest * request, ::iCubInterfaceMessages::MultiTargetResponse * response)
Definition at line 479 of file icub.grpc.pb.cc.
Referenced by Service().
WriteMultiTargetsEncoded() [1/2]
virtual ::grpc::Status iCubInterfaceMessages::WriteOutput::Service::WriteMultiTargetsEncoded (::grpc::ServerContext * context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest * request, ::iCubInterfaceMessages::MultiTargetEncodedResponse * response)
WriteMultiTargetsEncoded() [2/2]
grpc::Status iCubInterfaceMessages::WriteOutput::Service::WriteMultiTargetsEncoded (::grpc::ServerContext * context, const ::iCubInterfaceMessages::MultiTargetEncodedRequest * request, ::iCubInterfaceMessages::MultiTargetEncodedResponse * response)
Definition at line 486 of file icub.grpc.pb.cc.
Referenced by Service().
WriteSingleTarget() [1/2]
grpc::Status iCubInterfaceMessages::WriteOutput::Service::WriteSingleTarget (::grpc::ServerContext * context, const ::iCubInterfaceMessages::SingleTargetRequest * request, ::iCubInterfaceMessages::SingleTargetResponse * response)
Definition at line 465 of file icub.grpc.pb.cc.
Referenced by Service().
WriteSingleTarget() [2/2]
virtual ::grpc::Status iCubInterfaceMessages::WriteOutput::Service::WriteSingleTarget (::grpc::ServerContext * context, const ::iCubInterfaceMessages::SingleTargetRequest * request, ::iCubInterfaceMessages::SingleTargetResponse * response)
WriteSingleTargetEncoded() [1/2]
virtual ::grpc::Status iCubInterfaceMessages::WriteOutput::Service::WriteSingleTargetEncoded (::grpc::ServerContext * context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest * request, ::iCubInterfaceMessages::SingleTargetEncodedResponse * response)
WriteSingleTargetEncoded() [2/2]
grpc::Status iCubInterfaceMessages::WriteOutput::Service::WriteSingleTargetEncoded (::grpc::ServerContext * context, const ::iCubInterfaceMessages::SingleTargetEncodedRequest * request, ::iCubInterfaceMessages::SingleTargetEncodedResponse * response)
Definition at line 472 of file icub.grpc.pb.cc.
Referenced by Service().
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.grpc.pb.h
icub.grpc.pb.cc