ANNarchy iCub Interface: ini.cpp File Reference
ini.cpp File Reference
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include "ini.h"
Classes
struct ini_parse_string_ctx
Macros
#define MAX_SECTION 50
#define MAX_NAME 50
#define HANDLER(u, s, n, v) handler(u, s, n, v)
Functions
int ini_parse_stream (ini_reader reader, void *stream, ini_handler handler, void *user)
int ini_parse_file (FILE *file, ini_handler handler, void *user)
int ini_parse (const char *filename, ini_handler handler, void *user)
int ini_parse_string (const char *string, ini_handler handler, void *user)
Macro Definition Documentation
HANDLER
#define HANDLER (u, s, n, v) handler(u, s, n, v)
MAX_NAME
#define MAX_NAME 50
Definition at line 27 of file ini.cpp.
MAX_SECTION
#define MAX_SECTION 50
Definition at line 26 of file ini.cpp.
Function Documentation
ini_parse()
int ini_parse (const char * filename, ini_handler handler, void * user)
Definition at line 223 of file ini.cpp.
Referenced by INIReader::INIReader().
ini_parse_file()
int ini_parse_file (FILE * file, ini_handler handler, void * user)
Definition at line 217 of file ini.cpp.
Referenced by ini_parse().
ini_parse_stream()
int ini_parse_stream (ini_reader reader, void * stream, ini_handler handler, void * user)
Definition at line 81 of file ini.cpp.
Referenced by ini_parse_file(), and ini_parse_string().
ini_parse_string()
int ini_parse_string (const char * string, ini_handler handler, void * user)
Definition at line 264 of file ini.cpp.