ANNarchy iCub Interface: iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout Class Reference
iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout Class Reference
Public Member Functions
def __init__ (self, geometry=None, joints=None, encoded=False, ip_address="0.0.0.0", port=50005, copied=False)
def ip_address (self)
def ip_address (self, value)
def port (self)
def port (self, value)
def joints (self)
def joints (self, value)
def encoded (self)
def encoded (self, value)
def connect (self)
Detailed Description
Get the position/orientation of joints, e. g. elbow or finger.
Definition at line 150 of file JointPopulation.py.
Constructor & Destructor Documentation
__init__()
def iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout.__init__ (self, geometry = None, joints = None, encoded = False, ip_address = "0.0.0.0", port = 50005, copied = False)
Definition at line 154 of file JointPopulation.py.
Member Function Documentation
connect()
def iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout.connect (self)
Definition at line 338 of file JointPopulation.py.
encoded() [1/2]
def iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout.encoded (self)
Definition at line 220 of file JointPopulation.py.
Referenced by iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout.encoded().
encoded() [2/2]
def iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout.encoded (self, value)
Definition at line 227 of file JointPopulation.py.
ip_address() [1/2]
def iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout.ip_address (self)
Definition at line 178 of file JointPopulation.py.
Referenced by iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout.ip_address().
ip_address() [2/2]
def iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout.ip_address (self, value)
Definition at line 185 of file JointPopulation.py.
joints() [1/2]
def iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout.joints (self)
Definition at line 206 of file JointPopulation.py.
Referenced by iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout.joints().
joints() [2/2]
def iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout.joints (self, value)
Definition at line 213 of file JointPopulation.py.
port() [1/2]
def iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout.port (self)
Definition at line 192 of file JointPopulation.py.
Referenced by iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout.port().
port() [2/2]
def iCub_ANN_Interface.ANNarchy_iCub_Populations.JointPopulation.JointReadout.port (self, value)
Definition at line 199 of file JointPopulation.py.
The documentation for this class was generated from the following file:
JointPopulation.py