ANNarchy iCub Interface: Mod_BaseClass Class Reference
Mod_BaseClass Class Reference abstract
Base class for the sensor/actor reader/writer modules.
#include <Module_Base_Class.hpp>
Public Member Functions
Mod_BaseClass ()=default
~Mod_BaseClass ()
void setRegister (bool value)
bool getRegister ()
std::string get_identifier ()
virtual void Close ()=0
virtual std::vector< double > provideData ()
virtual std::vector< double > provideData (int value, bool enc)
virtual std::vector< double > provideData (std::vector< int > value, bool enc)
virtual std::vector< double > provideData (bool enc)
virtual std::vector< double > provideData (int value)
Protected Member Functions
bool CheckInit ()
Protected Attributes
bool dev_init = false
bool dev_init_grpc = false
std::string type
std::string icub_part
Detailed Description
Base class for the sensor/actor reader/writer modules.
Definition at line 29 of file Module_Base_Class.hpp.
Constructor & Destructor Documentation
Mod_BaseClass()
Mod_BaseClass::Mod_BaseClass () default
~Mod_BaseClass()
Mod_BaseClass::~Mod_BaseClass ()
Definition at line 26 of file Module_Base_Class.cpp.
Member Function Documentation
CheckInit()
bool Mod_BaseClass::CheckInit () protected
Definition at line 28 of file Module_Base_Class.cpp.
Referenced by JointReader::GetJointCount(), JointWriter::GetJointsDegRes(), JointReader::GetJointsDegRes(), JointWriter::GetNeuronsPerJoint(), JointReader::GetNeuronsPerJoint(), SkinReader::GetTactileArm(), SkinReader::GetTactileForearm(), SkinReader::GetTactileHand(), SkinReader::GetTaxelPos(), JointReader::ReadDoubleAll(), JointReader::ReadDoubleAllTime(), JointReader::ReadDoubleMultiple(), JointReader::ReadDoubleMultipleTime(), JointReader::ReadDoubleOne(), JointReader::ReadDoubleOneTime(), JointReader::ReadPopAll(), JointReader::ReadPopMultiple(), JointReader::ReadPopOne(), VisualReader::ReadRobotEyes(), SkinReader::ReadTactile(), JointWriter::WriteDoubleAll(), JointWriter::WriteDoubleMultiple(), JointWriter::WriteDoubleOne(), JointWriter::WritePopAll(), JointWriter::WritePopMultiple(), and JointWriter::WritePopOne().
Close()
virtual void Mod_BaseClass::Close () pure virtual
Implemented in VisualReader, JointReader, JointWriter, and SkinReader.
get_identifier()
std::string Mod_BaseClass::get_identifier ()
Definition at line 43 of file Module_Base_Class.cpp.
Referenced by ServerInstance::ServerInstance(), and ServerInstance::shutdown().
getRegister()
bool Mod_BaseClass::getRegister ()
Definition at line 41 of file Module_Base_Class.cpp.
provideData() [1/5]
std::vector< double > Mod_BaseClass::provideData () virtual
Definition at line 45 of file Module_Base_Class.cpp.
provideData() [2/5]
std::vector< double > Mod_BaseClass::provideData (bool enc) virtual
Definition at line 60 of file Module_Base_Class.cpp.
provideData() [3/5]
std::vector< double > Mod_BaseClass::provideData (int value) virtual
Definition at line 65 of file Module_Base_Class.cpp.
provideData() [4/5]
std::vector< double > Mod_BaseClass::provideData (int value, bool enc) virtual
Definition at line 50 of file Module_Base_Class.cpp.
provideData() [5/5]
std::vector< double > Mod_BaseClass::provideData (std::vector< int > value, bool enc) virtual
Definition at line 55 of file Module_Base_Class.cpp.
setRegister()
void Mod_BaseClass::setRegister (bool value)
Definition at line 40 of file Module_Base_Class.cpp.
Member Data Documentation
dev_init
bool Mod_BaseClass::dev_init = false protected
Definition at line 37 of file Module_Base_Class.hpp.
Referenced by CheckInit(), JointWriter::Close(), JointReader::Close(), SkinReader::Close(), VisualReader::Close(), JointWriter::Init(), JointReader::Init(), SkinReader::Init(), and VisualReader::Init().
dev_init_grpc
bool Mod_BaseClass::dev_init_grpc = false protected
Definition at line 38 of file Module_Base_Class.hpp.
Referenced by JointReader::Close(), SkinReader::Close(), and VisualReader::Close().
icub_part
std::string Mod_BaseClass::icub_part protected
Definition at line 40 of file Module_Base_Class.hpp.
Referenced by CheckInit(), get_identifier(), JointWriter::Init(), JointReader::Init(), SkinReader::Init(), VisualReader::Init(), JointReader::ReadDoubleOne(), JointReader::ReadDoubleOneTime(), JointReader::ReadPopOne(), JointWriter::SetJointControlMode(), JointWriter::SetJointVelocity(), JointWriter::WriteDoubleAll(), JointWriter::WriteDoubleMultiple(), JointWriter::WriteDoubleOne(), JointWriter::WritePopAll(), JointWriter::WritePopMultiple(), and JointWriter::WritePopOne().
type
std::string Mod_BaseClass::type protected
Definition at line 39 of file Module_Base_Class.hpp.
Referenced by CheckInit(), get_identifier(), JointWriter::Init(), JointReader::Init(), SkinReader::Init(), VisualReader::Init(), and provideData().
The documentation for this class was generated from the following files:
Module_Base_Class.hpp
Module_Base_Class.cpp