ANNarchy iCub Interface: iCubInterfaceMessages::MultiTargetEncodedResponse Class Reference
iCubInterfaceMessages::MultiTargetEncodedResponse Class Reference
#include <icub.pb.h>
Public Member Functions
MultiTargetEncodedResponse ()
virtual ~MultiTargetEncodedResponse ()
MultiTargetEncodedResponse (const MultiTargetEncodedResponse &from)
MultiTargetEncodedResponse & operator= (const MultiTargetEncodedResponse &from)
void Swap (MultiTargetEncodedResponse *other)
MultiTargetEncodedResponse * New () const final
MultiTargetEncodedResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const MultiTargetEncodedResponse &from)
void MergeFrom (const MultiTargetEncodedResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
MultiTargetEncodedResponse ()
virtual ~MultiTargetEncodedResponse ()
MultiTargetEncodedResponse (const MultiTargetEncodedResponse &from)
MultiTargetEncodedResponse & operator= (const MultiTargetEncodedResponse &from)
void Swap (MultiTargetEncodedResponse *other)
MultiTargetEncodedResponse * New () const final
MultiTargetEncodedResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const MultiTargetEncodedResponse &from)
void MergeFrom (const MultiTargetEncodedResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int angle_size () const
void clear_angle ()
double angle (int index) const
void set_angle (int index, double value)
void add_angle (double value)
const ::google::protobuf::RepeatedField< double > & angle () const
::google::protobuf::RepeatedField< double > * mutable_angle ()
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const MultiTargetEncodedResponse & default_instance ()
static void InitAsDefaultInstance ()
static const MultiTargetEncodedResponse * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const MultiTargetEncodedResponse & default_instance ()
static void InitAsDefaultInstance ()
static const MultiTargetEncodedResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kAngleFieldNumber = 2
static const int kStatusFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (MultiTargetEncodedResponse &a, MultiTargetEncodedResponse &b)
void swap (MultiTargetEncodedResponse &a, MultiTargetEncodedResponse &b)
Detailed Description
Definition at line 2365 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
MultiTargetEncodedResponse() [1/4]
iCubInterfaceMessages::MultiTargetEncodedResponse::MultiTargetEncodedResponse ()
Definition at line 5891 of file icub.pb.cc.
~MultiTargetEncodedResponse() [1/2]
iCubInterfaceMessages::MultiTargetEncodedResponse::~MultiTargetEncodedResponse () virtual
Definition at line 5911 of file icub.pb.cc.
MultiTargetEncodedResponse() [2/4]
iCubInterfaceMessages::MultiTargetEncodedResponse::MultiTargetEncodedResponse (const MultiTargetEncodedResponse & from)
Definition at line 5898 of file icub.pb.cc.
MultiTargetEncodedResponse() [3/4]
iCubInterfaceMessages::MultiTargetEncodedResponse::MultiTargetEncodedResponse ()
~MultiTargetEncodedResponse() [2/2]
virtual iCubInterfaceMessages::MultiTargetEncodedResponse::~MultiTargetEncodedResponse () virtual
MultiTargetEncodedResponse() [4/4]
iCubInterfaceMessages::MultiTargetEncodedResponse::MultiTargetEncodedResponse (const MultiTargetEncodedResponse & from)
Member Function Documentation
add_angle() [1/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::add_angle (double value) inline
Definition at line 3853 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
add_angle() [2/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::add_angle (double value)
angle() [1/4]
const ::google::protobuf::RepeatedField< double > & iCubInterfaceMessages::MultiTargetEncodedResponse::angle () const inline
Definition at line 3858 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by SerializeWithCachedSizes().
angle() [2/4]
const ::google::protobuf::RepeatedField< double >& iCubInterfaceMessages::MultiTargetEncodedResponse::angle () const
angle() [3/4]
double iCubInterfaceMessages::MultiTargetEncodedResponse::angle (int index) const inline
Definition at line 3845 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by WriteClientInstance::retrieve_multitarget_enc().
angle() [4/4]
double iCubInterfaceMessages::MultiTargetEncodedResponse::angle (int index) const
angle_size() [1/2]
int iCubInterfaceMessages::MultiTargetEncodedResponse::angle_size () const inline
Definition at line 3839 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
angle_size() [2/2]
int iCubInterfaceMessages::MultiTargetEncodedResponse::angle_size () const
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::MultiTargetEncodedResponse::ByteSizeLong () const final
Definition at line 6070 of file icub.pb.cc.
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::MultiTargetEncodedResponse::ByteSizeLong () const final
Clear() [1/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::Clear () final
Definition at line 5933 of file icub.pb.cc.
Referenced by CopyFrom().
clear_angle() [1/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::clear_angle () inline
Definition at line 3842 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_angle() [2/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::clear_angle ()
clear_status() [1/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::clear_status () inline
Definition at line 3825 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_status() [2/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::clear_status ()
CopyFrom() [1/4]
void iCubInterfaceMessages::MultiTargetEncodedResponse::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/4]
void iCubInterfaceMessages::MultiTargetEncodedResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 6134 of file icub.pb.cc.
CopyFrom() [3/4]
void iCubInterfaceMessages::MultiTargetEncodedResponse::CopyFrom (const MultiTargetEncodedResponse & from)
CopyFrom() [4/4]
void iCubInterfaceMessages::MultiTargetEncodedResponse::CopyFrom (const MultiTargetEncodedResponse & from)
Definition at line 6141 of file icub.pb.cc.
default_instance() [1/2]
static const MultiTargetEncodedResponse& iCubInterfaceMessages::MultiTargetEncodedResponse::default_instance () static
default_instance() [2/2]
const MultiTargetEncodedResponse & iCubInterfaceMessages::MultiTargetEncodedResponse::default_instance () static
Definition at line 5927 of file icub.pb.cc.
descriptor() [1/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::MultiTargetEncodedResponse::descriptor () static
descriptor() [2/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::MultiTargetEncodedResponse::descriptor () static
Definition at line 5922 of file icub.pb.cc.
GetCachedSize() [1/2]
int iCubInterfaceMessages::MultiTargetEncodedResponse::GetCachedSize () const inline final
Definition at line 2430 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::MultiTargetEncodedResponse::GetCachedSize () const inline final
Definition at line 2430 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
google::protobuf::Metadata iCubInterfaceMessages::MultiTargetEncodedResponse::GetMetadata () const final
Definition at line 6163 of file icub.pb.cc.
GetMetadata() [2/2]
::google::protobuf::Metadata iCubInterfaceMessages::MultiTargetEncodedResponse::GetMetadata () const final
InitAsDefaultInstance() [1/2]
static void iCubInterfaceMessages::MultiTargetEncodedResponse::InitAsDefaultInstance () static
InitAsDefaultInstance() [2/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::InitAsDefaultInstance () static
Definition at line 5884 of file icub.pb.cc.
internal_default_instance() [1/2]
static const MultiTargetEncodedResponse* iCubInterfaceMessages::MultiTargetEncodedResponse::internal_default_instance () inline static
Definition at line 2395 of file iCub_ANN_Interface/grpc/icub.pb.h.
internal_default_instance() [2/2]
static const MultiTargetEncodedResponse* iCubInterfaceMessages::MultiTargetEncodedResponse::internal_default_instance () inline static
Definition at line 2395 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::MultiTargetEncodedResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 6036 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::MultiTargetEncodedResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::MultiTargetEncodedResponse::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::MultiTargetEncodedResponse::IsInitialized () const final
Definition at line 6148 of file icub.pb.cc.
MergeFrom() [1/4]
void iCubInterfaceMessages::MultiTargetEncodedResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 6106 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/4]
void iCubInterfaceMessages::MultiTargetEncodedResponse::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [3/4]
void iCubInterfaceMessages::MultiTargetEncodedResponse::MergeFrom (const MultiTargetEncodedResponse & from)
MergeFrom() [4/4]
void iCubInterfaceMessages::MultiTargetEncodedResponse::MergeFrom (const MultiTargetEncodedResponse & from)
Definition at line 6121 of file icub.pb.cc.
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::MultiTargetEncodedResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 5944 of file icub.pb.cc.
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::MultiTargetEncodedResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_angle() [1/2]
::google::protobuf::RepeatedField< double >* iCubInterfaceMessages::MultiTargetEncodedResponse::mutable_angle ()
mutable_angle() [2/2]
google::protobuf::RepeatedField< double > * iCubInterfaceMessages::MultiTargetEncodedResponse::mutable_angle () inline
Definition at line 3863 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergePartialFromCodedStream().
New() [1/4]
MultiTargetEncodedResponse* iCubInterfaceMessages::MultiTargetEncodedResponse::New () const inline final
Definition at line 2409 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
MultiTargetEncodedResponse* iCubInterfaceMessages::MultiTargetEncodedResponse::New () const inline final
Definition at line 2409 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
MultiTargetEncodedResponse* iCubInterfaceMessages::MultiTargetEncodedResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 2413 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
MultiTargetEncodedResponse* iCubInterfaceMessages::MultiTargetEncodedResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 2413 of file iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
MultiTargetEncodedResponse& iCubInterfaceMessages::MultiTargetEncodedResponse::operator= (const MultiTargetEncodedResponse & from) inline
Definition at line 2372 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
MultiTargetEncodedResponse& iCubInterfaceMessages::MultiTargetEncodedResponse::operator= (const MultiTargetEncodedResponse & from) inline
Definition at line 2372 of file iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 6008 of file icub.pb.cc.
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_angle() [1/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::set_angle (int index, double value)
set_angle() [2/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::set_angle (int index, double value) inline
Definition at line 3849 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
set_status() [1/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::set_status (::iCubInterfaceMessages::Status value)
set_status() [2/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 3832 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status() [1/2]
iCubInterfaceMessages::Status iCubInterfaceMessages::MultiTargetEncodedResponse::status () const inline
Definition at line 3828 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
status() [2/2]
::iCubInterfaceMessages::Status iCubInterfaceMessages::MultiTargetEncodedResponse::status () const
Swap() [1/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::Swap (MultiTargetEncodedResponse * other)
Definition at line 6152 of file icub.pb.cc.
Swap() [2/2]
void iCubInterfaceMessages::MultiTargetEncodedResponse::Swap (MultiTargetEncodedResponse * other)
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 2478 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (MultiTargetEncodedResponse & a, MultiTargetEncodedResponse & b) friend
Definition at line 2403 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (MultiTargetEncodedResponse & a, MultiTargetEncodedResponse & b) friend
Definition at line 2403 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kAngleFieldNumber
static const int iCubInterfaceMessages::MultiTargetEncodedResponse::kAngleFieldNumber = 2 static
Definition at line 2455 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::MultiTargetEncodedResponse::kIndexInFileMessages static constexpr
Initial value:
=
    20
Definition at line 2399 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kStatusFieldNumber
static const int iCubInterfaceMessages::MultiTargetEncodedResponse::kStatusFieldNumber = 1 static
Definition at line 2466 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc