ANNarchy iCub Interface: iCubInterfaceMessages::SingleTargetRequest Class Reference
iCubInterfaceMessages::SingleTargetRequest Class Reference
#include <icub.pb.h>
Public Member Functions
SingleTargetRequest ()
virtual ~SingleTargetRequest ()
SingleTargetRequest (const SingleTargetRequest &from)
SingleTargetRequest & operator= (const SingleTargetRequest &from)
void Swap (SingleTargetRequest *other)
SingleTargetRequest * New () const final
SingleTargetRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SingleTargetRequest &from)
void MergeFrom (const SingleTargetRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_joint ()
::google::protobuf::int32 joint () const
void set_joint (::google::protobuf::int32 value)
SingleTargetRequest ()
virtual ~SingleTargetRequest ()
SingleTargetRequest (const SingleTargetRequest &from)
SingleTargetRequest & operator= (const SingleTargetRequest &from)
void Swap (SingleTargetRequest *other)
SingleTargetRequest * New () const final
SingleTargetRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SingleTargetRequest &from)
void MergeFrom (const SingleTargetRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_joint ()
::google::protobuf::int32 joint () const
void set_joint (::google::protobuf::int32 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SingleTargetRequest & default_instance ()
static void InitAsDefaultInstance ()
static const SingleTargetRequest * internal_default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const SingleTargetRequest & default_instance ()
static void InitAsDefaultInstance ()
static const SingleTargetRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kJointFieldNumber = 2
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (SingleTargetRequest &a, SingleTargetRequest &b)
void swap (SingleTargetRequest &a, SingleTargetRequest &b)
Detailed Description
Definition at line 1410 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Constructor & Destructor Documentation
SingleTargetRequest() [1/4]
iCubInterfaceMessages::SingleTargetRequest::SingleTargetRequest ()
Definition at line 3781 of file icub.pb.cc.
~SingleTargetRequest() [1/2]
iCubInterfaceMessages::SingleTargetRequest::~SingleTargetRequest () virtual
Definition at line 3800 of file icub.pb.cc.
SingleTargetRequest() [2/4]
iCubInterfaceMessages::SingleTargetRequest::SingleTargetRequest (const SingleTargetRequest & from)
Definition at line 3788 of file icub.pb.cc.
SingleTargetRequest() [3/4]
iCubInterfaceMessages::SingleTargetRequest::SingleTargetRequest ()
~SingleTargetRequest() [2/2]
virtual iCubInterfaceMessages::SingleTargetRequest::~SingleTargetRequest () virtual
SingleTargetRequest() [4/4]
iCubInterfaceMessages::SingleTargetRequest::SingleTargetRequest (const SingleTargetRequest & from)
Member Function Documentation
ByteSizeLong() [1/2]
size_t iCubInterfaceMessages::SingleTargetRequest::ByteSizeLong () const final
Definition at line 3914 of file icub.pb.cc.
ByteSizeLong() [2/2]
size_t iCubInterfaceMessages::SingleTargetRequest::ByteSizeLong () const final
Clear() [1/2]
void iCubInterfaceMessages::SingleTargetRequest::Clear () final
Clear() [2/2]
void iCubInterfaceMessages::SingleTargetRequest::Clear () final
Definition at line 3822 of file icub.pb.cc.
Referenced by CopyFrom().
clear_joint() [1/2]
void iCubInterfaceMessages::SingleTargetRequest::clear_joint () inline
Definition at line 3601 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
clear_joint() [2/2]
void iCubInterfaceMessages::SingleTargetRequest::clear_joint ()
CopyFrom() [1/4]
void iCubInterfaceMessages::SingleTargetRequest::CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/4]
void iCubInterfaceMessages::SingleTargetRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 3962 of file icub.pb.cc.
CopyFrom() [3/4]
void iCubInterfaceMessages::SingleTargetRequest::CopyFrom (const SingleTargetRequest & from)
CopyFrom() [4/4]
void iCubInterfaceMessages::SingleTargetRequest::CopyFrom (const SingleTargetRequest & from)
Definition at line 3969 of file icub.pb.cc.
default_instance() [1/2]
const SingleTargetRequest & iCubInterfaceMessages::SingleTargetRequest::default_instance () static
Definition at line 3816 of file icub.pb.cc.
default_instance() [2/2]
static const SingleTargetRequest& iCubInterfaceMessages::SingleTargetRequest::default_instance () static
descriptor() [1/2]
static const ::google::protobuf::Descriptor* iCubInterfaceMessages::SingleTargetRequest::descriptor () static
descriptor() [2/2]
const ::google::protobuf::Descriptor * iCubInterfaceMessages::SingleTargetRequest::descriptor () static
Definition at line 3811 of file icub.pb.cc.
GetCachedSize() [1/2]
int iCubInterfaceMessages::SingleTargetRequest::GetCachedSize () const inline final
Definition at line 1475 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
GetCachedSize() [2/2]
int iCubInterfaceMessages::SingleTargetRequest::GetCachedSize () const inline final
Definition at line 1475 of file iCub_ANN_Interface/grpc/icub.pb.h.
GetMetadata() [1/2]
google::protobuf::Metadata iCubInterfaceMessages::SingleTargetRequest::GetMetadata () const final
Definition at line 3990 of file icub.pb.cc.
GetMetadata() [2/2]
::google::protobuf::Metadata iCubInterfaceMessages::SingleTargetRequest::GetMetadata () const final
InitAsDefaultInstance() [1/2]
void iCubInterfaceMessages::SingleTargetRequest::InitAsDefaultInstance () static
Definition at line 3775 of file icub.pb.cc.
InitAsDefaultInstance() [2/2]
static void iCubInterfaceMessages::SingleTargetRequest::InitAsDefaultInstance () static
internal_default_instance() [1/2]
static const SingleTargetRequest* iCubInterfaceMessages::SingleTargetRequest::internal_default_instance () inline static
Definition at line 1440 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by default_instance().
internal_default_instance() [2/2]
static const SingleTargetRequest* iCubInterfaceMessages::SingleTargetRequest::internal_default_instance () inline static
Definition at line 1440 of file iCub_ANN_Interface/grpc/icub.pb.h.
InternalSerializeWithCachedSizesToArray() [1/2]
google::protobuf::uint8 * iCubInterfaceMessages::SingleTargetRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 3894 of file icub.pb.cc.
InternalSerializeWithCachedSizesToArray() [2/2]
::google::protobuf::uint8* iCubInterfaceMessages::SingleTargetRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized() [1/2]
bool iCubInterfaceMessages::SingleTargetRequest::IsInitialized () const final
IsInitialized() [2/2]
bool iCubInterfaceMessages::SingleTargetRequest::IsInitialized () const final
Definition at line 3976 of file icub.pb.cc.
joint() [1/2]
::google::protobuf::int32 iCubInterfaceMessages::SingleTargetRequest::joint () const
joint() [2/2]
google::protobuf::int32 iCubInterfaceMessages::SingleTargetRequest::joint () const inline
Definition at line 3604 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
MergeFrom() [1/4]
void iCubInterfaceMessages::SingleTargetRequest::MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/4]
void iCubInterfaceMessages::SingleTargetRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 3935 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [3/4]
void iCubInterfaceMessages::SingleTargetRequest::MergeFrom (const SingleTargetRequest & from)
MergeFrom() [4/4]
void iCubInterfaceMessages::SingleTargetRequest::MergeFrom (const SingleTargetRequest & from)
Definition at line 3950 of file icub.pb.cc.
MergePartialFromCodedStream() [1/2]
bool iCubInterfaceMessages::SingleTargetRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
MergePartialFromCodedStream() [2/2]
bool iCubInterfaceMessages::SingleTargetRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 3832 of file icub.pb.cc.
New() [1/4]
SingleTargetRequest* iCubInterfaceMessages::SingleTargetRequest::New () const inline final
Definition at line 1454 of file iCub_ANN_Interface/grpc/icub.pb.h.
New() [2/4]
SingleTargetRequest* iCubInterfaceMessages::SingleTargetRequest::New () const inline final
Definition at line 1454 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [3/4]
SingleTargetRequest* iCubInterfaceMessages::SingleTargetRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1458 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
New() [4/4]
SingleTargetRequest* iCubInterfaceMessages::SingleTargetRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1458 of file iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [1/2]
SingleTargetRequest& iCubInterfaceMessages::SingleTargetRequest::operator= (const SingleTargetRequest & from) inline
Definition at line 1417 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
operator=() [2/2]
SingleTargetRequest& iCubInterfaceMessages::SingleTargetRequest::operator= (const SingleTargetRequest & from) inline
Definition at line 1417 of file iCub_ANN_Interface/grpc/icub.pb.h.
SerializeWithCachedSizes() [1/2]
void iCubInterfaceMessages::SingleTargetRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 3876 of file icub.pb.cc.
SerializeWithCachedSizes() [2/2]
void iCubInterfaceMessages::SingleTargetRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_joint() [1/2]
void iCubInterfaceMessages::SingleTargetRequest::set_joint (::google::protobuf::int32 value)
set_joint() [2/2]
void iCubInterfaceMessages::SingleTargetRequest::set_joint (::google::protobuf::int32 value) inline
Definition at line 3608 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by MergeFrom().
Swap() [1/2]
void iCubInterfaceMessages::SingleTargetRequest::Swap (SingleTargetRequest * other)
Definition at line 3980 of file icub.pb.cc.
Swap() [2/2]
void iCubInterfaceMessages::SingleTargetRequest::Swap (SingleTargetRequest * other)
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 1509 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
swap [1/2]
void swap (SingleTargetRequest & a, SingleTargetRequest & b) friend
Definition at line 1448 of file iCub_ANN_Interface/grpc/icub.pb.h.
swap [2/2]
void swap (SingleTargetRequest & a, SingleTargetRequest & b) friend
Definition at line 1448 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Member Data Documentation
kIndexInFileMessages
static constexpr int iCubInterfaceMessages::SingleTargetRequest::kIndexInFileMessages static constexpr
Initial value:
=
    11
Definition at line 1444 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kJointFieldNumber
static const int iCubInterfaceMessages::SingleTargetRequest::kJointFieldNumber = 2 static
Definition at line 1499 of file build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h.
The documentation for this class was generated from the following files:
build/lib.linux-x86_64-3.8/iCub_ANN_Interface/grpc/icub.pb.h
icub.pb.cc