ANNarchy iCub Interface: iCubInterfaceMessages::SingleTargetResponse Class Reference
iCubInterfaceMessages::SingleTargetResponse Class Reference
#include <icub.pb.h>
Public Member Functions
SingleTargetResponse ()
virtual ~SingleTargetResponse ()
SingleTargetResponse (const SingleTargetResponse &from)
SingleTargetResponse & operator= (const SingleTargetResponse &from)
void Swap (SingleTargetResponse *other)
SingleTargetResponse * New () const final
SingleTargetResponse * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SingleTargetResponse &from)
void MergeFrom (const SingleTargetResponse &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_angle ()
double angle () const
void set_angle (double value)
void clear_status ()
::iCubInterfaceMessages::Status status () const
void set_status (::iCubInterfaceMessages::Status value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const SingleTargetResponse & default_instance ()
static void InitAsDefaultInstance ()
static const SingleTargetResponse * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kAngleFieldNumber = 2
static const int kStatusFieldNumber = 1
Friends
struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
void swap (SingleTargetResponse &a, SingleTargetResponse &b)
Detailed Description
Definition at line 1513 of file icub.pb.h.
Constructor & Destructor Documentation
SingleTargetResponse() [1/2]
iCubInterfaceMessages::SingleTargetResponse::SingleTargetResponse ()
Definition at line 4005 of file icub.pb.cc.
~SingleTargetResponse()
iCubInterfaceMessages::SingleTargetResponse::~SingleTargetResponse () virtual
Definition at line 4028 of file icub.pb.cc.
SingleTargetResponse() [2/2]
iCubInterfaceMessages::SingleTargetResponse::SingleTargetResponse (const SingleTargetResponse & from)
Definition at line 4012 of file icub.pb.cc.
Member Function Documentation
angle()
double iCubInterfaceMessages::SingleTargetResponse::angle () const inline
Definition at line 3636 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), WriteClientInstance::retrieve_singletarget(), and SerializeWithCachedSizes().
ByteSizeLong()
size_t iCubInterfaceMessages::SingleTargetResponse::ByteSizeLong () const final
Definition at line 4171 of file icub.pb.cc.
Clear()
void iCubInterfaceMessages::SingleTargetResponse::Clear () final
Definition at line 4050 of file icub.pb.cc.
Referenced by CopyFrom().
clear_angle()
void iCubInterfaceMessages::SingleTargetResponse::clear_angle () inline
Definition at line 3633 of file icub.pb.h.
clear_status()
void iCubInterfaceMessages::SingleTargetResponse::clear_status () inline
Definition at line 3619 of file icub.pb.h.
CopyFrom() [1/2]
void iCubInterfaceMessages::SingleTargetResponse::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 4226 of file icub.pb.cc.
CopyFrom() [2/2]
void iCubInterfaceMessages::SingleTargetResponse::CopyFrom (const SingleTargetResponse & from)
Definition at line 4233 of file icub.pb.cc.
default_instance()
const SingleTargetResponse & iCubInterfaceMessages::SingleTargetResponse::default_instance () static
Definition at line 4044 of file icub.pb.cc.
descriptor()
const ::google::protobuf::Descriptor * iCubInterfaceMessages::SingleTargetResponse::descriptor () static
Definition at line 4039 of file icub.pb.cc.
GetCachedSize()
int iCubInterfaceMessages::SingleTargetResponse::GetCachedSize () const inline final
Definition at line 1578 of file icub.pb.h.
GetMetadata()
google::protobuf::Metadata iCubInterfaceMessages::SingleTargetResponse::GetMetadata () const final
Definition at line 4255 of file icub.pb.cc.
InitAsDefaultInstance()
void iCubInterfaceMessages::SingleTargetResponse::InitAsDefaultInstance () static
Definition at line 3998 of file icub.pb.cc.
internal_default_instance()
static const SingleTargetResponse* iCubInterfaceMessages::SingleTargetResponse::internal_default_instance () inline static
Definition at line 1543 of file icub.pb.h.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * iCubInterfaceMessages::SingleTargetResponse::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 4145 of file icub.pb.cc.
IsInitialized()
bool iCubInterfaceMessages::SingleTargetResponse::IsInitialized () const final
Definition at line 4240 of file icub.pb.cc.
MergeFrom() [1/2]
void iCubInterfaceMessages::SingleTargetResponse::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 4196 of file icub.pb.cc.
Referenced by CopyFrom().
MergeFrom() [2/2]
void iCubInterfaceMessages::SingleTargetResponse::MergeFrom (const SingleTargetResponse & from)
Definition at line 4211 of file icub.pb.cc.
MergePartialFromCodedStream()
bool iCubInterfaceMessages::SingleTargetResponse::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 4062 of file icub.pb.cc.
New() [1/2]
SingleTargetResponse* iCubInterfaceMessages::SingleTargetResponse::New () const inline final
Definition at line 1557 of file icub.pb.h.
New() [2/2]
SingleTargetResponse* iCubInterfaceMessages::SingleTargetResponse::New (::google::protobuf::Arena * arena) const inline final
Definition at line 1561 of file icub.pb.h.
operator=()
SingleTargetResponse& iCubInterfaceMessages::SingleTargetResponse::operator= (const SingleTargetResponse & from) inline
Definition at line 1520 of file icub.pb.h.
SerializeWithCachedSizes()
void iCubInterfaceMessages::SingleTargetResponse::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 4121 of file icub.pb.cc.
set_angle()
void iCubInterfaceMessages::SingleTargetResponse::set_angle (double value) inline
Definition at line 3640 of file icub.pb.h.
Referenced by MergeFrom().
set_status()
void iCubInterfaceMessages::SingleTargetResponse::set_status (::iCubInterfaceMessages::Status value) inline
Definition at line 3626 of file icub.pb.h.
Referenced by MergeFrom(), and MergePartialFromCodedStream().
status()
iCubInterfaceMessages::Status iCubInterfaceMessages::SingleTargetResponse::status () const inline
Definition at line 3622 of file icub.pb.h.
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), and SerializeWithCachedSizes().
Swap()
void iCubInterfaceMessages::SingleTargetResponse::Swap (SingleTargetResponse * other)
Definition at line 4244 of file icub.pb.cc.
Friends And Related Function Documentation
::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct
friend struct ::protobuf_iCub_5fANN_5fInterface_2fgrpc_2ficub_2eproto::TableStruct friend
Definition at line 1619 of file icub.pb.h.
swap
void swap (SingleTargetResponse & a, SingleTargetResponse & b) friend
Definition at line 1551 of file icub.pb.h.
Member Data Documentation
kAngleFieldNumber
const int iCubInterfaceMessages::SingleTargetResponse::kAngleFieldNumber = 2 static
Definition at line 1602 of file icub.pb.h.
kIndexInFileMessages
constexpr int iCubInterfaceMessages::SingleTargetResponse::kIndexInFileMessages static constexpr
Initial value:
=
    12
Definition at line 1547 of file icub.pb.h.
Referenced by descriptor(), and GetMetadata().
kStatusFieldNumber
const int iCubInterfaceMessages::SingleTargetResponse::kStatusFieldNumber = 1 static
Definition at line 1608 of file icub.pb.h.
The documentation for this class was generated from the following files:
icub.pb.h
icub.pb.cc