from typing import Any

class ClockInterface:
    def __init__(self, *args, **kwargs) -> None: ...
    def sync_input(self, *args, **kwargs) -> Any: ...
    def update(self, *args, **kwargs) -> Any: ...

class MasterClock:
    def __init__(self, *args, **kwargs) -> None: ...
    def add(self, *args, **kwargs) -> Any: ...
    def update(self, *args, **kwargs) -> Any: ...
